import type { SectionConfig } from './types'

export const aiSection: SectionConfig = {
  key: 'ai',
  base: '/ai/',
  navText: 'Agent',
  overviewDescription:
    '适合希望系统入门并继续深入 Agent 和 LLM 应用开发的工程师，覆盖 Agent、Tool Calling、RAG、workflow，以及 Memory、Eval、Multi-Agent、知识系统设计、协议治理、运行优化、数据闭环和生产交付。',
  landing: {
    eyebrow: 'Agent',
    title: 'Agent 方向',
    intro:
      '从 Agent 模式、Tool Calling、RAG 到 workflow 设计，再延伸到 Memory、Eval、Multi-Agent、可观测性、数据闭环与生产交付，把零散资料收敛成一条更适合工程师持续推进的学习路径。',
    primary: { title: '知识地图', href: '/ai/knowledge-map', description: '先建立全局地图。' },
    secondary: { title: '综合指南', href: '/ai/agent-learning-guide', description: '再进入系统学习。' },
    scope: [
      'Agent 开发',
      'Tool Calling',
      'Workflow 与状态机',
      'RAG 与知识库',
      'Memory 与状态管理',
      'Eval 与回归',
      'Multi-Agent 与 Handoff',
      '可观测性、回放与复盘',
      '知识系统与向量检索选型',
      '协议、治理与成本控制',
      '实验、人工接管与运行优化',
      '数据闭环、长任务与灰度交付',
      '框架选型与产品化落地',
      'LLM 基础与学习路径',
    ],
    docs: [
      { title: 'LLM Agent 必学知识地图', href: '/ai/knowledge-map', description: '先搭整体认知框架，明确主题之间的关系。' },
      { title: 'Agent 学习综合指南', href: '/ai/agent-learning-guide', description: '用一篇长文把核心概念、资料和实践建议串起来。' },
      { title: 'Prompt Engineering 实践指南', href: '/ai/prompt-engineering', description: '聚焦提示词设计、格式约束、Few-shot 与工程化管理。' },
      { title: 'Context Engineering 实践指南', href: '/ai/context-engineering', description: '聚焦上下文选择、排序、摘要、记忆与动态组装。' },
      { title: 'Harness Engineering 实践指南', href: '/ai/harness-engineering', description: '聚焦 Agent 运行时、状态、权限、重试、观测与回放。' },
      { title: 'Agent Eval 设计与回归实践', href: '/ai/eval-design-and-regression', description: '把用例集、指标、LLM-as-Judge、回归测试和线上复盘串成闭环。' },
      { title: 'Agent Memory 设计与状态管理', href: '/ai/memory-design-and-state-management', description: '区分工作记忆、会话摘要、长期记忆与任务状态，讲清读写和遗忘策略。' },
      { title: 'Multi-Agent、Handoff 与路由边界', href: '/ai/multi-agent-handoff-and-routing', description: '讲清 single-agent 与 multi-agent 的分界、handoff 与 tool calling 的区别、路由模式和失败点。' },
      { title: 'Agent 可观测性、回放与故障复盘', href: '/ai/observability-replay-and-incident-review', description: '讲清 trace、step 日志、prompt/context 版本、回放与事故复盘闭环。' },
      { title: '模型、工具与知识库协同设计', href: '/ai/model-tool-knowledge-collaboration', description: '讲清模型、工具、知识库、记忆和工作流分别该解决什么问题。' },
      { title: 'Fine-tuning 边界与适用场景', href: '/ai/fine-tuning-boundaries', description: '讲清什么时候该先改 Prompt、RAG、工具和工作流，什么时候才值得做微调。' },
      { title: '向量数据库选型：pgvector、Milvus、Weaviate、Qdrant', href: '/ai/vector-database-selection', description: '按规模、运维复杂度和演进路径看向量数据库选型。' },
      { title: 'MCP 协议与工具接入', href: '/ai/mcp-protocol-and-tool-integration', description: '讲清 MCP 的定位、与 Tool Calling 的关系，以及什么时候值得做标准化接入。' },
      { title: 'Guardrails、审批与沙箱边界', href: '/ai/guardrails-approvals-and-sandboxing', description: '讲清拒答、审批、最小权限、只读隔离和沙箱执行分别解决什么问题。' },
      { title: '模型路由与成本控制', href: '/ai/model-routing-and-cost-control', description: '讲清强模型/快模型分层、预算控制、缓存与成本回归。' },
      { title: 'Prompt 版本化、实验与回滚', href: '/ai/prompt-versioning-experiments-and-rollbacks', description: '讲清 prompt/context/tool/workflow 如何一起版本化，以及 A/B、影子流量和回滚怎么做。' },
      { title: 'Human-in-the-loop、人工接管与升级策略', href: '/ai/human-in-the-loop-and-escalation', description: '讲清人工接管、审批、人工校对、人工终审和交接包的边界。' },
      { title: 'Agent 缓存、延迟与吞吐优化', href: '/ai/caching-latency-and-throughput-optimization', description: '讲清缓存、上下文压缩、并发设计、流式输出和高频路径优化顺序。' },
      { title: 'Agent 数据集构建、标注与合成数据', href: '/ai/dataset-curation-labeling-and-synthetic-data', description: '讲清真实样本沉淀、标注规范、合成数据边界、数据集版本化和线上回流。' },
      { title: 'Agent 长任务、队列与检查点恢复', href: '/ai/long-running-agents-queues-and-checkpointing', description: '讲清异步任务、队列、worker、幂等、检查点、补偿和人工恢复。' },
      { title: 'Agent 灰度发布、变更管理与回滚', href: '/ai/release-strategies-change-management-and-rollbacks', description: '讲清 Agent 变更包、影子流量、灰度策略、发布闸门和整包回滚。' },
      { title: 'Agent 产品化 Checklist', href: '/ai/agent-productization-checklist', description: '从权限、评测、回放、预算、灰度和运营反馈看 Agent 上线清单。' },
      { title: 'Agent 框架选型对比：LangGraph、LangChain、LlamaIndex、AutoGen、原生 SDK', href: '/ai/framework-selection-and-comparison', description: '按任务形状、控制流、RAG 比重和团队可控性看框架选型。' },
      { title: 'Agent横向对比：OpenClaw、Hermes-Agent、Claude Code、Codex', href: '/ai/coding-agents-comparison', description: '按运行形态、扩展机制、权限沙箱、记忆与可观测性六维对比主流编程类 Agent。' },
      { title: '本地知识库构建实践', href: '/ai/local-knowledge-base-practice', description: '讲清本地文档知识库的清洗、切块、元信息、索引更新和评测闭环。' },
      { title: 'Agent 常见失败案例复盘', href: '/ai/agent-failure-postmortems', description: '按 Prompt、Context、Tool、Workflow、权限和 Eval 六类常见事故模式做复盘。' },
      { title: 'Agent 能力自检题与案例', href: '/ai/agent-self-check-and-cases', description: '用判断题和案例题检查是否真正掌握 Prompt、RAG、Tool、Workflow 和产品化边界。' },
      { title: 'Agent Skill 设计与实践', href: '/ai/skill-design-and-practice', description: '聚焦 skill 的边界、结构、设计原则与团队落地。' },
      { title: 'Skill 类型模板速查', href: '/ai/skill-templates-by-type', description: '6 类常见 skill 的可复用模板（review、发布、排障、文档、工具、多 Agent）。' },
      { title: 'Skill 案例：review-checklist', href: '/ai/skill-case-review-checklist', description: '从 0 到 1 设计一个真实 skill 的完整演进过程。' },
      { title: '7 天 Agent 学习路线', href: '/ai/agent-learning-roadmap', description: '适合短周期起步，先把路径跑通。' },
      { title: 'Tool Calling 设计清单', href: '/ai/tool-calling-design-checklist', description: '关注接口设计、容错和运行边界。' },
      { title: 'RAG 基础与工作流', href: '/ai/rag-basics-and-workflow', description: '把检索、切分、召回和生成串成一个可理解的流程。' },
      { title: '待补主题清单', href: '/ai/todo-topics', description: '查看还未展开的补充主题。' },
    ],
    order: [
      'LLM Agent 必学知识地图',
      'Agent 学习综合指南',
      'Prompt Engineering 实践指南',
      'Context Engineering 实践指南',
      'Harness Engineering 实践指南',
      'Agent Eval 设计与回归实践',
      'Agent Memory 设计与状态管理',
      'Multi-Agent、Handoff 与路由边界',
      'Agent 可观测性、回放与故障复盘',
      '模型、工具与知识库协同设计',
      'Fine-tuning 边界与适用场景',
      '向量数据库选型：pgvector、Milvus、Weaviate、Qdrant',
      'MCP 协议与工具接入',
      'Guardrails、审批与沙箱边界',
      '模型路由与成本控制',
      'Prompt 版本化、实验与回滚',
      'Human-in-the-loop、人工接管与升级策略',
      'Agent 缓存、延迟与吞吐优化',
      'Agent 数据集构建、标注与合成数据',
      'Agent 长任务、队列与检查点恢复',
      'Agent 灰度发布、变更管理与回滚',
      'Agent 产品化 Checklist',
      'Agent 框架选型对比：LangGraph、LangChain、LlamaIndex、AutoGen、原生 SDK',
      'Agent横向对比：OpenClaw、Hermes-Agent、Claude Code、Codex',
      '本地知识库构建实践',
      'Agent 常见失败案例复盘',
      'Agent 能力自检题与案例',
      'Agent Skill 设计与实践',
      'Skill 类型模板速查',
      'Skill 案例：review-checklist',
      '7 天 Agent 学习路线',
      'Tool Calling 设计清单',
      'RAG 基础与工作流',
    ],
  },
  sidebar: [
    {
      text: 'AI 专题',
      items: [
        { text: '方向概览', link: '/ai/' },
        { text: '知识地图', link: '/ai/knowledge-map' },
        { text: '综合指南', link: '/ai/agent-learning-guide' },
        { text: 'Prompt 指南', link: '/ai/prompt-engineering' },
        { text: 'Context 指南', link: '/ai/context-engineering' },
        { text: 'Harness 指南', link: '/ai/harness-engineering' },
        { text: 'Tool 清单', link: '/ai/tool-calling-design-checklist' },
        { text: 'RAG 基础', link: '/ai/rag-basics-and-workflow' },
        { text: 'Skill 指南', link: '/ai/skill-design-and-practice' },
        { text: 'Skill 模板速查', link: '/ai/skill-templates-by-type' },
        { text: 'Skill 案例', link: '/ai/skill-case-review-checklist' },
        { text: '待补清单', link: '/ai/todo-topics' },
      ],
    },
    {
      text: '进阶专题',
      items: [
        { text: 'Eval 设计', link: '/ai/eval-design-and-regression' },
        { text: 'Memory 设计', link: '/ai/memory-design-and-state-management' },
        { text: 'Multi-Agent', link: '/ai/multi-agent-handoff-and-routing' },
        { text: '观测与回放', link: '/ai/observability-replay-and-incident-review' },
        { text: '协同设计', link: '/ai/model-tool-knowledge-collaboration' },
        { text: 'Fine-tuning', link: '/ai/fine-tuning-boundaries' },
        { text: '向量数据库', link: '/ai/vector-database-selection' },
      ],
    },
    {
      text: '协议与治理',
      items: [
        { text: 'MCP 协议', link: '/ai/mcp-protocol-and-tool-integration' },
        { text: 'Guardrails', link: '/ai/guardrails-approvals-and-sandboxing' },
        { text: '模型路由', link: '/ai/model-routing-and-cost-control' },
      ],
    },
    {
      text: '运行优化',
      items: [
        { text: 'Prompt 实验', link: '/ai/prompt-versioning-experiments-and-rollbacks' },
        { text: '人工接管', link: '/ai/human-in-the-loop-and-escalation' },
        { text: '缓存与延迟', link: '/ai/caching-latency-and-throughput-optimization' },
      ],
    },
    {
      text: '数据与交付',
      items: [
        { text: '数据集与合成数据', link: '/ai/dataset-curation-labeling-and-synthetic-data' },
        { text: '长任务与队列', link: '/ai/long-running-agents-queues-and-checkpointing' },
        { text: '灰度与回滚', link: '/ai/release-strategies-change-management-and-rollbacks' },
      ],
    },
    {
      text: '落地实践',
      items: [
        { text: '产品化清单', link: '/ai/agent-productization-checklist' },
        { text: '框架选型', link: '/ai/framework-selection-and-comparison' },
        { text: 'Agent对比', link: '/ai/coding-agents-comparison' },
        { text: '本地知识库', link: '/ai/local-knowledge-base-practice' },
        { text: '失败复盘', link: '/ai/agent-failure-postmortems' },
        { text: '能力自检', link: '/ai/agent-self-check-and-cases' },
      ],
    },
    {
      text: '七天路线',
      collapsed: true,
      items: [
        { text: '路线总览', link: '/ai/agent-learning-roadmap' },
        { text: 'D1 Agent 概念', link: '/ai/roadmap/day1-what-is-agent' },
        { text: 'D2 LLM API', link: '/ai/roadmap/day2-llm-api' },
        { text: 'D3 Tool 调用', link: '/ai/roadmap/day3-tool-calling' },
        { text: 'D4 Workflow', link: '/ai/roadmap/day4-workflow' },
        { text: 'D5 RAG 记忆', link: '/ai/roadmap/day5-rag-memory' },
        { text: 'D6 评测安全', link: '/ai/roadmap/day6-eval-safety' },
        { text: 'D7 完整项目', link: '/ai/roadmap/day7-full-project' },
      ],
    },
  ],
}
