import type { SectionConfig } from './types'

export const architectureSection: SectionConfig = {
  key: 'architecture',
  base: '/architecture/',
  navText: '架构',
  overviewDescription:
    '适合后端开发、技术负责人候选人和架构岗准备，主线是系统设计、架构方法、治理和分布式能力。',
  landing: {
    eyebrow: 'Architecture',
    title: '架构方向',
    intro:
      '围绕系统设计、高并发、分布式设计、评审方法与治理实践，把架构学习整理成适合长期复用的框架、清单和路线。',
    primary: { title: '学习路线', href: '/architecture/architect-learning-roadmap', description: '先搭主线。' },
    secondary: { title: '能力自检', href: '/architecture/architect-interview-prep-checklist', description: '再用清单校验。' },
    scope: [
      '系统设计',
      '核心基础',
      '分布式系统',
      '微服务与中间件',
      '数据架构',
      '云原生与 DevOps',
      '高可用与稳定性治理',
      '架构方法论与技术规划',
      '案例实战',
      'MySQL 深入学习',
    ],
    docs: [
      { title: '学习路线', href: '/architecture/architect-learning-roadmap', description: '先看各阶段该补什么。' },
      { title: '分阶书单', href: '/architecture/architect-booklist-by-level', description: '按成长阶段选更合适的资料。' },
      { title: '能力自检', href: '/architecture/architect-interview-prep-checklist', description: '用判断项校验系统设计与治理能力。' },
      { title: '设计方法与评审', href: '/architecture/architecture-design-method-and-review-checklist', description: '从目标、约束、容量到治理，建立设计骨架。' },
      { title: 'AI / IM / 云原生', href: '/architecture/ai-im-k8s-architecture-interview-guide', description: '围绕 AI 工程化、IM/直播和 K8s，整理高级后端主线。' },
      { title: '百万长连接网关', href: '/architecture/go-million-connection-gateway-design', description: '围绕分层、组件命名、技术选型与性能调优展开。' },
      { title: 'EMQX 长连接平台', href: '/architecture/go-emqx-million-connection-platform-design', description: '围绕 EMQX 连接层与 Go 业务层，梳理平台化架构主线。' },
      { title: '高并发系统设计', href: '/architecture/high-concurrency-system-design-core-points', description: '按流量承载、正确性、高可用与分布式基础设施展开。' },
      { title: '分布式系统设计', href: '/architecture/distributed-system-design', description: '从 CAP、一致性到存储内核，建立分布式设计地图。' },
      { title: '交易平台架构', href: '/architecture/ecommerce-transaction-platform-production-architecture', description: '串起多活、交易链路、高可用与大促保障。' },
      { title: '一致性总览', href: '/architecture/transaction-system-consistency-overview', description: '把订单、库存、支付、延时任务、Outbox 与补偿收成一张图。' },
      { title: '超时与时间轮', href: '/architecture/order-timeout-cancellation-and-timing-wheel', description: '从超时取消切入，串起延时消息、时间轮、幂等与补偿。' },
      { title: '订单状态机', href: '/architecture/order-state-machine-design', description: '围绕支付、取消、退款链路讲清状态流转、幂等与并发竞争。' },
      { title: '延时任务对比', href: '/architecture/delayed-task-solution-comparison', description: '对比 MQ、Redis ZSet、时间轮等方案的边界与取舍。' },
      { title: 'Outbox 模式', href: '/architecture/outbox-pattern-design', description: '围绕写库与发消息一致性，讲清 Outbox 流程、重试与幂等。' },
      { title: '订单与库存', href: '/architecture/order-and-inventory-consistency-design', description: '围绕超卖防护、库存冻结、Outbox 与补偿，讲清订单库存一致性。' },
      { title: '支付回调', href: '/architecture/payment/callback-idempotency', description: '围绕验签、状态机收口、主动查询与对账补偿展开。' },
      { title: '交易风控', href: '/architecture/payment/risk-control', description: '围绕规则引擎、限额限频、KYC/AML 与风控决策链路展开。' },
      { title: '反欺诈', href: '/architecture/payment/fraud-detection', description: '围绕欺诈识别、特征工程、拒付争议与反欺诈运营展开。' },
      { title: '分布式事务', href: '/architecture/distributed-transaction-comparison', description: '快速对比常见事务方案的边界与取舍。' },
      { title: '库存设计', href: '/architecture/seckill-system-inventory-design', description: '围绕预扣减、异步下单、热点库存与回补补偿展开。' },
      { title: '限流与降级', href: '/architecture/seckill-system-rate-limiting-and-degradation', description: '围绕预热、限流、削峰、背压与降级策略展开。' },
      { title: '风控与防刷', href: '/architecture/seckill-risk-control-and-eligibility-design', description: '围绕资格校验、抢购 Token 与误杀恢复展开。' },
      { title: '排队与结果', href: '/architecture/seckill-result-query-and-queueing-ux-design', description: '围绕排队态、结果查询与失败提示展开。' },
      { title: '监控与应急', href: '/architecture/seckill-monitoring-alerting-and-incident-response', description: '围绕指标、告警、值守与止血动作展开。' },
      { title: '压测与容量', href: '/architecture/seckill-pressure-testing-capacity-estimation-and-drills', description: '围绕流量模型、容量估算、压测与演练展开。' },
      { title: '活动平台设计', href: '/architecture/marketing-activity-platform-architecture', description: '围绕模板、规则、发放、核销与平台治理展开。' },
      { title: '大促保障手册', href: '/architecture/promotion-readiness-pressure-test-and-switch-governance', description: '围绕预热、压测、灰度放量与值守展开。' },
      { title: '活动复盘手册', href: '/architecture/activity-postmortem-and-capacity-regression-playbook', description: '围绕时间线、容量回归、阈值修正与责任闭环展开。' },
      { title: '抢券系统设计', href: '/architecture/coupon-claim-system-design-and-comparison', description: '围绕领券资格、库存配额、异步发券与核销展开。' },
      { title: 'PostgreSQL 高可用', href: '/postgresql/ha-cluster', description: 'Patroni、WAL 流复制与故障恢复速查。' },
      { title: '支付系统总览', href: '/architecture/payment/', description: '收录支付系统架构设计与高并发实践完整专题。' },
      { title: '高并发支付', href: '/architecture/payment/high-concurrency-notes', description: '围绕 Go 性能、分布式事务、资金安全与清结算做系统梳理。' },
      { title: '架构案例实战', href: '/architecture/case-studies/', description: '收录组织设计与出海架构案例。' },
      { title: '待补主题', href: '/architecture/todo-topics', description: '查看后续计划补充的专题。' },
    ],
    order: [
      '学习路线',
      '分阶书单',
      '能力自检',
      '设计方法与评审',
      'AI / IM / 云原生',
      '百万长连接网关',
      'EMQX 长连接平台',
      '高并发系统设计',
      '分布式系统设计',
      '交易平台架构',
      '一致性总览',
      '超时与时间轮',
      '订单状态机',
      '延时任务对比',
      'Outbox 模式',
      '订单与库存',
      '支付系统总览',
      '支付回调',
      '高并发支付',
      '交易风控',
      '反欺诈',
      '分布式事务',
      '库存设计',
      '限流与降级',
      '风控与防刷',
      '排队与结果',
      '监控与应急',
      '压测与容量',
      '活动平台设计',
      '大促保障手册',
      '活动复盘手册',
      '抢券系统设计',
      'PostgreSQL 高可用',
      '架构案例实战',
    ],
  },
  sidebar: [
    {
      text: '方向概览',
      items: [
        { text: '方向概览', link: '/architecture/' },
      ],
    },
    {
      text: '学习路线',
      items: [
        { text: '学习路线', link: '/architecture/architect-learning-roadmap' },
        { text: '分阶书单', link: '/architecture/architect-booklist-by-level' },
        { text: '能力自检', link: '/architecture/architect-interview-prep-checklist' },
        { text: '设计方法与评审', link: '/architecture/architecture-design-method-and-review-checklist' },
        { text: 'AI / IM / 云原生', link: '/architecture/ai-im-k8s-architecture-interview-guide' },
        { text: '长连接网关', link: '/architecture/go-million-connection-gateway-design' },
        { text: 'EMQX 平台', link: '/architecture/go-emqx-million-connection-platform-design' },
        { text: '高并发设计', link: '/architecture/high-concurrency-system-design-core-points' },
        { text: '分布式设计', link: '/architecture/distributed-system-design' },
      ],
    },
    {
      text: '交易一致',
      items: [
        { text: '一致性总览', link: '/architecture/transaction-system-consistency-overview' },
        { text: '交易平台架构', link: '/architecture/ecommerce-transaction-platform-production-architecture' },
        { text: '超时与时间轮', link: '/architecture/order-timeout-cancellation-and-timing-wheel' },
        { text: '订单状态机', link: '/architecture/order-state-machine-design' },
        { text: '延时任务对比', link: '/architecture/delayed-task-solution-comparison' },
        { text: 'Outbox 模式', link: '/architecture/outbox-pattern-design' },
        { text: '订单与库存', link: '/architecture/order-and-inventory-consistency-design' },
        { text: '分布式事务', link: '/architecture/distributed-transaction-comparison' },
      ],
    },
    {
      text: '支付系统',
      items: [
        { text: '支付总览', link: '/architecture/payment/' },
        { text: '回调幂等', link: '/architecture/payment/callback-idempotency' },
        { text: '高并发支付', link: '/architecture/payment/high-concurrency-notes' },
        { text: '交易风控', link: '/architecture/payment/risk-control' },
        { text: '反欺诈', link: '/architecture/payment/fraud-detection' },
      ],
    },
    {
      text: '秒杀专题',
      items: [
        { text: '库存设计', link: '/architecture/seckill-system-inventory-design' },
        { text: '限流与降级', link: '/architecture/seckill-system-rate-limiting-and-degradation' },
        { text: '风控与防刷', link: '/architecture/seckill-risk-control-and-eligibility-design' },
        { text: '排队与结果', link: '/architecture/seckill-result-query-and-queueing-ux-design' },
        { text: '监控与应急', link: '/architecture/seckill-monitoring-alerting-and-incident-response' },
        { text: '压测与容量', link: '/architecture/seckill-pressure-testing-capacity-estimation-and-drills' },
      ],
    },
    {
      text: '营销活动',
      items: [
        { text: '活动平台', link: '/architecture/marketing-activity-platform-architecture' },
        { text: '大促保障', link: '/architecture/promotion-readiness-pressure-test-and-switch-governance' },
        { text: '活动复盘', link: '/architecture/activity-postmortem-and-capacity-regression-playbook' },
        { text: '抢券系统', link: '/architecture/coupon-claim-system-design-and-comparison' },
      ],
    },
    {
      text: '案例实战',
      items: [
        { text: '案例概览', link: '/architecture/case-studies/' },
        { text: '组织设计', link: '/architecture/case-studies/organization-structure-and-business-system-design' },
        { text: '出海架构', link: '/architecture/case-studies/global-fitness-app-architecture-and-management-guide' },
      ],
    },
    {
      text: '待补主题',
      items: [
        { text: '待补主题', link: '/architecture/todo-topics' },
      ],
    },
  ],
}
