import type { SectionConfig } from './types'

export const architectureSection: SectionConfig = {
  key: 'architecture',
  base: '/architecture/',
  navText: '架构',
  overviewDescription:
    '适合后端开发、技术负责人候选人和架构岗准备，主线是系统设计、治理和分布式能力。',
  landing: {
    eyebrow: 'Architecture',
    title: '架构方向',
    intro:
      '围绕系统设计、高并发、分布式事务与治理方法，把架构学习整理成适合长期复用的框架、清单和路线。',
    primary: { title: '学习路线', href: '/architecture/architect-learning-roadmap', description: '先搭主线。' },
    secondary: { title: '能力自检', href: '/architecture/architect-interview-prep-checklist', description: '再用清单校验。' },
    scope: [
      '系统设计',
      '核心基础',
      '分布式系统',
      '微服务与中间件',
      '数据架构',
      '云原生与 DevOps',
      '高可用与稳定性治理',
      '架构方法论与技术规划',
      '案例实战',
      'MySQL 深入学习',
    ],
    docs: [
      { title: '学习路线', href: '/architecture/architect-learning-roadmap', description: '适合作为主入口，先看清楚各阶段该补什么。' },
      { title: '分阶书单', href: '/architecture/architect-booklist-by-level', description: '按成长阶段筛选更合适的资料。' },
      { title: '能力自检', href: '/architecture/architect-interview-prep-checklist', description: '用判断项梳理系统设计和架构治理能力。' },
      { title: 'AI / IM / 云原生', href: '/architecture/ai-im-k8s-architecture-interview-guide', description: '围绕 Go、MySQL、Redis、Kafka、AI 工程化、IM/直播和 K8s，整理一套适合高级后端岗位准备的面试主线。' },
      { title: '百万长连接网关', href: '/architecture/go-million-connection-gateway-design', description: '基于 Go 设计支持百万级 WebSocket 与 MQTT 长连接的高可用网关系统，覆盖架构分层、核心组件命名、技术选型与性能调优。' },
      { title: 'Go + EMQX 长连接平台', href: '/architecture/go-emqx-million-connection-platform-design', description: '以 EMQX 5.x 为连接层核心，Go 微服务为业务层，覆盖 IM、IoT 和通用长连接平台的完整架构设计。' },
      { title: '高并发清单', href: '/architecture/high-concurrency-system-checklist', description: '把常见高并发设计问题拆成一组可检查项。' },
      { title: '高并发系统设计核心要点', href: '/architecture/architecture', description: '按流量承载、业务正确性、高可用保障和分布式基础设施四层，系统梳理高并发系统设计的核心抓手。' },
      { title: '一致性总览', href: '/architecture/transaction-system-consistency-overview', description: '把订单、库存、支付、延时任务、Outbox 与补偿主线收成一张统一的交易一致性地图。' },
      { title: '超时与时间轮', href: '/architecture/order-timeout-cancellation-and-timing-wheel', description: '从 30 分钟未支付自动取消切入，串起延时消息、时间轮、状态机幂等与补偿兜底。' },
      { title: '订单状态机', href: '/architecture/order-state-machine-design', description: '围绕支付、取消、退款等链路，讲清状态机设计、条件更新、幂等与并发竞争。' },
      { title: '延时任务对比', href: '/architecture/delayed-task-solution-comparison', description: '系统对比 RocketMQ、RabbitMQ、Redis ZSet、时间轮等延时任务方案的边界与取舍。' },
      { title: 'Outbox 消息表', href: '/architecture/outbox-pattern-design', description: '围绕写库与发消息的一致性问题，讲清 Outbox 的流程、表设计、重试与幂等。' },
      { title: '库存与订单', href: '/architecture/order-and-inventory-consistency-design', description: '围绕超卖防护、库存冻结、Outbox 与补偿恢复，讲清订单与库存的一致性设计。' },
      { title: '支付回调补偿', href: '/architecture/payment-callback-idempotency-and-compensation', description: '围绕签名校验、状态机收口、主动查询与对账补偿，讲清支付回调的一致性设计。' },
      { title: '分布式事务', href: '/architecture/distributed-transaction-comparison', description: '快速对比常见事务方案的边界与取舍。' },
      { title: '库存设计', href: '/architecture/seckill-system-inventory-design', description: '围绕资格过滤、Redis 预扣减、异步下单、热点库存和回补补偿，讲清秒杀系统库存设计主线。' },
      { title: '限流与降级', href: '/architecture/seckill-system-rate-limiting-and-degradation', description: '围绕活动预热、资格令牌、多层限流、排队削峰、背压与降级策略，讲清秒杀系统稳定性设计主线。' },
      { title: '风控与防刷', href: '/architecture/seckill-risk-control-and-eligibility-design', description: '围绕活动资格、抢购 Token、黑白名单、行为识别与误杀恢复，讲清秒杀系统入口治理主线。' },
      { title: '结果与体验', href: '/architecture/seckill-result-query-and-queueing-ux-design', description: '围绕排队态设计、结果查询接口、轮询与推送取舍、失败提示和状态收敛，讲清秒杀活动的用户体验主线。' },
      { title: '监控与应急', href: '/architecture/seckill-monitoring-alerting-and-incident-response', description: '围绕指标分层、告警分级、链路追踪、值守大盘、止血动作与复盘回写，讲清秒杀系统监控与应急治理主线。' },
      { title: '压测与容量', href: '/architecture/seckill-pressure-testing-capacity-estimation-and-drills', description: '围绕流量模型、容量估算、压测脚本、影子流量、故障注入与演练回写，讲清秒杀系统压测与容量验证主线。' },
      { title: '活动平台设计', href: '/architecture/marketing-activity-platform-architecture', description: '围绕活动模板、规则引擎、发放中心、券资产、核销链路、风控审计与平台治理，讲清营销活动平台的一体化架构主线。' },
      { title: '大促保障手册', href: '/architecture/promotion-readiness-pressure-test-and-switch-governance', description: '围绕容量估算、资源预热、全链路压测、灰度放量、开关矩阵与应急值守，讲清大促活动保障主线。' },
      { title: '活动复盘手册', href: '/architecture/activity-postmortem-and-capacity-regression-playbook', description: '围绕事实时间线、指标对比、容量回归、阈值修正、预案更新与责任闭环，讲清高峰活动后的复盘与资产沉淀主线。' },
      { title: '抢券系统设计', href: '/architecture/coupon-claim-system-design-and-comparison', description: '围绕券模板、领券资格、库存配额、异步发券、核销状态与用户限领，讲清抢券系统设计主线和它与秒杀系统的差异。' },
      { title: 'PostgreSQL 高可用集群整理', href: '/postgresql/ha-cluster', description: 'PG 高可用方案选型、Patroni 部署、WAL 流复制与故障恢复速查。' },
      { title: '架构案例实战', href: '/architecture/case-studies/', description: '收录偏业务落地的组织设计、PostgreSQL 高可用、支付系统与出海架构案例。' },
      { title: '待补主题', href: '/architecture/todo-topics', description: '查看后续计划补充的专题。' },
    ],
    order: [
      '学习路线',
      '分阶书单',
      '能力自检',
      'AI / IM / 云原生',
      '百万长连接网关',
      'Go + EMQX 长连接平台',
      '高并发清单',
      '高并发系统设计核心要点',
      '一致性总览',
      '超时与时间轮',
      '订单状态机',
      '延时任务对比',
      'Outbox 消息表',
      '库存与订单',
      '支付回调补偿',
      '分布式事务',
      '库存设计',
      '限流与降级',
      '风控与防刷',
      '结果与体验',
      '监控与应急',
      '压测与容量',
      '活动平台设计',
      '大促保障手册',
      '活动复盘手册',
      '抢券系统设计',
      'PostgreSQL 高可用集群整理',
      '架构案例实战',
    ],
  },
  sidebar: [
    {
      text: '方向概览',
      items: [
        { text: '方向概览', link: '/architecture/' },
      ],
    },
    {
      text: '学习路线',
      items: [
        { text: '学习路线', link: '/architecture/architect-learning-roadmap' },
        { text: '分阶书单', link: '/architecture/architect-booklist-by-level' },
        { text: '能力自检', link: '/architecture/architect-interview-prep-checklist' },
        { text: 'AI / IM / 云原生', link: '/architecture/ai-im-k8s-architecture-interview-guide' },
        { text: '长连接网关', link: '/architecture/go-million-connection-gateway-design' },
        { text: 'EMQX 平台', link: '/architecture/go-emqx-million-connection-platform-design' },
        { text: '高并发清单', link: '/architecture/high-concurrency-system-checklist' },
        { text: '高并发要点', link: '/architecture/architecture' },
      ],
    },
    {
      text: '交易一致',
      items: [
        { text: '一致性总览', link: '/architecture/transaction-system-consistency-overview' },
        { text: '超时与时间轮', link: '/architecture/order-timeout-cancellation-and-timing-wheel' },
        { text: '订单状态机', link: '/architecture/order-state-machine-design' },
        { text: '延时任务对比', link: '/architecture/delayed-task-solution-comparison' },
        { text: 'Outbox 消息表', link: '/architecture/outbox-pattern-design' },
        { text: '库存与订单', link: '/architecture/order-and-inventory-consistency-design' },
        { text: '支付回调补偿', link: '/architecture/payment-callback-idempotency-and-compensation' },
        { text: '分布式事务', link: '/architecture/distributed-transaction-comparison' },
      ],
    },
    {
      text: '秒杀专题',
      items: [
        { text: '库存设计', link: '/architecture/seckill-system-inventory-design' },
        { text: '限流与降级', link: '/architecture/seckill-system-rate-limiting-and-degradation' },
        { text: '风控与防刷', link: '/architecture/seckill-risk-control-and-eligibility-design' },
        { text: '结果与体验', link: '/architecture/seckill-result-query-and-queueing-ux-design' },
        { text: '监控与应急', link: '/architecture/seckill-monitoring-alerting-and-incident-response' },
        { text: '压测与容量', link: '/architecture/seckill-pressure-testing-capacity-estimation-and-drills' },
      ],
    },
    {
      text: '营销活动',
      items: [
        { text: '活动平台', link: '/architecture/marketing-activity-platform-architecture' },
        { text: '大促保障', link: '/architecture/promotion-readiness-pressure-test-and-switch-governance' },
        { text: '活动复盘', link: '/architecture/activity-postmortem-and-capacity-regression-playbook' },
        { text: '抢券系统', link: '/architecture/coupon-claim-system-design-and-comparison' },
      ],
    },
    {
      text: '案例实战',
      items: [
        { text: '案例概览', link: '/architecture/case-studies/' },
        { text: '组织设计', link: '/architecture/case-studies/organization-structure-and-business-system-design' },
        { text: '高并发支付', link: '/architecture/case-studies/high-concurrency-payment-system-practice-notes' },
        { text: '出海架构', link: '/architecture/case-studies/global-fitness-app-architecture-and-management-guide' },
      ],
    },
    {
      text: '待补主题',
      items: [
        { text: '待补主题', link: '/architecture/todo-topics' },
      ],
    },
  ],
}
