import type { SidebarEntry, SidebarGroup, SectionConfig } from './types'

const golangSourceReadingSidebar: SidebarGroup[] = [
  {
    text: '推荐先读',
    items: [
      { text: 'runtime：GMP 调度器', link: '/golang/guide/source-reading/runtime-scheduler' },
      { text: 'runtime：GC 垃圾回收', link: '/golang/guide/source-reading/runtime-gc' },
      { text: 'channel：底层实现', link: '/golang/guide/source-reading/channel' },
      { text: 'map：Swiss Table', link: '/golang/guide/source-reading/map' },
      { text: 'net/http：HTTP 实现', link: '/golang/guide/source-reading/net-http' },
      { text: 'database/sql：连接池', link: '/golang/guide/source-reading/database-sql' },
    ],
  },
  {
    text: '运行并发',
    collapsed: true,
    items: [
      { text: 'sync：同步原语', link: '/golang/guide/source-reading/sync-primitives' },
      { text: 'sync/atomic：原子操作', link: '/golang/guide/source-reading/sync-atomic' },
      { text: 'sync.Pool：对象池', link: '/golang/guide/source-reading/sync-pool' },
      { text: 'sync.Cond：条件变量', link: '/golang/guide/source-reading/sync-cond' },
      { text: 'context：上下文传播', link: '/golang/guide/source-reading/context' },
      { text: 'channel：底层实现', link: '/golang/guide/source-reading/channel' },
      { text: 'map：Swiss Table', link: '/golang/guide/source-reading/map' },
      { text: 'goroutine：生命周期', link: '/golang/guide/source-reading/goroutine' },
      { text: 'timer：定时器实现', link: '/golang/guide/source-reading/timer' },
      { text: 'runtime：GMP 调度器', link: '/golang/guide/source-reading/runtime-scheduler' },
      { text: 'runtime：GC 垃圾回收', link: '/golang/guide/source-reading/runtime-gc' },
      { text: 'runtime：内存分配', link: '/golang/guide/source-reading/runtime-memory' },
      { text: 'runtime/debug：调试工具', link: '/golang/guide/source-reading/runtime-debug' },
      { text: 'runtime/pprof：性能剖析', link: '/golang/guide/source-reading/runtime-pprof' },
      { text: 'runtime/trace：执行追踪', link: '/golang/guide/source-reading/runtime-trace' },
      { text: 'runtime/metrics：运行时指标', link: '/golang/guide/source-reading/runtime-metrics' },
      { text: 'runtime.SetFinalizer：GC 终结器', link: '/golang/guide/source-reading/runtime-finalizer' },
      { text: 'go-memory-tuning：内存调优', link: '/golang/guide/source-reading/go-memory-tuning' },
    ],
  },
  {
    text: '标准库',
    collapsed: true,
    items: [
      { text: 'errors：错误链', link: '/golang/guide/source-reading/errors' },
      { text: 'strings/bytes：字符串处理', link: '/golang/guide/source-reading/strings-bytes' },
      { text: 'fmt：格式化 I/O', link: '/golang/guide/source-reading/fmt' },
      { text: 'strconv：字符串转换', link: '/golang/guide/source-reading/strconv' },
      { text: 'sort/slices：排序算法', link: '/golang/guide/source-reading/sort' },
      { text: 'math/rand：随机数生成（含 v2）', link: '/golang/guide/source-reading/math-rand' },
      { text: 'math/big：任意精度算术', link: '/golang/guide/source-reading/math-big' },
      { text: 'math/bits：位操作', link: '/golang/guide/source-reading/math-bits' },
      { text: 'time：时间处理', link: '/golang/guide/source-reading/time-pkg' },
      { text: 'unsafe：内存操作', link: '/golang/guide/source-reading/unsafe' },
      { text: 'reflect：反射原理', link: '/golang/guide/source-reading/reflect' },
      { text: 'iter（Go 1.23+）：迭代器协议', link: '/golang/guide/source-reading/iter-pkg' },
      { text: 'unique（Go 1.23+）：字符串驻留', link: '/golang/guide/source-reading/unique-pkg' },
      { text: 'slices/maps/cmp：泛型标准库', link: '/golang/guide/source-reading/slices-maps-cmp' },
    ],
  },
  {
    text: 'IO 与网络',
    collapsed: true,
    items: [
      { text: 'io：接口体系', link: '/golang/guide/source-reading/io-interfaces' },
      { text: 'io 高级组合：TeeReader/Pipe', link: '/golang/guide/source-reading/io-advanced' },
      { text: 'bufio：缓冲 I/O 与 Scanner', link: '/golang/guide/source-reading/bufio' },
      { text: 'io/fs：文件系统抽象', link: '/golang/guide/source-reading/io-fs' },
      { text: 'os：文件与进程', link: '/golang/guide/source-reading/os' },
      { text: 'os/exec：命令执行', link: '/golang/guide/source-reading/os-exec' },
      { text: 'os/signal：信号处理', link: '/golang/guide/source-reading/os-signal' },
      { text: 'os/user：用户信息', link: '/golang/guide/source-reading/os-user' },
      { text: 'path/filepath：路径处理', link: '/golang/guide/source-reading/path-filepath' },
      { text: 'unicode/utf8：字符编码', link: '/golang/guide/source-reading/unicode-utf8' },
      { text: 'text/tabwriter：列对齐输出', link: '/golang/guide/source-reading/text-tabwriter' },
      { text: 'net：TCP/UDP 底层', link: '/golang/guide/source-reading/net' },
      { text: 'net/url：URL 解析', link: '/golang/guide/source-reading/net-url' },
      { text: 'net/http：HTTP 实现', link: '/golang/guide/source-reading/net-http' },
      { text: 'net/http 服务端高级模式', link: '/golang/guide/source-reading/net-http-server' },
      { text: 'net/http RESTful API 设计模式', link: '/golang/guide/source-reading/net-http-api' },
      { text: 'net/http Transport：连接池调优', link: '/golang/guide/source-reading/net-http-transport' },
      { text: 'net/http/httptrace：请求追踪', link: '/golang/guide/source-reading/net-http-trace' },
      { text: 'net/http/httptest：HTTP 测试', link: '/golang/guide/source-reading/net-http-test' },
      { text: 'net/http/httputil：反向代理', link: '/golang/guide/source-reading/net-httputil' },
      { text: 'net/http 限流与熔断', link: '/golang/guide/source-reading/net-http-ratelimit' },
      { text: 'HTTP/2：多路复用与 Server Push', link: '/golang/guide/source-reading/net-http2' },
      { text: 'net/http/cookiejar：Cookie 管理', link: '/golang/guide/source-reading/net-cookiejar' },
      { text: 'net/netip：现代 IP 地址', link: '/golang/guide/source-reading/net-netip' },
      { text: 'net/rpc：远程过程调用', link: '/golang/guide/source-reading/net-rpc' },
      { text: 'net/smtp：邮件发送', link: '/golang/guide/source-reading/net-smtp' },
      { text: 'mime/multipart：表单上传', link: '/golang/guide/source-reading/mime-multipart' },
      { text: '自定义 TCP 协议服务器', link: '/golang/guide/source-reading/net-tcp-server' },
      { text: 'WebSocket 服务器实现', link: '/golang/guide/source-reading/websocket' },
      { text: 'gRPC-Go：微服务通信', link: '/golang/guide/source-reading/grpc-go' },
      { text: 'Prometheus Go 客户端', link: '/golang/guide/source-reading/prometheus-go' },
      { text: 'OpenTelemetry Go：分布式追踪', link: '/golang/guide/source-reading/opentelemetry-go' },
      { text: 'golang.org/x/sync：并发工具包', link: '/golang/guide/source-reading/golang-x-sync' },
      { text: 'golang.org/x/oauth2：OAuth2 客户端', link: '/golang/guide/source-reading/golang-x-oauth2' },
      { text: 'go-redis：Redis 客户端', link: '/golang/guide/source-reading/go-redis' },
      { text: 'pgx：PostgreSQL 原生驱动', link: '/golang/guide/source-reading/pgx-driver' },
    ],
  },
  {
    text: '编码模板',
    collapsed: true,
    items: [
      { text: 'encoding/json：编解码', link: '/golang/guide/source-reading/encoding-json' },
      { text: 'encoding/xml：XML 编解码', link: '/golang/guide/source-reading/encoding-xml' },
      { text: 'encoding/csv：CSV 处理', link: '/golang/guide/source-reading/encoding-csv' },
      { text: 'encoding/gob：Go 原生序列化', link: '/golang/guide/source-reading/encoding-gob' },
      { text: 'encoding/base64：Base64 编码', link: '/golang/guide/source-reading/encoding-base64' },
      { text: 'encoding/hex：十六进制编解码', link: '/golang/guide/source-reading/encoding-hex' },
      { text: 'encoding/binary：字节序与协议', link: '/golang/guide/source-reading/encoding-binary' },
      { text: 'compress/gzip：流式压缩', link: '/golang/guide/source-reading/compress-gzip' },
      { text: 'archive/zip：ZIP 归档', link: '/golang/guide/source-reading/archive-zip' },
      { text: 'archive/tar：TAR 归档', link: '/golang/guide/source-reading/archive-tar' },
      { text: 'regexp：正则引擎', link: '/golang/guide/source-reading/regexp' },
      { text: 'container/heap：优先队列', link: '/golang/guide/source-reading/container-heap' },
      { text: 'container/list：双向链表', link: '/golang/guide/source-reading/container-list' },
      { text: 'text/template：模板引擎', link: '/golang/guide/source-reading/text-template' },
      { text: 'html/template：安全模板引擎', link: '/golang/guide/source-reading/html-template' },
      { text: 'database/sql：连接池', link: '/golang/guide/source-reading/database-sql' },
      { text: 'database/sql：高级事务与批量插入', link: '/golang/guide/source-reading/database-sql-advanced' },
    ],
  },
  {
    text: '安全密码',
    collapsed: true,
    items: [
      { text: 'crypto/tls：TLS 实现', link: '/golang/guide/source-reading/crypto-tls' },
      { text: 'crypto/x509：证书与 PKI', link: '/golang/guide/source-reading/crypto-x509' },
      { text: 'crypto/aes：对称加密', link: '/golang/guide/source-reading/crypto-aes' },
      { text: 'crypto/cipher：分组密码模式', link: '/golang/guide/source-reading/crypto-cipher' },
      { text: 'crypto/rand：密码学随机数', link: '/golang/guide/source-reading/crypto-rand' },
      { text: 'crypto/hmac：哈希与消息认证', link: '/golang/guide/source-reading/crypto-hmac' },
      { text: 'crypto/sha256：hash 接口体系', link: '/golang/guide/source-reading/crypto-sha' },
      { text: 'crypto/rsa：RSA 非对称加密', link: '/golang/guide/source-reading/crypto-rsa' },
      { text: 'crypto/ecdsa：椭圆曲线签名', link: '/golang/guide/source-reading/crypto-ecdsa' },
      { text: 'crypto/ed25519：EdDSA 签名', link: '/golang/guide/source-reading/crypto-ed25519' },
      { text: '密码散列：bcrypt/Argon2id/scrypt', link: '/golang/guide/source-reading/crypto-password' },
      { text: 'hash/crc32：校验和', link: '/golang/guide/source-reading/hash-crc32' },
    ],
  },
  {
    text: '工程工具',
    collapsed: true,
    items: [
      { text: 'log/slog：结构化日志', link: '/golang/guide/source-reading/log-slog' },
      { text: 'zap：高性能日志库', link: '/golang/guide/source-reading/zap' },
      { text: 'log：标准日志库', link: '/golang/guide/source-reading/log-pkg' },
      { text: 'testing：测试框架与高级模式', link: '/golang/guide/source-reading/testing' },
      { text: 'testing/fstest：虚拟文件系统测试', link: '/golang/guide/source-reading/testing-fstest' },
      { text: 'testing/fuzzing：模糊测试', link: '/golang/guide/source-reading/go-fuzzing' },
      { text: 'go:generate 代码生成工具链', link: '/golang/guide/source-reading/go-generate' },
      { text: 'go/format：代码格式化', link: '/golang/guide/source-reading/go-format' },
      { text: 'go/ast + go/parser：AST 解析', link: '/golang/guide/source-reading/go-ast' },
      { text: 'go/types：类型检查器', link: '/golang/guide/source-reading/go-types' },
      { text: 'go/analysis：自定义 Linter', link: '/golang/guide/source-reading/go-analysis' },
      { text: 'embed：静态资源嵌入', link: '/golang/guide/source-reading/embed' },
      { text: 'flag：命令行解析', link: '/golang/guide/source-reading/flag' },
      { text: 'expvar：可导出变量', link: '/golang/guide/source-reading/expvar' },
      { text: 'debug/buildinfo：构建信息', link: '/golang/guide/source-reading/debug-buildinfo' },
      { text: 'cgo：C/Go 互操作', link: '/golang/guide/source-reading/cgo-basics' },
      { text: 'cobra+viper：CLI 工具框架', link: '/golang/guide/source-reading/cobra-viper' },
      { text: 'wire：编译期依赖注入', link: '/golang/guide/source-reading/wire' },
      { text: 'golang.org/x/text：Unicode 文本', link: '/golang/guide/source-reading/golang-x-text' },
    ],
  },
]

export const golangSection: SectionConfig = {
  key: 'golang',
  base: '/golang/',
  navText: 'Golang',
  overviewDescription:
    '适合 Go 后端和高级开发，重点覆盖语言机制、并发、性能、工程实践与源码精读主线。',
  landing: {
    eyebrow: 'Golang',
    title: 'Golang 方向',
    intro:
      '从语言机制、并发与性能，到服务端工程实践、能力自检和源码精读，把 Go 进阶学习整理成一套统一入口。',
    primary: { title: '源码精读主线', href: '/golang/guide/source-reading/learning-path', description: '先走源码阅读主线。' },
    secondary: { title: '能力自检', href: '/golang/interview-prep', description: '再做题库和专题回查。' },
    scope: ['Go 语言底层', '并发模型', '性能优化与排障', '服务端工程实践', '能力自检准备', '设计模式与安全', '容器化与云原生', '代码生成与元编程', '标准库源码精读', 'runtime 源码分析'],
    docs: [
      { title: 'Go 文档导航', href: '/golang/', description: '先看目录，再决定走学习主线、源码主线还是自检入口。' },
      { title: 'Go 学习路径', href: '/golang/learning-path', description: '串联各阶段专题、练习与补充资料入口。' },
      { title: 'Go 常用库专题', href: '/golang/excellent-open-source', description: '按并发、Web、数据访问、CLI、日志和测试整理常用库。' },
      { title: 'Go 源码阅读主线', href: '/golang/guide/source-reading/learning-path', description: '统一维护源码阅读路线、方法、runtime 导读与资料。' },
      { title: 'Go 源码精读总览', href: '/golang/guide/source-reading/', description: '按 runtime、网络、编码与工程化浏览源码文章。' },
      { title: 'Go 能力自检导航', href: '/golang/interview-prep', description: '整理题库、代码片段与专题回查入口。' },
      { title: 'database/sql 与连接池', href: '/golang/guide/06-database-sql-and-connection', description: 'Go 标准库数据库访问与连接池的实战入口。' },
      { title: '30+ 高频自检题', href: '/golang/go-top-30-interview-questions', description: '用问题驱动回顾知识盲区和底层理解。' },
      { title: '高频题代码片段', href: '/golang/go-interview-code-snippets', description: '配套示例代码，方便把抽象概念落到实现。' },
      { title: 'Pprof 排障指南', href: '/golang/pprof-troubleshooting-guide', description: '围绕性能定位与排障建立实操路径。' },
      { title: 'Context 使用边界', href: '/golang/context-usage-boundaries', description: '厘清 Go 服务里使用 Context 的边界和误区。' },
    ],
    order: [
      'Go 文档导航',
      'Go 学习路径',
      'Go 常用库专题',
      'Go 源码阅读主线',
      'Go 源码精读总览',
      'Go 能力自检导航',
      'database/sql 与连接池',
      '30+ 高频自检题',
      '高频题代码片段',
      'Pprof 排障指南',
      'Context 使用边界',
    ],
  },
  sidebar: [
    {
      text: '核心入口',
      items: [
        { text: '方向概览', link: '/golang/' },
        { text: '学习路径', link: '/golang/learning-path' },
        { text: '源码主线', link: '/golang/guide/source-reading/learning-path' },
        { text: '精读总览', link: '/golang/guide/source-reading/' },
        { text: '能力自检', link: '/golang/interview-prep' },
        { text: 'SQL 连接', link: '/golang/guide/06-database-sql-and-connection' },
        { text: '性能排障', link: '/golang/pprof-troubleshooting-guide' },
        { text: '上下文边界', link: '/golang/context-usage-boundaries' },
        { text: '版本特性', link: '/golang/go-version-features' },
        { text: '高频自检', link: '/golang/go-top-30-interview-questions' },
        { text: '自检代码', link: '/golang/go-interview-code-snippets' },
      ],
    },
    {
      text: '大纲详解',
      collapsed: true,
      items: [
        {
          text: '一、语言基础',
          link: '/golang/guide/01-language-fundamentals',
          items: [
            { text: '变量与类型', link: '/golang/guide/01-variables-types-and-semantics' },
            { text: 'defer 与闭包', link: '/golang/guide/01-defer-panic-and-closures' },
            { text: '接口反射泛型', link: '/golang/guide/01-interface-reflect-generics' },
            { text: '错误处理', link: '/golang/guide/01-error-handling-design' },
            { text: 'Slice 陷阱', link: '/golang/guide/01-slice-append-pitfalls' },
            { text: '字符串转换', link: '/golang/guide/01-string-byte-best-practices' },
          ],
        },
        {
          text: '二、底层原理',
          link: '/golang/guide/02-underlying-principles',
          items: [
            { text: '容器底层实现', link: '/golang/guide/02-slice-map-channel-internals' },
            { text: '运行时内存主线', link: '/golang/guide/02-runtime-memory-lifecycle' },
            { text: '逃逸分析专题', link: '/golang/guide/02-escape-analysis' },
            { text: '并发切片', link: '/golang/guide/02-concurrent-slice-patterns' },
          ],
        },
        {
          text: '三、并发编程',
          link: '/golang/guide/03-concurrency',
          items: [
            { text: '协程与调度', link: '/golang/guide/03-goroutine-and-scheduler' },
            { text: 'Channel 模式', link: '/golang/guide/03-channel-select-context' },
            { text: '同步原语', link: '/golang/guide/03-sync-primitives' },
            { text: '泄漏与竞态', link: '/golang/guide/03-goroutine-leak-and-data-race' },
            { text: '高级模式', link: '/golang/guide/03-advanced-concurrency-patterns' },
          ],
        },
        {
          text: '四、网络编程',
          link: '/golang/guide/04-network-stdlib',
          items: [
            { text: 'HTTP 与 TCP', link: '/golang/guide/04-http-server-client-tcp-udp' },
            { text: '超时重试限流', link: '/golang/guide/04-connection-timeout-retry-rate-limit' },
            { text: '中间件与 IO', link: '/golang/guide/04-middleware-json-io' },
          ],
        },
        {
          text: '五、工程实践',
          link: '/golang/guide/05-engineering-practices',
          items: [
            { text: '结构与配置', link: '/golang/guide/05-project-layout-deps-logging-config' },
            { text: '规范与错误码', link: '/golang/guide/05-error-middleware-code-style' },
            { text: '测试与 CI', link: '/golang/guide/05-testing-benchmark-cicd' },
          ],
        },
        {
          text: '六、数据与缓存',
          link: '/golang/guide/06-database-cache',
          items: [
            { text: 'Redis 缓存', link: '/redis/redis-and-cache-patterns' },
            { text: '一致性分表', link: '/golang/guide/06-cache-consistency-and-sharding' },
            { text: 'SQL 连接池', link: '/golang/guide/06-database-sql-and-connection' },
          ],
        },
        {
          text: '七、性能排障',
          link: '/golang/guide/07-performance-troubleshooting',
          items: [
            { text: '性能采集', link: '/golang/guide/07-pprof-trace-and-benchmark' },
            { text: 'GC 与内存', link: '/golang/guide/07-gc-tuning-and-memory-optimization' },
            { text: '锁与慢请求', link: '/golang/guide/07-lock-contention-and-slow-requests' },
            { text: '泄漏与定位', link: '/golang/guide/07-goroutine-leak-and-production-debugging' },
          ],
        },
        {
          text: '八、微服务架构',
          link: '/golang/guide/08-microservices-distributed',
          items: [
            { text: 'RPC 与发现', link: '/golang/guide/08-rpc-discovery-config' },
            { text: '容错与追踪', link: '/golang/guide/08-observability-resilience' },
            { text: '高并发系统设计', link: '/golang/guide/08-go-high-concurrency-system-design' },
            { text: 'MQ 与高可用', link: '/golang/guide/08-mq-transaction-governance-ha' },
          ],
        },
        { text: '九、源码阅读', link: '/golang/guide/source-reading/learning-path' },
        {
          text: '十、进阶专题',
          link: '/golang/guide/10-advanced-topics',
          items: [
            { text: '设计模式', link: '/golang/guide/10-design-patterns-idioms' },
            { text: '安全编程', link: '/golang/guide/10-security-practices' },
            { text: '容器云原生', link: '/golang/guide/10-containerization-cloud-native' },
            { text: '代码生成', link: '/golang/guide/10-codegen-metaprogramming' },
          ],
        },
      ],
    },
    ...golangSourceReadingSidebar,
    { text: '第三方专题', link: '/golang/excellent-open-source' },
  ] satisfies SidebarEntry[],
}
