import type { SectionConfig } from './types'

export const k8sSection: SectionConfig = {
    key: 'k8s',
    base: '/k8s/',
    navText: 'K8s',
    overviewDescription:
      '系统整理 Kubernetes 必备知识，涵盖核心对象、调度与资源管理、网络与存储、发布治理、故障排查与控制面原理。',
    landing: {
      eyebrow: 'K8s',
      title: 'K8s 专题',
      intro:
        '把 Kubernetes 从“会写 YAML”提升到“能解释机制、能定位问题、能回答高频追问”的层面，先建立统一对象模型，再按由浅入深整理必备问题。',
      primary: { title: '专题总览', href: '/k8s/', description: '从总览页开始，先建立统一框架。' },
      secondary: { title: '入口控制器实现链路', href: '/k8s/ingress-and-gateway-controller-chain', description: '补 IngressClass、GatewayClass、controller 接管和地址分配。' },
      scope: [
        '控制面与节点组件',
        'Pod / Deployment / StatefulSet',
        'Service / Ingress / Mesh 与服务发现',
        '调度、资源限制与弹性伸缩',
        '探针、发布与优雅终止',
        '网络、存储与持久化',
        'RBAC、ServiceAccount 与隔离',
        '控制循环、etcd、CRD / Operator',
      ],
      docs: [
        { title: '核心概念与对象模型', href: '/k8s/core-concepts', description: '从定位、控制面、核心对象到调度与存储，建立统一认知。' },
        { title: '必备问题清单', href: '/k8s/essential-questions', description: '按由浅入深整理高频问题，覆盖发布、排障、安全与深入机制。' },
        { title: 'Pod 生命周期与探针实战', href: '/k8s/pod-lifecycle-and-probes', description: '系统讲清 Pod phase、Running/Ready、CrashLoopBackOff 与 startup、readiness、liveness 的边界。' },
        { title: 'Pod 内多容器协作实战', href: '/k8s/pod-multi-container-collaboration', description: '系统讲清为什么 Pod 是最小调度单元，以及主容器、Init Container、Sidecar、临时容器、共享网络与共享卷的边界。' },
        { title: 'Job 与 CronJob 批处理链路实战', href: '/k8s/job-and-cronjob-batch-workloads', description: '系统讲清 Job、CronJob、重试、补跑、并发策略、历史清理与幂等性边界，以及为什么一次性任务不该用 Deployment。' },
        { title: 'ConfigMap、Secret 与配置注入边界实战', href: '/k8s/configmap-secret-and-config-injection', description: '系统讲清 ConfigMap、Secret、env、envFrom、volume、projected volume、subPath、热更新传播与安全边界。' },
        { title: '调度与驱逐链路实战', href: '/k8s/scheduling-and-eviction', description: '把 Pending、OOMKilled、Evicted 以及 requests、QoS、优先级、污点容忍放回同一条链路里。' },
        { title: 'PriorityClass、Preemption 与调度让路边界实战', href: '/k8s/priorityclass-preemption-and-scheduling-boundaries', description: '系统讲清 PriorityClass、调度队列顺序、scheduler preemption、nominatedNodeName、非抢占优先级、PDB best effort、QoS 与节点压力驱逐的边界。' },
        { title: '资源规格与运行时压力实战', href: '/k8s/resource-specs-and-runtime-pressure', description: '系统讲清 requests、limits、QoS、CPU throttling、OOMKilled 和节点压力之间的关系，以及为什么“能调度”不等于“跑得稳”。' },
        { title: '弹性扩缩容与容量协同实战', href: '/k8s/autoscaling-and-capacity-control-chain', description: '系统讲清 HPA、VPA、Cluster Autoscaler 如何围绕 requests、Pending、节点容量和 Ready 协同工作。' },
        { title: '副本打散与拓扑高可用实战', href: '/k8s/replica-spread-and-topology-ha', description: '系统讲清 podAntiAffinity、topologySpreadConstraints、PodDisruptionBudget、drain 如何围绕节点、可用区和维护窗口共同保障高可用。' },
        { title: '零停机发布链路实战', href: '/k8s/zero-downtime-rollout', description: '把 readiness、preStop、SIGTERM、grace period、PDB 串成一条真正可用的发布链路。' },
        { title: 'PDB、Eviction API 与 drain 边界实战', href: '/k8s/pdb-eviction-api-and-drain-boundaries', description: '系统讲清 voluntary/involuntary disruption、PodDisruptionBudget、Eviction API、kubectl drain、429 Too Many Requests 与 unhealthyPodEvictionPolicy。' },
        { title: 'StatefulSet 与 Headless Service 实战', href: '/k8s/statefulset-headless-service', description: '讲清稳定实例身份、成员级 DNS 和独立 PVC，拆掉“固定 Pod IP”误解。' },
        { title: 'DaemonSet 节点驻留与更新边界实战', href: '/k8s/daemonset-node-resident-and-update-boundaries', description: '系统讲清 DaemonSet 的节点驻留语义、自动容忍、滚动更新、cordon/drain 边界，以及它为什么不是固定副本数控制器。' },
        { title: '存储与数据链路实战', href: '/k8s/storage-and-data-lifecycle', description: '拆清 PV、PVC、StorageClass、CSI、扩容、回收策略和常见挂载故障。' },
        { title: '认证、授权与隔离链路实战', href: '/k8s/authn-authz-and-isolation', description: '拆清 ServiceAccount、RBAC、Admission、Secret、NetworkPolicy 的边界与协作关系。' },
        { title: 'ServiceAccount Token 与 Pod 身份边界实战', href: '/k8s/serviceaccount-token-and-pod-identity', description: '系统讲清 ServiceAccount、自动挂载 token、projected serviceAccountToken、TokenRequest、audience、自动轮转与 Pod 身份边界。' },
        { title: 'RBAC 实战与最小权限设计', href: '/k8s/rbac-and-least-privilege', description: '系统讲清 Role、ClusterRole、RoleBinding、ClusterRoleBinding、resourceNames、subresource、serviceaccounts/token、bind、escalate、impersonate 与最小权限设计边界。' },
        { title: 'Pod Security 与 SecurityContext 运行权限边界实战', href: '/k8s/pod-security-and-security-context', description: '系统讲清 SecurityContext、Pod Security Admission、Pod Security Standards、runAsNonRoot、allowPrivilegeEscalation、privileged、capabilities、seccomp、host namespaces 与 hostPath 的安全边界。' },
        { title: 'Admission、策略治理与 Policy Engine 边界实战', href: '/k8s/admission-policy-and-governance', description: '系统讲清内建 Admission Controllers、Mutating/Validating Webhook、ValidatingAdmissionPolicy、Pod Security Admission、OPA Gatekeeper、Kyverno 的职责边界与选型。' },
        { title: '镜像安全、镜像准入与供应链边界实战', href: '/k8s/image-security-and-supply-chain-governance', description: '系统讲清镜像 tag 与 digest、imagePullPolicy、imagePullSecrets、AlwaysPullImages、镜像来源限制、签名校验、attestation、SBOM 与供应链治理边界。' },
        { title: 'Secret 安全、etcd 加密与外部 Secret 管理边界实战', href: '/k8s/secret-security-and-external-secret-management', description: '系统讲清 Secret 的 base64 与真正加密、etcd at-rest encryption、KMS、RBAC 边界、节点分发、ESO、Secrets Store CSI Driver 与轮转收敛。' },
        { title: 'API 审计、Audit Policy 与审计日志边界实战', href: '/k8s/api-auditing-and-audit-policy-boundary', description: '系统讲清 API Audit 的执行位置、Audit Policy、规则顺序、级别、阶段、log 与 webhook backend、admission webhook audit annotations 与审计日志边界。' },
        { title: 'Namespace 资源治理与配额边界实战', href: '/k8s/namespace-resource-governance-and-quota', description: '系统讲清 Namespace、LimitRange、ResourceQuota 如何围绕默认值、单对象边界、命名空间总预算和对象数量配额共同做资源治理。' },
        { title: '控制器与 Reconcile 链路实战', href: '/k8s/controllers-and-reconcile', description: '讲清 controller、reconcile loop、Deployment、HPA、CRD、Operator 如何协同工作。' },
        { title: '删除、Finalizers 与 Terminating 边界实战', href: '/k8s/deletion-finalizers-and-terminating-boundaries', description: '系统讲清 delete、deletionTimestamp、finalizers、ownerReferences、垃圾回收、Foreground/Background/Orphan、Pod Terminating 与控制面对象删除边界。' },
        { title: '控制面主线实战', href: '/k8s/control-plane-mainline', description: '系统讲清 kube-apiserver、etcd、kube-scheduler、kube-controller-manager 如何把声明变成真正运行的 Pod。' },
        { title: '节点心跳、Lease 与失联驱逐边界实战', href: '/k8s/node-heartbeat-lease-and-failure-eviction', description: '系统讲清节点心跳、Lease、Ready False/Unknown、自动 taint、NoExecute、tolerationSeconds、失联驱逐与网络分区边界。' },
        { title: '节点执行链路实战', href: '/k8s/node-execution-chain', description: '系统讲清 kubelet、CRI、container runtime、Pod sandbox、CNI、CSI 如何把一个已调度的 Pod 真正跑起来。' },
        { title: '服务暴露与流量入口链路实战', href: '/k8s/service-exposure-and-traffic-entry', description: '拆清 ClusterIP、NodePort、LoadBalancer、Ingress、Gateway API、TLS 终止与真实源地址。' },
        { title: 'Ingress Controller 与 Gateway Controller 实现链路', href: '/k8s/ingress-and-gateway-controller-chain', description: '系统讲清 Ingress、IngressClass、GatewayClass、Gateway、HTTPRoute 背后的控制器接管、路由下发、地址分配与常见排障方法。' },
        { title: 'CoreDNS 与服务发现实战', href: '/k8s/coredns-and-service-discovery', description: '系统讲清服务名解析、CoreDNS、普通 Service DNS、Headless Service DNS、dnsPolicy、ndots 与常见服务发现排障方法。' },
        { title: 'EndpointSlice、Ready 与服务后端收敛边界实战', href: '/k8s/service-backend-readiness-and-endpointslice', description: '系统讲清 EndpointSlice、Service selector、ready/serving/terminating、publishNotReadyAddresses、滚动发布摘流量，以及为什么 Pod Running 了也不一定已经进后端池。' },
        { title: 'kube-proxy 与 Service 数据面实战', href: '/k8s/kube-proxy-and-service-dataplane', description: '系统讲清 Service VIP、EndpointSlice、kube-proxy、iptables、IPVS、NodePort 与 externalTrafficPolicy 的数据面实现和排障方法。' },
        { title: 'NetworkPolicy 与东西向访问控制实战', href: '/k8s/networkpolicy-and-east-west-access-control', description: '系统讲清 NetworkPolicy 的默认拒绝、Ingress/Egress、生效前提、selector 语义、DNS 放行、ipBlock 边界与常见排障方法。' },
        { title: 'Service Mesh 与东西向流量实战', href: '/k8s/service-mesh-and-east-west-traffic', description: '拆清南北向与东西向边界，以及 Service Mesh、Sidecar、mTLS、重试、熔断、灰度和 Egress Gateway。' },
        { title: 'K8s 网络排障手册', href: '/k8s/network-troubleshooting', description: '按 Service、EndpointSlice、kube-proxy、CNI、Pod 五层链路系统排查网络问题。' },
        { title: '固定入口、固定出口与白名单实战', href: '/k8s/fixed-ip-and-whitelist', description: '拆清 Pod 动态 IP、固定入口、固定出口、第三方白名单与真实客户端 IP 保留。' },
        { title: 'externalTrafficPolicy Local 实战与边界', href: '/k8s/external-traffic-policy-local', description: '拆清 Cluster 和 Local 的差异、源地址保留机制、副作用与适用边界。' },
        { title: '容器化与云原生实践', href: '/golang/guide/10-containerization-cloud-native', description: '从 Go 服务视角看探针、优雅关闭、配置和 K8s 部署。' },
        { title: 'etcd 专题', href: '/etcd/', description: '理解 etcd 在 Kubernetes 控制面中的角色和一致性边界。' },
        { title: 'kubectl 排障速查', href: '/k8s/kubectl-troubleshooting-cheatsheet', description: '系统整理排障常用命令、Pod 状态判断流程与临时调试容器使用边界。' },
        { title: 'CRD、Operator 与扩展机制实战', href: '/k8s/crd-operator-and-extension', description: '系统讲清 CRD 定义与校验、Operator 模式、controller-runtime 核心概念。' },
        { title: 'Helm 与包管理实战', href: '/k8s/helm-and-package-management', description: '系统讲清 Chart 结构、values 管理、install/upgrade/rollback 与仓库依赖。' },
        { title: '可观测性与监控实战', href: '/k8s/observability-and-monitoring', description: '系统讲清指标、日志、链路追踪三大支柱的 K8s 落地方式与边界。' },
        { title: 'GitOps 与持续交付实战', href: '/k8s/gitops-and-delivery', description: '系统讲清 GitOps 核心理念、ArgoCD/Flux 工作机制与 CI/CD 对接模式。' },
        { title: '实战部署指南', href: '/k8s/production-deployment-guide', description: '按小集群/大集群两条线给出搭建、网络、存储、发布、安全、观测与容灾的完整方案。' },
        { title: '内网离线集群搭建操作指南', href: '/k8s/offline-cluster-setup-guide', description: '面向无公网环境，从资源准备、Harbor 搭建到 kubeadm 高可用初始化的完整操作手册。' },
        { title: '管理面板与可视化工具实战', href: '/k8s/dashboard-and-management-ui', description: '对比 k9s、Dashboard、Headlamp、Rancher、KubeSphere 等主流方案的选型与安全实践。' },
        { title: '集群搭建实操：kubeadm + KubeSphere', href: '/k8s/cluster-setup-kubeadm-kubesphere', description: '完整操作手册：kubeadm + containerd + Calico + KubeSphere + Helm + Nginx Ingress 从零到登录。' },
      ],
      order: [
        '核心概念与对象模型',
        '必备问题清单',
        'Pod 生命周期与探针实战',
        'Pod 内多容器协作实战',
        'Job 与 CronJob 批处理链路实战',
        'ConfigMap、Secret 与配置注入边界实战',
        '调度与驱逐链路实战',
        'PriorityClass、Preemption 与调度让路边界实战',
        '资源规格与运行时压力实战',
        '弹性扩缩容与容量协同实战',
        '副本打散与拓扑高可用实战',
        '零停机发布链路实战',
        'PDB、Eviction API 与 drain 边界实战',
        'StatefulSet 与 Headless Service 实战',
        'DaemonSet 节点驻留与更新边界实战',
        '存储与数据链路实战',
        '认证、授权与隔离链路实战',
        'ServiceAccount Token 与 Pod 身份边界实战',
        'RBAC 实战与最小权限设计',
        'Pod Security 与 SecurityContext 运行权限边界实战',
        'Admission、策略治理与 Policy Engine 边界实战',
        '镜像安全、镜像准入与供应链边界实战',
        'Secret 安全、etcd 加密与外部 Secret 管理边界实战',
        'API 审计、Audit Policy 与审计日志边界实战',
        'Namespace 资源治理与配额边界实战',
        '控制器与 Reconcile 链路实战',
        '删除、Finalizers 与 Terminating 边界实战',
        '控制面主线实战',
        '节点心跳、Lease 与失联驱逐边界实战',
        '节点执行链路实战',
        '服务暴露与流量入口链路实战',
        'Ingress Controller 与 Gateway Controller 实现链路',
        'CoreDNS 与服务发现实战',
        'EndpointSlice、Ready 与服务后端收敛边界实战',
        'kube-proxy 与 Service 数据面实战',
        'NetworkPolicy 与东西向访问控制实战',
        'Service Mesh 与东西向流量实战',
        'K8s 网络排障手册',
        '固定入口、固定出口与白名单实战',
        'externalTrafficPolicy Local 实战与边界',
        '容器化与云原生实践',
        'etcd 专题',
        'kubectl 排障速查',
        'CRD、Operator 与扩展机制实战',
        'Helm 与包管理实战',
        '可观测性与监控实战',
        'GitOps 与持续交付实战',
        '实战部署指南',
        '内网离线集群搭建操作指南',
        '管理面板与可视化工具实战',
        '集群搭建实操：kubeadm + KubeSphere',
      ],
    },
    sidebar: [
      {
        text: '全局认知',
        items: [
          { text: '专题总览', link: '/k8s/' },
          { text: '核心概念', link: '/k8s/core-concepts' },
          { text: '高频问题', link: '/k8s/essential-questions' },
          { text: '排障速查', link: '/k8s/kubectl-troubleshooting-cheatsheet' },
        ],
      },
      {
        text: 'Pod 负载',
        collapsed: true,
        items: [
          { text: 'Pod 生命周期', link: '/k8s/pod-lifecycle-and-probes' },
          { text: '多容器协作', link: '/k8s/pod-multi-container-collaboration' },
          { text: 'Job 批处理', link: '/k8s/job-and-cronjob-batch-workloads' },
          { text: '配置注入', link: '/k8s/configmap-secret-and-config-injection' },
          { text: 'StatefulSet', link: '/k8s/statefulset-headless-service' },
          { text: 'DaemonSet', link: '/k8s/daemonset-node-resident-and-update-boundaries' },
        ],
      },
      {
        text: '调度资源',
        collapsed: true,
        items: [
          { text: '调度与驱逐', link: '/k8s/scheduling-and-eviction' },
          { text: '优先级抢占', link: '/k8s/priorityclass-preemption-and-scheduling-boundaries' },
          { text: '资源与压力', link: '/k8s/resource-specs-and-runtime-pressure' },
          { text: '弹性扩缩容', link: '/k8s/autoscaling-and-capacity-control-chain' },
        ],
      },
      {
        text: '发布与高可用',
        collapsed: true,
        items: [
          { text: '副本打散', link: '/k8s/replica-spread-and-topology-ha' },
          { text: '零停机发布', link: '/k8s/zero-downtime-rollout' },
          { text: 'PDB 与 drain', link: '/k8s/pdb-eviction-api-and-drain-boundaries' },
          { text: '删除与终止', link: '/k8s/deletion-finalizers-and-terminating-boundaries' },
        ],
      },
      {
        text: '存储',
        collapsed: true,
        items: [
          { text: '存储与数据', link: '/k8s/storage-and-data-lifecycle' },
        ],
      },
      {
        text: '网络发现',
        collapsed: true,
        items: [
          { text: '服务暴露', link: '/k8s/service-exposure-and-traffic-entry' },
          { text: 'Ingress', link: '/k8s/ingress-and-gateway-controller-chain' },
          { text: 'CoreDNS', link: '/k8s/coredns-and-service-discovery' },
          { text: '后端收敛', link: '/k8s/service-backend-readiness-and-endpointslice' },
          { text: 'kube-proxy', link: '/k8s/kube-proxy-and-service-dataplane' },
          { text: 'NetworkPolicy', link: '/k8s/networkpolicy-and-east-west-access-control' },
          { text: 'Service Mesh', link: '/k8s/service-mesh-and-east-west-traffic' },
          { text: '流量策略', link: '/k8s/external-traffic-policy-local' },
          { text: '固定 IP', link: '/k8s/fixed-ip-and-whitelist' },
          { text: '网络排障', link: '/k8s/network-troubleshooting' },
        ],
      },
      {
        text: '安全权限',
        collapsed: true,
        items: [
          { text: '认证与授权', link: '/k8s/authn-authz-and-isolation' },
          { text: 'SA 身份', link: '/k8s/serviceaccount-token-and-pod-identity' },
          { text: 'RBAC 权限', link: '/k8s/rbac-and-least-privilege' },
          { text: 'Pod 安全', link: '/k8s/pod-security-and-security-context' },
          { text: '准入治理', link: '/k8s/admission-policy-and-governance' },
          { text: '镜像安全', link: '/k8s/image-security-and-supply-chain-governance' },
          { text: 'Secret', link: '/k8s/secret-security-and-external-secret-management' },
          { text: 'API 审计', link: '/k8s/api-auditing-and-audit-policy-boundary' },
          { text: '命名配额', link: '/k8s/namespace-resource-governance-and-quota' },
        ],
      },
      {
        text: '控制面',
        collapsed: true,
        items: [
          { text: '控制面主线', link: '/k8s/control-plane-mainline' },
          { text: '控制器循环', link: '/k8s/controllers-and-reconcile' },
          { text: '节点心跳', link: '/k8s/node-heartbeat-lease-and-failure-eviction' },
          { text: '节点执行', link: '/k8s/node-execution-chain' },
        ],
      },
      {
        text: '进阶生态',
        collapsed: true,
        items: [
          { text: 'CRD 扩展', link: '/k8s/crd-operator-and-extension' },
          { text: 'Helm', link: '/k8s/helm-and-package-management' },
          { text: '可观测性', link: '/k8s/observability-and-monitoring' },
          { text: 'GitOps', link: '/k8s/gitops-and-delivery' },
          { text: '实战部署', link: '/k8s/production-deployment-guide' },
          { text: '离线搭建', link: '/k8s/offline-cluster-setup-guide' },
          { text: '管理面板', link: '/k8s/dashboard-and-management-ui' },
          { text: '集群实操', link: '/k8s/cluster-setup-kubeadm-kubesphere' },
        ],
      },
    ],
  }
