import type { SectionConfig } from './types'

export const mysqlSection: SectionConfig = {
    key: 'mysql',
    base: '/mysql/',
    navText: 'MySQL',
    overviewDescription:
      '系统整理 MySQL 核心知识，聚焦事务、查询优化、GORM，以及高并发场景下的索引设计、大事务拆分、死锁治理、热点更新与分库迁移。',
    landing: {
      eyebrow: 'MySQL',
      title: 'MySQL 专题',
      intro:
        '把散落在 Go 学习大纲和支付系统案例中的 MySQL 相关内容统一收敛，涵盖日常开发基础和高并发场景实战。',
      primary: { title: '专题总览', href: '/mysql/', description: '从总览页开始按主题查阅。' },
      secondary: { title: '索引设计', href: '/mysql/index-design', description: '从 B+ 树和最左前缀开始。' },
      scope: [
        'Go 与 MySQL 集成',
        '事务处理',
        '查询优化',
        'GORM 实战',
        '索引设计',
        '双 ID 设计（自增+雪花）',
        '长事务与死锁治理',
        '热点更新与分库迁移',
        'MySQL 实战 45 讲（原理精读）',
      ],
      docs: [
        { title: 'database/sql 与连接池', href: '/golang/guide/06-database-sql-and-connection', description: 'Go 标准库操作数据库与连接池配置。' },
        { title: '事务处理', href: '/mysql/transaction-and-optimization', description: '隔离级别、锁模式、大事务拆分与长事务治理。' },
        { title: '查询优化', href: '/mysql/sql-optimization', description: 'EXPLAIN、索引使用、批量操作与游标分页。' },
        { title: 'GORM 实战', href: '/mysql/orm-gorm', description: 'GORM 基础用法、N+1 与原生 SQL 取舍。' },
        { title: '索引设计', href: '/mysql/index-design', description: '索引结构、回表原理与最左前缀场景。' },
        { title: '双 ID 设计', href: '/mysql/dual-id-design', description: '内部自增主键配合雪花 ID，对外兼顾性能与安全。' },
        { title: '死锁重试', href: '/mysql/deadlock-and-retry', description: '死锁排查、根因治理与幂等回滚重试。' },
        { title: '热点更新', href: '/mysql/hot-account-update', description: '从乐观锁到子账户拆分的分层治理方案。' },
        { title: '分库迁移', href: '/mysql/sharding-and-migration', description: '拆分策略、数据迁移流程与核心原则。' },
        { title: '高频追问', href: '/mysql/high-frequency-questions', description: 'SELECT *、深分页、锁持有时间等落地细节。' },
      ],
      order: [
        'database/sql 与连接池',
        '事务处理',
        '查询优化',
        'GORM 实战',
        '索引设计',
        '双 ID 设计',
        '死锁重试',
        '热点更新',
        '分库迁移',
        '高频追问',
      ],
    },
    sidebar: [
      {
        text: '基础专题',
        items: [
          { text: '专题总览', link: '/mysql/' },
          { text: '事务处理', link: '/mysql/transaction-and-optimization' },
          { text: '查询优化', link: '/mysql/sql-optimization' },
          { text: 'GORM实战', link: '/mysql/orm-gorm' },
        ],
      },
      {
        text: '并发专题',
        items: [
          { text: '索引设计', link: '/mysql/index-design' },
          { text: '双ID设计', link: '/mysql/dual-id-design' },
          { text: '死锁重试', link: '/mysql/deadlock-and-retry' },
          { text: '热点更新', link: '/mysql/hot-account-update' },
          { text: '分库迁移', link: '/mysql/sharding-and-migration' },
          { text: '高频追问', link: '/mysql/high-frequency-questions' },
        ],
      },
      {
        text: '基础八讲',
        collapsed: true,
        items: [
          { text: '00 开篇导读', link: '/mysql/00-preface' },
          { text: '01 查询执行', link: '/mysql/01-sql-query-execution' },
          { text: '02 更新链路', link: '/mysql/02-sql-update-log-system' },
          { text: '03 事务隔离', link: '/mysql/03-transaction-isolation' },
          { text: '04 索引上篇', link: '/mysql/04-index-part1' },
          { text: '05 索引下篇', link: '/mysql/05-index-part2' },
          { text: '06 全局表锁', link: '/mysql/06-global-table-lock' },
          { text: '07 行锁机制', link: '/mysql/07-row-lock' },
          { text: '08 隔离细节', link: '/mysql/08-transaction-isolation-detail' },
        ],
      },
      {
        text: '索引七讲',
        collapsed: true,
        items: [
          { text: '09 索引选型', link: '/mysql/09-normal-vs-unique-index' },
          { text: '10 误选索引', link: '/mysql/10-wrong-index-selection' },
          { text: '11 字符索引', link: '/mysql/11-string-index' },
          { text: '12 抖动分析', link: '/mysql/12-mysql-flush' },
          { text: '13 空间回收', link: '/mysql/13-table-space-reclaim' },
          { text: '14 计数优化', link: '/mysql/14-count-slow' },
          { text: '15 日志索引', link: '/mysql/15-qa-log-and-index' },
        ],
      },
      {
        text: '查询六讲',
        collapsed: true,
        items: [
          { text: '16 排序原理', link: '/mysql/16-order-by' },
          { text: '17 随机查询', link: '/mysql/17-random-message' },
          { text: '18 逻辑性能', link: '/mysql/18-sql-same-logic-diff-perf' },
          { text: '19 单行慢查', link: '/mysql/19-single-row-query-slow' },
          { text: '20 幻读问题', link: '/mysql/20-phantom-read' },
          { text: '21 更新加锁', link: '/mysql/21-single-row-update-many-locks' },
        ],
      },
      {
        text: '高可用篇',
        collapsed: true,
        items: [
          { text: '22 应急提速', link: '/mysql/22-emergency-perf-boost' },
          { text: '23 数据持久', link: '/mysql/23-data-durability' },
          { text: '24 主备一致', link: '/mysql/24-master-slave-consistency' },
          { text: '25 高可用性', link: '/mysql/25-high-availability' },
          { text: '26 备库延迟', link: '/mysql/26-slave-delay' },
          { text: '27 主库故障', link: '/mysql/27-master-failure' },
          { text: '28 读写分离', link: '/mysql/28-read-write-split-pitfalls' },
          { text: '29 健康检查', link: '/mysql/29-database-health-check' },
          { text: '30 动态加锁', link: '/mysql/30-qa-dynamic-locking' },
        ],
      },
      {
        text: '运维进阶',
        collapsed: true,
        items: [
          { text: '31 误删恢复', link: '/mysql/31-data-recovery' },
          { text: '32 语句终止', link: '/mysql/32-unkillable-query' },
          { text: '33 查询内存', link: '/mysql/33-large-query-memory' },
          { text: '34 关联使用', link: '/mysql/34-join-usage' },
          { text: '35 关联优化', link: '/mysql/35-join-optimization' },
          { text: '36 临表重名', link: '/mysql/36-temp-table-rename' },
          { text: '37 内部临表', link: '/mysql/37-internal-temp-table' },
          { text: '38 引擎对比', link: '/mysql/38-innodb-vs-memory-engine' },
          { text: '39 自增间隙', link: '/mysql/39-auto-increment-gaps' },
          { text: '40 插入加锁', link: '/mysql/40-insert-locks' },
          { text: '41 快速拷表', link: '/mysql/41-fastest-table-copy' },
          { text: '42 权限刷新', link: '/mysql/42-grant-flush-privileges' },
          { text: '43 分区设计', link: '/mysql/43-partition-table' },
          { text: '44 问题答疑', link: '/mysql/44-qa-good-questions' },
          { text: '45 自增溢出', link: '/mysql/45-auto-increment-overflow' },
          { text: '46 收官总结', link: '/mysql/46-conclusion' },
        ],
      },
    ],
  }
