import type { SectionConfig } from './types'

export const nginxSection: SectionConfig = {
    key: 'nginx',
    base: '/nginx/',
    navText: 'Nginx',
    overviewDescription:
      '系统整理 Nginx 必须掌握的核心知识，覆盖请求匹配、反向代理、配置治理、OpenResty / Lua 扩展边界、gRPC / HTTP/2 / WebSocket 边界、CDN / 对象存储协同、Ingress / Gateway 映射、HTTPS、静态资源、性能优化、安全基线与常见排障。',
    landing: {
      eyebrow: 'Nginx',
      title: 'Nginx 专题',
      intro:
        '把 Nginx 从“会抄一份配置”提升到“能解释请求怎么匹配、代理怎么转发、配置怎么治理、什么时候该引入 OpenResty / Lua、协议边界怎么区分、分发链路怎么设计、Ingress / Gateway 怎么映射、HTTPS 怎么落、故障怎么排”的层面，先建立统一对象模型，再展开配置、治理、扩展边界、协议边界、分发、迁移、性能与运维主线。',
      primary: { title: '专题总览', href: '/nginx/', description: '先建立 Nginx 的完整框架。' },
      secondary: { title: '配置、Location 匹配与反向代理', href: '/nginx/config-and-reverse-proxy', description: '先讲清匹配规则和代理边界。' },
      scope: [
        'master / worker 与事件驱动',
        'server_name 与 location 匹配',
        'root / alias / try_files',
        'proxy_pass 与转发头',
        '配置拆分与变更发布',
        'OpenResty / Lua 扩展边界',
        'gRPC / HTTP/2 / WebSocket 边界',
        'Ingress / Gateway 映射与迁移',
        '负载均衡与 WebSocket',
        'HTTPS 与 TLS 终止',
        '静态资源缓存与压缩',
        '限流、安全基线与日常排障',
        '高频问题与自检口径',
      ],
      docs: [
        { title: 'Nginx 核心概念与请求处理模型', href: '/nginx/core-concepts', description: '建立 server、location、upstream 的统一对象模型。' },
        { title: 'Nginx 配置、Location 匹配与反向代理', href: '/nginx/config-and-reverse-proxy', description: '讲清 location 优先级、try_files、proxy_pass 与代理边界。' },
        { title: 'Nginx 上游、负载均衡与失败处理', href: '/nginx/upstream-load-balancing-and-failure-handling', description: '讲清 upstream、keepalive、失败重试与会话粘性边界。' },
        { title: 'Nginx gRPC、HTTP/2 与 WebSocket 实战', href: '/nginx/grpc-http2-and-websocket-boundaries', description: '讲清 grpc_pass、Upgrade 与 h2 / h2c / TLS 区别。' },
        { title: 'Nginx HTTPS、性能优化与安全基线', href: '/nginx/https-performance-and-security', description: '讲清 TLS 终止、缓存头、压缩与安全基线。' },
        { title: 'Nginx 缓存、回源与静态资源加速实战', href: '/nginx/cache-origin-and-static-acceleration-practice', description: '讲清 proxy_cache、缓存 key、回源条件与旧缓存兜底。' },
        { title: 'Nginx 与 CDN、对象存储协同实战', href: '/nginx/cdn-object-storage-and-large-file-distribution-practice', description: '讲清 CDN 回源、对象存储直链与大文件分发。' },
        { title: 'Nginx Ingress、K8s 网关映射实战', href: '/nginx/ingress-k8s-gateway-mapping-and-config-migration', description: '讲清 Nginx 配置到 Ingress / Gateway 的映射路径。' },
        { title: 'Nginx 多环境配置治理实战', href: '/nginx/multi-environment-config-governance-and-change-release', description: '讲清配置拆分、环境差异收口与平滑 reload。' },
        { title: 'Nginx 与 OpenResty、Lua 扩展实战', href: '/nginx/openresty-lua-extension-boundaries-and-use-cases', description: '讲清 Lua 执行阶段、适用场景与性能边界。' },
        { title: 'Nginx + Let\'s Encrypt / certbot 自动续期实战', href: '/nginx/lets-encrypt-and-certbot-renewal-practice', description: '讲清 HTTP-01、自动续期与 reload 协作。' },
        { title: 'Nginx 限流、白名单与安全防护实战', href: '/nginx/rate-limit-allowlist-and-security-hardening', description: '讲清 limit_req、白名单、Basic Auth 与方法限制。' },
        { title: 'Nginx 排障与日常运维', href: '/nginx/troubleshooting-and-operations', description: '整理 403/404/499/502/504 的排查主线。' },
        { title: 'Nginx 日志、监控与告警实战', href: '/nginx/logging-monitoring-and-alerting-practice', description: '讲清日志分析、stub_status、指标与告警分级。' },
        { title: 'Nginx 常见场景与配置模板', href: '/nginx/common-scenarios-and-config-templates', description: '整理 SPA、API、上传下载与维护页模板。' },
        { title: 'Nginx + Docker Compose 部署实战', href: '/nginx/docker-compose-deployment-practice', description: '讲清 Compose 编排、配置挂载与发布回滚。' },
        { title: 'Nginx 灰度发布与蓝绿切换实战', href: '/nginx/gray-release-blue-green-and-maintenance-switching', description: '讲清灰度、蓝绿切换与快速回滚。' },
        { title: 'Nginx 必备问题与自检清单', href: '/nginx/essential-questions', description: '整理对象模型、代理、HTTPS 与排障高频题。' },
      ],
      order: [
        'Nginx 核心概念与请求处理模型',
        'Nginx 配置、Location 匹配与反向代理',
        'Nginx 上游、负载均衡与失败处理',
        'Nginx gRPC、HTTP/2 与 WebSocket 实战',
        'Nginx HTTPS、性能优化与安全基线',
        'Nginx 缓存、回源与静态资源加速实战',
        'Nginx 与 CDN、对象存储协同实战',
        'Nginx Ingress、K8s 网关映射实战',
        'Nginx 多环境配置治理实战',
        'Nginx 与 OpenResty、Lua 扩展实战',
        'Nginx + Let\'s Encrypt / certbot 自动续期实战',
        'Nginx 限流、白名单与安全防护实战',
        'Nginx 排障与日常运维',
        'Nginx 日志、监控与告警实战',
        'Nginx 常见场景与配置模板',
        'Nginx + Docker Compose 部署实战',
        'Nginx 灰度发布与蓝绿切换实战',
        'Nginx 必备问题与自检清单',
      ],
    },
    sidebar: [
      {
        text: '全局认知',
        items: [
          { text: '专题总览', link: '/nginx/' },
          { text: '核心概念', link: '/nginx/core-concepts' },
        ],
      },
      {
        text: '配置代理',
        collapsed: true,
        items: [
          { text: '配置匹配', link: '/nginx/config-and-reverse-proxy' },
          { text: '负载均衡', link: '/nginx/upstream-load-balancing-and-failure-handling' },
          { text: '协议边界', link: '/nginx/grpc-http2-and-websocket-boundaries' },
          { text: 'Lua 扩展', link: '/nginx/openresty-lua-extension-boundaries-and-use-cases' },
        ],
      },
      {
        text: '上线优化',
        collapsed: true,
        items: [
          { text: 'HTTPS 安全', link: '/nginx/https-performance-and-security' },
          { text: '缓存加速', link: '/nginx/cache-origin-and-static-acceleration-practice' },
          { text: 'CDN 分发', link: '/nginx/cdn-object-storage-and-large-file-distribution-practice' },
          { text: 'K8s 映射', link: '/nginx/ingress-k8s-gateway-mapping-and-config-migration' },
          { text: '配置治理', link: '/nginx/multi-environment-config-governance-and-change-release' },
          { text: '证书续期', link: '/nginx/lets-encrypt-and-certbot-renewal-practice' },
          { text: '限流防护', link: '/nginx/rate-limit-allowlist-and-security-hardening' },
          { text: '配置模板', link: '/nginx/common-scenarios-and-config-templates' },
          { text: 'Compose', link: '/nginx/docker-compose-deployment-practice' },
          { text: '灰度发布', link: '/nginx/gray-release-blue-green-and-maintenance-switching' },
        ],
      },
      {
        text: '运维复习',
        collapsed: true,
        items: [
          { text: '排障运维', link: '/nginx/troubleshooting-and-operations' },
          { text: '日志监控', link: '/nginx/logging-monitoring-and-alerting-practice' },
          { text: '自检清单', link: '/nginx/essential-questions' },
        ],
      },
    ],
  }
