import type { SectionConfig } from './types'

export const nodejsSection: SectionConfig = {
  key: 'nodejs',
  base: '/nodejs/',
  navText: 'Node.js',
  overviewDescription:
    '适合希望系统补齐 Node.js 服务端能力的工程师，重点覆盖事件循环、模块系统、高并发治理、配置治理、可观测性、监控告警与压测演练、导出与大结果集治理、Feature Flag 与运行时治理、Webhook 与回调边界、数据库边界、测试工程化，以及 NestJS 与后台任务实践。',
  landing: {
    eyebrow: 'Node.js',
    title: 'Node.js 专题',
    intro:
      '把 Node.js 从“会跑一个脚本”提升到“能解释运行时、能定位性能问题、能设计高并发方案、能做监控告警与压测演练、能治理导出与大结果集、能落地 Feature Flag 与运行时开关、能守住 Webhook 与回调边界、能落地 NestJS 与后台任务工程实践”的层面，先建立服务端对象模型，再进入模块拆分、流量治理、测试治理、异步任务和部署主线。',
    primary: { title: '专题总览', href: '/nodejs/', description: '先看 Node.js 服务端能力地图和阅读顺序。' },
    secondary: { title: 'NestJS 实战指南', href: '/nodejs/nestjs-practice-guide', description: '从模块分层到测试部署，系统补齐 NestJS 工程落地方法。' },
    scope: [
      'Node.js 运行时与事件循环',
      '高并发、限流、削峰与背压治理',
      'CommonJS / ESM 与模块边界',
      'npm / pnpm / monorepo 工程化',
      '配置管理与环境变量治理',
      '日志、追踪与性能排障',
      '监控告警与压测演练闭环',
      '导出、报表与大结果集治理',
      'Feature Flag、灰度与运行时开关治理',
      'Webhook、回调与签名校验边界',
      'HTTP 服务分层与错误处理',
      'NestJS Module / Controller / Provider',
      'DTO、校验、鉴权与数据库事务',
      '队列、定时任务与异步处理',
      '测试、发布与优雅退出',
    ],
    docs: [
      { title: 'Node.js 专题总览', href: '/nodejs/', description: '先看 Node.js 服务端主线、适合人群和推荐阅读顺序。' },
      { title: 'Node.js 模块系统、ESM/CommonJS 与 monorepo 工程边界', href: '/nodejs/module-system-esm-commonjs-and-monorepo-boundaries', description: '把 import/export、require、包导出、workspace 和 monorepo 边界讲成一条工程主线。' },
      { title: 'Node.js 运行时、事件循环与性能排障', href: '/nodejs/runtime-event-loop-and-performance-troubleshooting', description: '把事件循环、microtask、流、内存、CPU 和线上排障顺序整理成一条线。' },
      { title: 'Node.js 高并发解决方案实践', href: '/nodejs/high-concurrency-solution-practice', description: '围绕事件循环、连接池、缓存、限流、异步削峰、Worker 和可观测性，系统整理 Node.js 高并发治理主线。' },
      { title: 'Node.js 缓存、热点 Key 与缓存一致性实践', href: '/nodejs/cache-hotkey-and-consistency-practice', description: '围绕本地缓存、Redis、两级缓存、热点 Key、缓存击穿/雪崩与一致性边界，系统整理 Node.js 缓存工程主线。' },
      { title: 'Node.js Redis 实战：客户端、连接池、Pipeline 与 Lua 脚本边界', href: '/nodejs/redis-client-pipeline-and-lua-practice', description: '围绕 Redis client 复用、连接管理、Pipeline、Lua 原子脚本、热点 Key、大 Key 与高并发边界，系统整理 Node.js Redis 工程主线。' },
      { title: 'Node.js 限流、超时与过载保护实践', href: '/nodejs/rate-limit-timeout-and-overload-protection-practice', description: '围绕 rate limit、concurrency limit、timeout、backpressure 和快速失败，系统整理 Node.js 服务保护边界。' },
      { title: 'Node.js HTTP Client、重试、熔断与退避实践', href: '/nodejs/http-client-retry-circuit-breaker-and-backoff-practice', description: '围绕 HTTP client 复用、超时、重试预算、退避、熔断、幂等与下游保护，系统整理 Node.js 外部 API 调用主线。' },
      { title: 'Node.js Webhook、回调与签名校验实践', href: '/nodejs/webhook-and-callback-practice', description: '围绕原始 body 验签、时间戳与重放防护、重复与乱序回调、2xx/5xx 返回语义与异步解耦，系统整理 Node.js webhook 主线。' },
      { title: 'Node.js 秒杀 / 抢券系统实践', href: '/nodejs/seckill-and-coupon-claim-system-practice', description: '围绕活动预热、资格校验、限流削峰、Redis 预扣减、异步排队、幂等补偿与结果查询，系统整理 Node.js 秒杀 / 抢券系统主线。' },
      { title: 'Node.js 幂等、状态机与 Outbox 实践', href: '/nodejs/idempotency-state-machine-and-outbox-practice', description: '围绕重复请求、状态推进、Outbox、本地事务、异步补偿与最终一致性，系统整理 Node.js 幂等与一致性工程主线。' },
      { title: 'Node.js 测试、Mock 与工程化实践', href: '/nodejs/testing-mock-and-engineering-practice', description: '系统整理项目结构、依赖管理、测试分层、Mock 策略、日志配置与发布基线。' },
      { title: 'Node.js 配置管理、日志、Tracing 与可观测性实践', href: '/nodejs/config-logging-tracing-and-observability-practice', description: '把配置收口、结构化日志、request id、trace、指标和线上观测边界整理成一条线。' },
      { title: 'Node.js 监控、告警与压测演练实践', href: '/nodejs/monitoring-alerting-and-pressure-drill-practice', description: '围绕 runtime 指标、依赖指标、业务指标、告警分级、压测建模与故障演练，系统整理 Node.js 稳定性保障闭环。' },
      { title: 'Node.js Feature Flag、运行时开关与灰度治理实践', href: '/nodejs/feature-flag-and-runtime-governance-practice', description: '围绕静态配置与运行时开关分层、灰度放量、kill switch、降级回退、观测审计与拆除治理，系统整理 Node.js 运行时治理主线。' },
      { title: 'Node.js 数据库、事务与 ORM/Query Builder 实践', href: '/nodejs/database-transaction-and-orm-practice', description: '系统整理连接管理、事务边界、Repository 分层、ORM 取舍和 Query Builder 使用边界。' },
      { title: 'Node.js 队列、定时任务与 Worker 实战', href: '/nodejs/queue-scheduler-and-worker-practice', description: '把异步任务、重试、幂等、死信、定时调度和优雅关闭的工程边界收成一页。' },
      { title: 'Node.js 导出、报表与大结果集实践', href: '/nodejs/export-report-and-large-result-practice', description: '围绕同步小导出、异步导出任务、流式读取、对象存储交付、权限配额与清理回收，系统整理 Node.js 导出与大结果集主线。' },
      { title: 'Express / Fastify Web 服务实践', href: '/nodejs/express-fastify-web-service-practice', description: '围绕路由、中间件、请求上下文、错误处理、分层和部署边界整理 Node.js Web 服务主线。' },
      { title: 'NestJS 实战指南', href: '/nodejs/nestjs-practice-guide', description: '系统整理 NestJS 项目结构、请求链路、数据边界、可观测性、测试与部署实践。' },
    ],
    order: [
      'Node.js 专题总览',
      'Node.js 模块系统、ESM/CommonJS 与 monorepo 工程边界',
      'Node.js 运行时、事件循环与性能排障',
      'Node.js 高并发解决方案实践',
      'Node.js 缓存、热点 Key 与缓存一致性实践',
      'Node.js Redis 实战：客户端、连接池、Pipeline 与 Lua 脚本边界',
      'Node.js 限流、超时与过载保护实践',
      'Node.js HTTP Client、重试、熔断与退避实践',
      'Node.js Webhook、回调与签名校验实践',
      'Node.js 秒杀 / 抢券系统实践',
      'Node.js 幂等、状态机与 Outbox 实践',
      'Node.js 测试、Mock 与工程化实践',
      'Node.js 配置管理、日志、Tracing 与可观测性实践',
      'Node.js 监控、告警与压测演练实践',
      'Node.js Feature Flag、运行时开关与灰度治理实践',
      'Node.js 数据库、事务与 ORM/Query Builder 实践',
      'Node.js 队列、定时任务与 Worker 实战',
      'Node.js 导出、报表与大结果集实践',
      'Express / Fastify Web 服务实践',
      'NestJS 实战指南',
    ],
  },
  sidebar: [
    {
      text: '核心入口',
      items: [
        { text: '专题总览', link: '/nodejs/' },
        { text: '模块系统', link: '/nodejs/module-system-esm-commonjs-and-monorepo-boundaries' },
        { text: '事件循环', link: '/nodejs/runtime-event-loop-and-performance-troubleshooting' },
        { text: '高并发', link: '/nodejs/high-concurrency-solution-practice' },
        { text: '缓存一致', link: '/nodejs/cache-hotkey-and-consistency-practice' },
        { text: 'Redis 实战', link: '/nodejs/redis-client-pipeline-and-lua-practice' },
        { text: '限流保护', link: '/nodejs/rate-limit-timeout-and-overload-protection-practice' },
        { text: '重试熔断', link: '/nodejs/http-client-retry-circuit-breaker-and-backoff-practice' },
        { text: 'Webhook 回调', link: '/nodejs/webhook-and-callback-practice' },
        { text: '秒杀抢券', link: '/nodejs/seckill-and-coupon-claim-system-practice' },
        { text: '幂等状态', link: '/nodejs/idempotency-state-machine-and-outbox-practice' },
        { text: '测试工程', link: '/nodejs/testing-mock-and-engineering-practice' },
        { text: '配置观测', link: '/nodejs/config-logging-tracing-and-observability-practice' },
        { text: '监控压测', link: '/nodejs/monitoring-alerting-and-pressure-drill-practice' },
        { text: '运行时开关', link: '/nodejs/feature-flag-and-runtime-governance-practice' },
        { text: '数据库事务', link: '/nodejs/database-transaction-and-orm-practice' },
        { text: '队列任务', link: '/nodejs/queue-scheduler-and-worker-practice' },
        { text: '导出报表', link: '/nodejs/export-report-and-large-result-practice' },
        { text: 'Web 服务', link: '/nodejs/express-fastify-web-service-practice' },
        { text: 'NestJS', link: '/nodejs/nestjs-practice-guide' },
      ],
    },
  ],
}
