import type { SectionConfig } from './types'

export const pythonSection: SectionConfig = {
  key: 'python',
  base: '/python/',
  navText: 'Python',
  overviewDescription:
    '适合希望系统掌握 Python 语言基础、数据模型、函数与模块、面向对象、标准库、异步并发、工程化，以及 Web、数据库、配置管理、自动化、爬虫、数据处理和 AI 工程方向实践的工程师。',
  landing: {
    eyebrow: 'Python',
    title: 'Python 方向',
    intro:
      '从语法、数据结构、函数、模块和面向对象，到 typing、asyncio、测试、打包与性能调优，再到数据库、配置管理、采集任务、数据处理和 AI 工程，把 Python 从入门到能稳定写工程代码的主线整理成一组清晰入口。',
    primary: { title: 'Python 必备知识', href: '/python/essential-knowledge', description: '先把必须掌握的知识框架搭起来。' },
    secondary: { title: 'Python 学习路径', href: '/python/learning-path', description: '再按阶段推进练习和项目。' },
    scope: [
      '语法基础与数据结构',
      '函数、作用域与闭包',
      '对象模型与可变性',
      '模块、包与导入系统',
      '面向对象与 dataclass',
      '异常、文件与上下文管理',
      '标准库与 typing',
      '线程、进程与 asyncio',
      '测试、虚拟环境与打包',
      '性能优化与调试',
      'FastAPI / Web 后端',
      '数据库 / 事务 / ORM',
      'Pydantic / 配置管理',
      'CLI 自动化 / subprocess',
      '爬虫 / HTTP 抓取 / 异步采集',
      'NumPy / pandas 数据处理',
      'AI 工程 / RAG / 服务化',
    ],
    docs: [
      { title: 'Python 方向概览', href: '/python/', description: '先看入口、适合人群和阅读顺序。' },
      { title: 'Python 必备知识：由浅入深', href: '/python/essential-knowledge', description: '系统梳理必须掌握的语言、标准库、并发和工程化知识。' },
      { title: 'Python 数据模型与常见陷阱', href: '/python/data-model-and-common-pitfalls', description: '重点补名字绑定、可变性、拷贝、哈希、闭包和高频坑。' },
      { title: 'Python 标准库与 typing 必修清单', href: '/python/standard-library-and-typing', description: '重点补标准库工具箱、接口边界和类型标注。' },
      { title: 'Python 函数、模块与装饰器', href: '/python/functions-modules-and-decorators', description: '重点补参数设计、模块拆分、导入边界和装饰器本质。' },
      { title: 'Python 面向对象、类设计与 dataclass', href: '/python/object-oriented-programming-and-dataclass', description: '重点补类设计、组合与继承、属性管理和数据类建模。' },
      { title: 'Python 异常、文件处理与上下文管理', href: '/python/exceptions-files-and-context-managers', description: '重点补错误表达、资源释放、with 和上下文管理器。' },
      { title: 'Python 并发、GIL 与 asyncio', href: '/python/concurrency-and-asyncio', description: '重点补线程、进程、协程与事件循环边界。' },
      { title: 'Python 性能、内存与调试排障', href: '/python/performance-debugging-and-memory', description: '重点补热点定位、内存问题、调试思路和优化顺序。' },
      { title: 'Python 测试、项目结构与工程化', href: '/python/testing-and-project-engineering', description: '重点补项目结构、依赖管理、测试和发布基本盘。' },
      { title: 'Python 学习路径', href: '/python/learning-path', description: '按阶段拆出学习目标、练习方式和阶段产出。' },
      { title: 'Python FastAPI 与 Web 后端实践', href: '/python/fastapi-and-web-backend-practice', description: '重点补路由分层、依赖注入、事务、鉴权和接口边界。' },
      { title: 'Python 数据库、事务与 ORM 实践', href: '/python/database-and-orm-practice', description: '重点补事务边界、session 生命周期、迁移、索引和 ORM 常见坑。' },
      { title: 'Python Pydantic、配置管理与数据校验', href: '/python/pydantic-and-settings-management', description: '重点补请求/响应模型、配置收口、结构化校验和序列化边界。' },
      { title: 'Python pytest 进阶与测试替身', href: '/python/pytest-advanced-and-test-doubles', description: '重点补 fixture、monkeypatch、mock、fake 和异步测试。' },
      { title: 'Python CLI 自动化与 subprocess 实践', href: '/python/automation-cli-and-subprocess-practice', description: '重点补参数设计、子进程、日志、退出码和可重跑性。' },
      { title: 'Python 爬虫、HTTP 抓取与异步采集实践', href: '/python/web-scraping-and-async-fetching-practice', description: '重点补采集流水线、超时重试、限流、解析、去重和断点续跑。' },
      { title: 'Python NumPy、pandas 与数据处理实践', href: '/python/numpy-pandas-and-data-processing-practice', description: '重点补数组/表格心智模型、清洗聚合和数据任务工程化。' },
      { title: 'Python AI 工程、RAG 与服务化实践', href: '/python/ai-engineering-and-rag-practice', description: '重点补模型调用收口、RAG、Tool 边界、评测、观测和服务化。' },
    ],
    order: [
      'Python 方向概览',
      'Python 必备知识：由浅入深',
      'Python 数据模型与常见陷阱',
      'Python 标准库与 typing 必修清单',
      'Python 函数、模块与装饰器',
      'Python 面向对象、类设计与 dataclass',
      'Python 异常、文件处理与上下文管理',
      'Python 并发、GIL 与 asyncio',
      'Python 性能、内存与调试排障',
      'Python 测试、项目结构与工程化',
      'Python 学习路径',
      'Python FastAPI 与 Web 后端实践',
      'Python 数据库、事务与 ORM 实践',
      'Python Pydantic、配置管理与数据校验',
      'Python pytest 进阶与测试替身',
      'Python CLI 自动化与 subprocess 实践',
      'Python 爬虫、HTTP 抓取与异步采集实践',
      'Python NumPy、pandas 与数据处理实践',
      'Python AI 工程、RAG 与服务化实践',
    ],
  },
  sidebar: [
    {
      text: '核心入口',
      items: [
        { text: '方向概览', link: '/python/' },
        { text: '必备知识', link: '/python/essential-knowledge' },
        { text: '学习路径', link: '/python/learning-path' },
      ],
    },
    {
      text: '核心专题',
      items: [
        { text: '数据模型', link: '/python/data-model-and-common-pitfalls' },
        { text: '标准库', link: '/python/standard-library-and-typing' },
        { text: '函数模块', link: '/python/functions-modules-and-decorators' },
        { text: '面向对象', link: '/python/object-oriented-programming-and-dataclass' },
        { text: '异常处理', link: '/python/exceptions-files-and-context-managers' },
        { text: '并发异步', link: '/python/concurrency-and-asyncio' },
        { text: '性能调试', link: '/python/performance-debugging-and-memory' },
        { text: '测试工程', link: '/python/testing-and-project-engineering' },
      ],
    },
    {
      text: '方向实践',
      items: [
        { text: 'FastAPI', link: '/python/fastapi-and-web-backend-practice' },
        { text: '数据库 ORM', link: '/python/database-and-orm-practice' },
        { text: 'Pydantic', link: '/python/pydantic-and-settings-management' },
        { text: 'pytest', link: '/python/pytest-advanced-and-test-doubles' },
        { text: 'CLI 自动化', link: '/python/automation-cli-and-subprocess-practice' },
        { text: '爬虫采集', link: '/python/web-scraping-and-async-fetching-practice' },
        { text: '数据处理', link: '/python/numpy-pandas-and-data-processing-practice' },
        { text: 'AI 工程', link: '/python/ai-engineering-and-rag-practice' },
      ],
    },
    {
      text: '阅读顺序',
      collapsed: true,
      items: [
        { text: '1. 方向概览', link: '/python/' },
        { text: '2. 必备知识', link: '/python/essential-knowledge' },
        { text: '3. 数据与标准库', link: '/python/data-model-and-common-pitfalls' },
        { text: '4. 函数与异常', link: '/python/functions-modules-and-decorators' },
        { text: '5. 并发与工程', link: '/python/concurrency-and-asyncio' },
        { text: '6. 方向实践', link: '/python/fastapi-and-web-backend-practice' },
        { text: '7. 路径练习', link: '/python/learning-path' },
      ],
    },
  ],
}
