import type { SectionConfig } from './types'

export const redisSection: SectionConfig = {
    key: 'redis',
    base: '/redis/',
    navText: 'Redis',
    overviewDescription:
      '系统整理 Redis 核心知识，并收录《Redis 核心技术与实战》章节笔记，涵盖缓存治理、客户端实践、分布式锁、集群与高并发场景。',
    landing: {
      eyebrow: 'Redis',
      title: 'Redis 专题',
      intro:
        '把散落在 Go 实践、源码精读、支付系统案例和极客时间课程中的 Redis 内容统一收敛，既能按主题解决问题，也能按课程主线系统精读。',
      primary: { title: '专题总览', href: '/redis/', description: '从总览页开始，按主题查阅。' },
      secondary: { title: '课程精读', href: '/redis/course/', description: '按 52 讲系统学习 Redis。' },
      scope: [
        'Redis 课程精读',
        'go-redis 客户端实践',
        '缓存穿透/击穿/雪崩',
        '高并发治理与集群部署',
        'Pipeline 与 Pub/Sub',
        '分布式锁与 Lua',
        '滑动窗口与限流',
        '支付系统幂等与高并发治理',
      ],
      docs: [
        { title: 'Redis 核心技术与实战课程精读', href: '/redis/course/', description: '按章节整理 52 讲，系统覆盖架构、IO、复制、哨兵、集群、事务与 Redis 6.0。' },
        { title: 'Redis 实践与缓存穿透/击穿/雪崩', href: '/redis/redis-and-cache-patterns', description: 'go-redis 基础用法、Pipeline、Pub/Sub、singleflight、布隆过滤器与多级缓存。' },
        { title: 'Redis 高并发、集群部署与分布式锁', href: '/redis/high-concurrency-cluster-locks', description: '热点 Key / 大 Key 治理、Sentinel / Cluster 选型、hash tag、分布式锁与 Lua 原子脚本。' },
        { title: 'go-redis 客户端源码精读', href: '/golang/guide/source-reading/go-redis', description: '连接池、Pipeline/TxPipeline、分布式锁、Watch 与客户端设计细节。' },
        { title: '支付系统 Redis 实战', href: '/redis/payment-practice', description: '缓存治理、分布式锁、Lua、滑动窗口、请求级幂等与支付场景答题模板。' },
      ],
      order: [
        'Redis 核心技术与实战课程精读',
        'Redis 实践与缓存穿透/击穿/雪崩',
        'Redis 高并发、集群部署与分布式锁',
        'go-redis 客户端源码精读',
        '支付系统 Redis 实战',
      ],
    },
    sidebar: [
      {
        text: 'Redis 专题',
        items: [
          { text: '专题总览', link: '/redis/' },
          { text: '课程精读总览', link: '/redis/course/' },
          { text: 'Redis 实践与缓存穿透/击穿/雪崩', link: '/redis/redis-and-cache-patterns' },
          { text: 'Redis 高并发、集群部署与分布式锁', link: '/redis/high-concurrency-cluster-locks' },
          { text: 'go-redis 客户端源码精读', link: '/golang/guide/source-reading/go-redis' },
          { text: '支付系统 Redis 实战', link: '/redis/payment-practice' },
        ],
      },
      {
        text: '开篇与基础篇',
        collapsed: true,
        items: [
          { text: '00 开篇词', link: '/redis/course/00-preface' },
          { text: '01 基本架构', link: '/redis/course/01-basic-architecture' },
          { text: '02 慢操作', link: '/redis/course/02-slow-operations' },
          { text: '03 高性能 IO 模型', link: '/redis/course/03-high-performance-io' },
          { text: '04 AOF 日志', link: '/redis/course/04-aof-log' },
          { text: '05 RDB 快照', link: '/redis/course/05-rdb-snapshot' },
          { text: '06 主从一致性', link: '/redis/course/06-replication-consistency' },
          { text: '07 哨兵机制', link: '/redis/course/07-sentinel-mechanism' },
          { text: '08 哨兵集群', link: '/redis/course/08-sentinel-cluster' },
          { text: '09 切片集群', link: '/redis/course/09-cluster-sharding' },
          { text: '10 基础篇答疑', link: '/redis/course/10-foundation-qa' },
        ],
      },
      {
        text: '实践篇（11-22）',
        collapsed: true,
        items: [
          { text: '11 String 的边界', link: '/redis/course/11-string-pitfalls' },
          { text: '12 一亿个 keys 统计', link: '/redis/course/12-billion-keys-set-selection' },
          { text: '13 GEO 与自定义类型', link: '/redis/course/13-geo-and-custom-types' },
          { text: '14 时间序列数据', link: '/redis/course/14-time-series-data' },
          { text: '15 消息队列方案', link: '/redis/course/15-message-queue-solutions' },
          { text: '16 异步机制', link: '/redis/course/16-async-mechanism' },
          { text: '17 CPU 结构影响', link: '/redis/course/17-cpu-architecture-impact' },
          { text: '18 响应延迟（上）', link: '/redis/course/18-latency-spike-part1' },
          { text: '19 响应延迟（下）', link: '/redis/course/19-latency-spike-part2' },
          { text: '20 删除后内存仍高', link: '/redis/course/20-memory-after-delete' },
          { text: '21 缓冲区风险', link: '/redis/course/21-buffer-risks' },
          { text: '22 实践篇答疑（一）', link: '/redis/course/22-practice-qa-1' },
        ],
      },
      {
        text: '实践篇（23-38）',
        collapsed: true,
        items: [
          { text: '23 旁路缓存', link: '/redis/course/23-cache-aside' },
          { text: '24 替换策略', link: '/redis/course/24-eviction-policy' },
          { text: '25 缓存一致性', link: '/redis/course/25-cache-consistency' },
          { text: '26 缓存异常治理', link: '/redis/course/26-cache-anomalies' },
          { text: '27 缓存污染', link: '/redis/course/27-cache-pollution' },
          { text: '28 Pika 与 SSD', link: '/redis/course/28-pika-ssd' },
          { text: '29 原子操作', link: '/redis/course/29-atomic-operations' },
          { text: '30 分布式锁', link: '/redis/course/30-distributed-lock' },
          { text: '31 事务机制', link: '/redis/course/31-transaction-acid' },
          { text: '32 主从同步与切换坑点', link: '/redis/course/32-replication-failover-pitfalls' },
          { text: '33 脑裂与数据丢失', link: '/redis/course/33-split-brain-data-loss' },
          { text: '34 实践篇答疑（二）', link: '/redis/course/34-practice-qa-2' },
          { text: '35 Codis vs Cluster', link: '/redis/course/35-codis-vs-redis-cluster' },
          { text: '36 秒杀实践', link: '/redis/course/36-seckill-practice' },
          { text: '37 数据倾斜', link: '/redis/course/37-data-skew' },
          { text: '38 集群通信开销', link: '/redis/course/38-cluster-communication-overhead' },
        ],
      },
      {
        text: '未来篇与加餐',
        collapsed: true,
        items: [
          { text: '39 Redis 6.0 新特性', link: '/redis/course/39-redis6-new-features' },
          { text: '40 NVM 实践', link: '/redis/course/40-nvm-practice' },
          { text: '41 未来篇答疑', link: '/redis/course/41-future-qa' },
          { text: '42 学习资料', link: '/redis/course/42-extra-learning-resources' },
          { text: '43 如何学习 Redis', link: '/redis/course/43-extra-learning-method' },
          { text: '44 在压力中成长', link: '/redis/course/44-extra-growth-under-pressure' },
          { text: '45 客户端与服务器协议', link: '/redis/course/45-extra-client-server-protocol' },
          { text: '46 运维工具', link: '/redis/course/46-extra-ops-tools' },
          { text: '47 使用规范建议', link: '/redis/course/47-extra-usage-guidelines' },
          { text: '48 微博 Redis 实践', link: '/redis/course/48-extra-weibo-practice' },
        ],
      },
      {
        text: '测试与收官',
        collapsed: true,
        items: [
          { text: '49 期中测试题', link: '/redis/course/49-midterm-quiz' },
          { text: '50 期中测试答案', link: '/redis/course/50-midterm-quiz-answers' },
          { text: '51 结束语', link: '/redis/course/51-conclusion' },
        ],
      },
    ],
  }
