import type { SectionConfig } from './types'

export const rustSection: SectionConfig = {
  key: 'rust',
  base: '/rust/',
  navText: 'Rust',
  overviewDescription:
    '适合希望系统掌握 Rust 语言基础、所有权模型、类型系统、错误处理、Cargo 工程化与并发 async 的工程师。',
  landing: {
    eyebrow: 'Rust',
    title: 'Rust 方向',
    intro:
      '从所有权模型、类型系统与错误处理，到 Cargo 工程化、测试和并发 async，把 Rust 入门到能写出可靠代码的必备知识串成一条清晰路径。',
    primary: { title: 'Rust 学习路径', href: '/rust/learning-path', description: '先按阶段看整体主线。' },
    secondary: { title: 'Rust 必备知识总览', href: '/rust/essential-knowledge', description: '再建立整体知识地图。' },
    scope: [
      '所有权与借用',
      'Borrow Checker 排障',
      '生命周期',
      'struct / enum / match',
      'trait / 泛型',
      'DTO / 领域模型分层',
      '输入校验 / 边界建模',
      '错误处理',
      'Cargo / 测试 / 工程化',
      'crate 选型与边界',
      'CLI 工具实践',
      '配置管理',
      'Workspace 与 Monorepo',
      'HTTP client / 外部 API',
      '后台任务与 Worker',
      '定时任务 / 调度 / Leader Election',
      '缓存 / Redis',
      '集合与字符串处理',
      '智能指针与内部可变性',
      '线程并发与 async 基础',
      'Tokio async 工程实践',
      'Axum Web 服务实践',
      '限流 / 超时 / 负载保护',
      'API 错误响应 / 响应体设计',
      'API Versioning / 兼容 / 弃用治理',
      '过滤 / 排序 / 分页',
      '搜索 / 索引 / 检索',
      '软删除 / 恢复 / 删除语义',
      '批处理 / 回填 / 历史数据修复',
      '幂等 / 状态机 / Outbox',
      '消息队列 / 事件驱动',
      '通知 / 邮件 / 短信 / Push',
      '文件上传 / 对象存储 / S3',
      '认证 / 请求上下文',
      'Secrets / 密钥 / 凭证轮换',
      '数据脱敏 / 隐私字段 / 日志安全',
      'Feature Flag / 运行时开关 / 灰度治理',
      '多租户 / 数据隔离',
      '审计日志 / 操作记录',
      'Webhook / 回调 / 签名校验',
      'WebSocket / SSE',
      'SQLx 数据库访问实践',
      '事务 / 锁 / 并发更新',
      '数据库迁移 / Schema 演进',
      '导出 / 报表 / 大结果集',
      '数据归档 / 保留策略 / 冷热分层',
      'Axum + SQLx 服务落地模板',
      'Tracing 与可观测性',
      'Metrics / OpenTelemetry',
      '性能分析与 Profiling',
      '配置与优雅关闭',
      '后端项目骨架',
      '部署与发布清单',
      'Serde 与数据序列化',
      '宏与元编程',
      'Unsafe / FFI 边界',
      '测试替身与依赖隔离',
      '能力自检与面试准备',
      '面试代码片段',
    ],
    docs: [
      { title: 'Rust 学习路径与资料导航', href: '/rust/learning-path', description: '把 Rust 核心主题按阶段串成一条学习主线。' },
      { title: 'Rust 必备知识总览', href: '/rust/essential-knowledge', description: '先建立 Rust 的主线认知，明确先学什么、后学什么。' },
      { title: 'Rust 能力自检与面试准备导航', href: '/rust/interview-prep', description: '把问题清单、学习主线和专题回查入口收敛到一页。' },
      { title: 'Rust 必备问题清单', href: '/rust/essential-questions', description: '按由浅入深整理 30 个最常用来检验理解深度的问题。' },
      { title: 'Rust 能力自检高频题示例代码片段', href: '/rust/interview-code-snippets', description: '用最小、可讲解、可手写的代码片段把所有权、迭代器、错误处理和 async 高频题落下来。' },
      { title: '所有权、借用与生命周期', href: '/rust/ownership-borrowing-and-lifetimes', description: '理解 move、借用规则、切片和生命周期约束。' },
      { title: 'Rust Borrow Checker 常见报错排障指南', href: '/rust/borrow-checker-troubleshooting-guide', description: '集中处理 moved value、借用冲突、生命周期不够长和 async 边界等高频编译报错。' },
      { title: '集合、字符串与迭代器', href: '/rust/collections-strings-and-iterators', description: '补齐 String、Vec、HashMap 和 iterator 的日常编码边界。' },
      { title: 'Trait、泛型与模式匹配', href: '/rust/traits-generics-and-pattern-matching', description: '把类型建模、行为抽象和通用逻辑复用放到一条线上理解。' },
      { title: '智能指针与内部可变性', href: '/rust/smart-pointers-and-interior-mutability', description: '理解 Box、Rc、Arc、RefCell、Mutex 等工具的职责边界。' },
      { title: '错误处理、Cargo 与测试', href: '/rust/error-handling-cargo-and-testing', description: '补齐 Result、工程结构、测试、格式化与 lint 的基础工作流。' },
      { title: '项目结构、crate 组织与 API 设计', href: '/rust/project-structure-and-api-design', description: '把模块、crate、workspace 和 API 边界放到工程视角下理解。' },
      { title: 'Rust DTO、领域模型与存储模型分层实践', href: '/rust/dto-domain-and-persistence-model-practice', description: '把请求 DTO、领域对象、数据库模型和外部 API DTO 的职责边界与映射方式收成一页。' },
      { title: 'Rust 输入校验与边界建模实践', href: '/rust/validation-and-input-boundaries-practice', description: '把 serde 解析、字段校验、领域不变量、axum 输入边界和错误映射收成一页。' },
      { title: 'Rust 常用 crate 选型与工程边界', href: '/rust/crate-selection-and-boundaries', description: '把 CLI、错误处理、序列化、async、HTTP、数据库和 tracing 这些高频依赖的选型思路、feature 控制和适用边界收成一页。' },
      { title: 'Rust CLI 工具实践', href: '/rust/cli-tool-practice', description: '把参数解析、配置加载、错误处理、文件 I/O、HTTP 调用和集成测试收成一条完整的小工具主线。' },
      { title: 'Rust 配置管理实践', href: '/rust/configuration-management-practice', description: '把默认值、文件、环境变量、命令行、校验和多来源合并收成一条清晰的配置主线。' },
      { title: 'Rust Workspace 与 Monorepo 实践', href: '/rust/workspace-and-monorepo-practice', description: '把多 crate 项目的拆分时机、workspace.dependencies、default-members、resolver 与依赖治理收成一页。' },
      { title: '并发与 Async 基础', href: '/rust/concurrency-and-async', description: '理解 Send/Sync、线程、共享状态和 async 的基本边界。' },
      { title: 'Tokio 与 Async 工程实践', href: '/rust/tokio-and-async-practice', description: '补 runtime、task、超时、取消和阻塞边界。' },
      { title: 'Rust HTTP Client 与外部 API 实践', href: '/rust/http-client-and-external-api-practice', description: '把 reqwest、timeout、认证、错误分层、重试、幂等和 tracing 这些外部调用边界收成一页。' },
      { title: 'Rust 后台任务与 Worker 实践', href: '/rust/background-jobs-and-worker-practice', description: '把进程内 task、定时任务、队列消费者、取消、背压、重试和幂等这些后台执行边界收成一页。' },
      { title: 'Rust 定时任务、调度与 Leader Election 实践', href: '/rust/scheduler-and-leader-election-practice', description: '把 interval / cron、补跑、单实例执行、租约选主、关闭交接和调度观测收成一页。' },
      { title: 'Rust 缓存与 Redis 实践', href: '/rust/cache-and-redis-practice', description: '把本地缓存、Redis、TTL、cache-aside、两级缓存和缓存击穿/雪崩这些读路径边界收成一页。' },
      { title: 'Axum Web 服务实践', href: '/rust/axum-web-service-practice', description: '围绕 Router、State、Extractor、Middleware 和错误边界梳理 Rust Web 服务主线。' },
      { title: 'Rust 限流、超时与负载保护实践', href: '/rust/rate-limit-timeout-and-overload-protection-practice', description: '把 timeout、并发限制、rate limit、load shed、buffer 和 backpressure 这些服务保护边界收成一页。' },
      { title: 'Rust API 错误响应与响应体设计实践', href: '/rust/api-error-and-response-design-practice', description: '把 IntoResponse、状态码分层、统一错误体、request id 透传和中间件错误收口成一套稳定 API 契约。' },
      { title: 'Rust API Versioning、兼容演进与弃用治理实践', href: '/rust/api-versioning-and-compatibility-governance-practice', description: '把路径与 header 版本策略、兼容新增、错误契约稳定性、弃用窗口和多版本观测收成一页。' },
      { title: 'Rust 列表查询、过滤、排序与分页实践', href: '/rust/pagination-filter-and-sorting-practice', description: '把 Query DTO、过滤条件、排序白名单、offset 与 cursor 分页、total 成本和索引约束收成一页。' },
      { title: 'Rust 搜索、索引与检索实践', href: '/rust/search-index-and-retrieval-practice', description: '把搜索 query DTO、索引文档、异步同步、回填重建和 alias 切换收成一页。' },
      { title: 'Rust 软删除、恢复与删除语义实践', href: '/rust/soft-delete-restore-and-deletion-semantics-practice', description: '把 deleted_at、恢复窗口、物理删除时机和查询边界收成一页。' },
      { title: 'Rust 批处理、回填与历史数据修复实践', href: '/rust/batch-processing-backfill-and-historical-repair-practice', description: '把分批扫描、checkpoint、限速、dry-run、补跑和历史修复收成一页。' },
      { title: 'Rust 幂等、状态机与 Outbox 实践', href: '/rust/idempotency-state-machine-and-outbox-practice', description: '把请求级幂等键、业务唯一键、条件更新、状态机推进和 Outbox 一起收成有副作用操作的一致性主线。' },
      { title: 'Rust 消息队列与事件驱动实践', href: '/rust/message-queue-and-event-driven-practice', description: '把 producer、consumer、事件契约、至少一次投递、重试、死信、顺序性和幂等消费收成一条消息驱动主线。' },
      { title: 'Rust 通知、邮件、短信与消息触达实践', href: '/rust/notification-email-sms-and-delivery-practice', description: '把通知意图、模板、渠道选择、回调状态和限流收成一页。' },
      { title: 'Rust 文件上传、对象存储与 S3 实践', href: '/rust/file-upload-and-object-storage-practice', description: '把 multipart、流式上传、预签名 URL、对象 key、元数据落库、异步后处理和 orphan 清理收成一页。' },
      { title: 'Rust 认证、授权与请求上下文实践', href: '/rust/auth-authorization-and-request-context-practice', description: '把 middleware、extractor、route_layer、当前用户、request id 和服务授权边界收成一页。' },
      { title: 'Rust Secrets、密钥与凭证轮换实践', href: '/rust/secret-management-and-credential-rotation-practice', description: '把 secret 注入、JWK / webhook secret 轮换、对象存储凭证和外部 API token 脱敏收成一页。' },
      { title: 'Rust 数据脱敏、隐私字段与日志安全实践', href: '/rust/data-masking-privacy-and-log-safety-practice', description: '把 DTO 暴露、日志 / trace / audit 脱敏、导出和对象存储交付边界收成一页。' },
      { title: 'Rust Feature Flag、运行时开关与灰度治理实践', href: '/rust/feature-flag-and-runtime-governance-practice', description: '把静态配置和运行时开关分层、按租户和按比例灰度、kill switch、回退降级和治理收成一页。' },
      { title: 'Rust 多租户与数据隔离实践', href: '/rust/multi-tenant-and-data-isolation-practice', description: '把 tenant context、SQL 过滤、租户内唯一约束、缓存 key、对象 key、租户配额和观测边界收成一页。' },
      { title: 'Rust 审计日志与操作记录实践', href: '/rust/audit-log-and-operation-history-practice', description: '把 actor、tenant、resource、request id、trace id、脱敏和异步审计落库边界收成一页。' },
      { title: 'Rust Webhook、回调与签名校验实践', href: '/rust/webhook-and-callback-practice', description: '把原始 body 验签、重放防护、重复与乱序回调、2xx / 5xx 返回语义和异步解耦收成一页。' },
      { title: 'Rust WebSocket 与 SSE 实践', href: '/rust/websocket-and-sse-practice', description: '把 WebSocketUpgrade、SSE、broadcast/watch、慢消费者和长连接生命周期收成一页。' },
      { title: 'SQLx 数据库访问实践', href: '/rust/sqlx-database-practice', description: '补连接池、编译期 SQL 校验、事务、迁移和分层设计。' },
      { title: 'Rust 事务、锁与并发更新实践', href: '/rust/transaction-locking-and-concurrent-update-practice', description: '把事务边界、隔离级别、条件更新、乐观锁、FOR UPDATE 和锁冲突排障收成一页。' },
      { title: 'Rust 数据库迁移、Schema 演进与兼容发布实践', href: '/rust/database-migration-and-schema-evolution-practice', description: '把 expand / contract、回填、双读双写、索引变更和兼容发布边界收成一页。' },
      { title: 'Rust 导出、报表与大结果集实践', href: '/rust/export-report-and-large-result-practice', description: '把异步导出任务、批量扫描、对象存储交付、租户配额和审计留痕收成一页。' },
      { title: 'Rust 数据归档、保留策略与冷热分层实践', href: '/rust/data-archiving-retention-and-hot-cold-tiering-practice', description: '把保留窗口、冷热分层、归档恢复和对象冷存储边界收成一页。' },
      { title: 'Axum + SQLx 服务落地模板', href: '/rust/axum-sqlx-service-template', description: '把目录结构、Cargo、启动顺序、State、Router、SQLx 和关闭流程收成一份可直接照着搭的模板。' },
      { title: 'Tracing 与可观测性实践', href: '/rust/tracing-and-observability-practice', description: '把 event、span、instrument、subscriber 和服务观测边界串起来。' },
      { title: 'Rust Metrics 与 OpenTelemetry 实践', href: '/rust/metrics-and-opentelemetry-practice', description: '把 counter、gauge、histogram、OTLP exporter、标签基数和指标闭环收成一页。' },
      { title: 'Rust 性能分析与 Profiling 指南', href: '/rust/performance-and-profiling-guide', description: '补 release 构建、bench、flamegraph、内存分配分析和 async 争用排障的实战主线。' },
      { title: '服务配置与优雅关闭', href: '/rust/service-configuration-and-graceful-shutdown', description: '补配置加载、启动校验、信号处理、任务协调和关闭流程。' },
      { title: 'Rust 后端项目骨架', href: '/rust/backend-project-skeleton', description: '把 axum、sqlx、tracing、配置和关闭流程收成一个可持续演进的服务骨架。' },
      { title: 'Rust 服务部署与发布清单', href: '/rust/deployment-and-release-checklist', description: '把镜像构建、配置注入、迁移、健康检查、资源、发布验证和回滚收成一页上线清单。' },
      { title: 'Serde 与数据序列化实践', href: '/rust/serde-and-data-serialization', description: '理解类型与外部协议、配置格式之间的映射和错误边界。' },
      { title: '宏与元编程基础', href: '/rust/macros-and-metaprogramming', description: '理清声明宏、过程宏和普通抽象手段的边界。' },
      { title: 'Unsafe 与 FFI 边界', href: '/rust/unsafe-and-ffi-boundaries', description: '理解 unsafe 责任转移、封装原则和跨语言交互风险。' },
      { title: '测试与质量实践', href: '/rust/testing-and-quality-practice', description: '把测试、fmt、clippy 和回归策略收成一条质量闭环。' },
      { title: 'Rust 测试替身与依赖隔离实践', href: '/rust/test-doubles-and-dependency-isolation-practice', description: '把 fake、stub、mock、本地 HTTP server、Tokio 异步测试和依赖隔离策略收成一页。' },
    ],
    order: [
      'Rust 学习路径与资料导航',
      'Rust 必备知识总览',
      'Rust 能力自检与面试准备导航',
      'Rust 必备问题清单',
      'Rust 能力自检高频题示例代码片段',
      '所有权、借用与生命周期',
      'Rust Borrow Checker 常见报错排障指南',
      '集合、字符串与迭代器',
      'Trait、泛型与模式匹配',
      '智能指针与内部可变性',
      '错误处理、Cargo 与测试',
      '项目结构、crate 组织与 API 设计',
      'Rust DTO、领域模型与存储模型分层实践',
      'Rust 输入校验与边界建模实践',
      'Rust 常用 crate 选型与工程边界',
      'Rust CLI 工具实践',
      'Rust 配置管理实践',
      'Rust Workspace 与 Monorepo 实践',
      '并发与 Async 基础',
      'Tokio 与 Async 工程实践',
      'Rust HTTP Client 与外部 API 实践',
      'Rust 后台任务与 Worker 实践',
      'Rust 定时任务、调度与 Leader Election 实践',
      'Rust 缓存与 Redis 实践',
      'Axum Web 服务实践',
      'Rust 限流、超时与负载保护实践',
      'Rust API 错误响应与响应体设计实践',
      'Rust API Versioning、兼容演进与弃用治理实践',
      'Rust 列表查询、过滤、排序与分页实践',
      'Rust 搜索、索引与检索实践',
      'Rust 软删除、恢复与删除语义实践',
      'Rust 批处理、回填与历史数据修复实践',
      'Rust 幂等、状态机与 Outbox 实践',
      'Rust 消息队列与事件驱动实践',
      'Rust 通知、邮件、短信与消息触达实践',
      'Rust 文件上传、对象存储与 S3 实践',
      'Rust 认证、授权与请求上下文实践',
      'Rust Secrets、密钥与凭证轮换实践',
      'Rust 数据脱敏、隐私字段与日志安全实践',
      'Rust Feature Flag、运行时开关与灰度治理实践',
      'Rust 多租户与数据隔离实践',
      'Rust 审计日志与操作记录实践',
      'Rust Webhook、回调与签名校验实践',
      'Rust WebSocket 与 SSE 实践',
      'SQLx 数据库访问实践',
      'Rust 事务、锁与并发更新实践',
      'Rust 数据库迁移、Schema 演进与兼容发布实践',
      'Rust 导出、报表与大结果集实践',
      'Rust 数据归档、保留策略与冷热分层实践',
      'Axum + SQLx 服务落地模板',
      'Tracing 与可观测性实践',
      'Rust Metrics 与 OpenTelemetry 实践',
      'Rust 性能分析与 Profiling 指南',
      '服务配置与优雅关闭',
      'Rust 后端项目骨架',
      'Rust 服务部署与发布清单',
      'Serde 与数据序列化实践',
      '宏与元编程基础',
      'Unsafe 与 FFI 边界',
      '测试与质量实践',
      'Rust 测试替身与依赖隔离实践',
    ],
  },
  sidebar: [
    {
      text: '核心入口',
      items: [
        { text: '方向概览', link: '/rust/' },
        { text: '学习路径', link: '/rust/learning-path' },
        { text: '必备知识总览', link: '/rust/essential-knowledge' },
        { text: '能力自检导航', link: '/rust/interview-prep' },
        { text: '必备问题清单', link: '/rust/essential-questions' },
        { text: '高频代码片段', link: '/rust/interview-code-snippets' },
        { text: '所有权与生命周期', link: '/rust/ownership-borrowing-and-lifetimes' },
        { text: 'Borrow Checker 排障', link: '/rust/borrow-checker-troubleshooting-guide' },
        { text: 'CLI 工具实践', link: '/rust/cli-tool-practice' },
      ],
    },
    {
      text: '语言与工程',
      collapsed: true,
      items: [
        { text: '所有权与生命周期', link: '/rust/ownership-borrowing-and-lifetimes' },
        { text: 'Borrow Checker 排障', link: '/rust/borrow-checker-troubleshooting-guide' },
        { text: '集合、字符串与迭代器', link: '/rust/collections-strings-and-iterators' },
        { text: 'Trait 与泛型', link: '/rust/traits-generics-and-pattern-matching' },
        { text: '智能指针与内部可变性', link: '/rust/smart-pointers-and-interior-mutability' },
        { text: '错误处理与 Cargo', link: '/rust/error-handling-cargo-and-testing' },
        { text: '项目结构与 API 设计', link: '/rust/project-structure-and-api-design' },
        { text: 'DTO / 领域模型分层', link: '/rust/dto-domain-and-persistence-model-practice' },
        { text: '输入校验与边界建模', link: '/rust/validation-and-input-boundaries-practice' },
        { text: 'crate 选型与边界', link: '/rust/crate-selection-and-boundaries' },
        { text: 'CLI 工具实践', link: '/rust/cli-tool-practice' },
        { text: '配置管理实践', link: '/rust/configuration-management-practice' },
        { text: 'Workspace 与 Monorepo', link: '/rust/workspace-and-monorepo-practice' },
      ],
    },
    {
      text: '并发与 Async',
      collapsed: true,
      items: [
        { text: '并发与 Async 基础', link: '/rust/concurrency-and-async' },
        { text: 'Tokio 与 Async 工程实践', link: '/rust/tokio-and-async-practice' },
        { text: 'HTTP Client 与外部 API', link: '/rust/http-client-and-external-api-practice' },
        { text: '后台任务与 Worker', link: '/rust/background-jobs-and-worker-practice' },
        { text: '定时任务、调度与 Leader Election', link: '/rust/scheduler-and-leader-election-practice' },
        { text: '缓存与 Redis 实践', link: '/rust/cache-and-redis-practice' },
      ],
    },
    {
      text: '服务与数据库',
      collapsed: true,
      items: [
        { text: 'Axum Web 服务实践', link: '/rust/axum-web-service-practice' },
        { text: '限流、超时与负载保护', link: '/rust/rate-limit-timeout-and-overload-protection-practice' },
        { text: 'API 错误响应与响应体设计', link: '/rust/api-error-and-response-design-practice' },
        { text: 'API Versioning、兼容演进与弃用治理', link: '/rust/api-versioning-and-compatibility-governance-practice' },
        { text: '列表查询、过滤、排序与分页', link: '/rust/pagination-filter-and-sorting-practice' },
        { text: '搜索、索引与检索', link: '/rust/search-index-and-retrieval-practice' },
        { text: '软删除、恢复与删除语义', link: '/rust/soft-delete-restore-and-deletion-semantics-practice' },
        { text: '批处理、回填与历史数据修复', link: '/rust/batch-processing-backfill-and-historical-repair-practice' },
        { text: '幂等、状态机与 Outbox', link: '/rust/idempotency-state-machine-and-outbox-practice' },
        { text: '消息队列与事件驱动', link: '/rust/message-queue-and-event-driven-practice' },
        { text: '通知、邮件、短信与消息触达', link: '/rust/notification-email-sms-and-delivery-practice' },
        { text: '文件上传、对象存储与 S3', link: '/rust/file-upload-and-object-storage-practice' },
        { text: '认证与请求上下文', link: '/rust/auth-authorization-and-request-context-practice' },
        { text: 'Secrets、密钥与凭证轮换', link: '/rust/secret-management-and-credential-rotation-practice' },
        { text: '数据脱敏、隐私字段与日志安全', link: '/rust/data-masking-privacy-and-log-safety-practice' },
        { text: 'Feature Flag、运行时开关与灰度治理', link: '/rust/feature-flag-and-runtime-governance-practice' },
        { text: '多租户与数据隔离', link: '/rust/multi-tenant-and-data-isolation-practice' },
        { text: '审计日志与操作记录', link: '/rust/audit-log-and-operation-history-practice' },
        { text: 'Webhook、回调与签名校验', link: '/rust/webhook-and-callback-practice' },
        { text: 'WebSocket 与 SSE', link: '/rust/websocket-and-sse-practice' },
        { text: 'SQLx 数据库访问实践', link: '/rust/sqlx-database-practice' },
        { text: '事务、锁与并发更新', link: '/rust/transaction-locking-and-concurrent-update-practice' },
        { text: '数据库迁移与 Schema 演进', link: '/rust/database-migration-and-schema-evolution-practice' },
        { text: '导出、报表与大结果集', link: '/rust/export-report-and-large-result-practice' },
        { text: '数据归档、保留策略与冷热分层', link: '/rust/data-archiving-retention-and-hot-cold-tiering-practice' },
        { text: 'Axum + SQLx 服务落地模板', link: '/rust/axum-sqlx-service-template' },
        { text: 'Tracing 与可观测性', link: '/rust/tracing-and-observability-practice' },
        { text: 'Metrics 与 OpenTelemetry', link: '/rust/metrics-and-opentelemetry-practice' },
        { text: '性能分析与 Profiling', link: '/rust/performance-and-profiling-guide' },
        { text: '配置与优雅关闭', link: '/rust/service-configuration-and-graceful-shutdown' },
        { text: '后端项目骨架', link: '/rust/backend-project-skeleton' },
        { text: '部署与发布清单', link: '/rust/deployment-and-release-checklist' },
      ],
    },
    {
      text: '进阶专题',
      collapsed: true,
      items: [
        { text: 'Serde 与数据序列化', link: '/rust/serde-and-data-serialization' },
        { text: '宏与元编程', link: '/rust/macros-and-metaprogramming' },
        { text: 'Unsafe 与 FFI 边界', link: '/rust/unsafe-and-ffi-boundaries' },
        { text: '测试与质量实践', link: '/rust/testing-and-quality-practice' },
        { text: '测试替身与依赖隔离', link: '/rust/test-doubles-and-dependency-isolation-practice' },
      ],
    },
  ],
}
