export interface LandingLink {
  title: string
  href: string
  description: string
}

export interface SectionLandingContent {
  eyebrow: string
  title: string
  intro: string
  primary: LandingLink
  secondary?: LandingLink
  scope: string[]
  docs: LandingLink[]
  order: string[]
}

interface Items {
  text: string; 
  link: string;
  items?: Items[];
}

export interface SidebarGroup {
  text: string
  collapsed?: boolean
  items: Items[]
}

export interface SectionConfig {
  key: string
  base: string
  navText: string
  overviewDescription: string
  landing: SectionLandingContent
  sidebar: SidebarGroup[]
}

export const quickNavLink = { text: '快速导航', link: '/nav' }

const golangSourceReadingSidebar: SidebarGroup[] = [
  {
    text: '先读这几篇',
    items: [
      { text: 'runtime：GMP 调度器', link: '/golang/guide/source-reading/runtime-scheduler' },
      { text: 'runtime：GC 垃圾回收', link: '/golang/guide/source-reading/runtime-gc' },
      { text: 'channel：底层实现', link: '/golang/guide/source-reading/channel' },
      { text: 'map：Swiss Table', link: '/golang/guide/source-reading/map' },
      { text: 'net/http：HTTP 实现', link: '/golang/guide/source-reading/net-http' },
      { text: 'database/sql：连接池', link: '/golang/guide/source-reading/database-sql' },
    ],
  },
  {
    text: '运行时与并发',
    collapsed: true,
    items: [
      { text: 'sync：同步原语', link: '/golang/guide/source-reading/sync-primitives' },
      { text: 'sync/atomic：原子操作', link: '/golang/guide/source-reading/sync-atomic' },
      { text: 'sync.Pool：对象池', link: '/golang/guide/source-reading/sync-pool' },
      { text: 'sync.Cond：条件变量', link: '/golang/guide/source-reading/sync-cond' },
      { text: 'context：上下文传播', link: '/golang/guide/source-reading/context' },
      { text: 'channel：底层实现', link: '/golang/guide/source-reading/channel' },
      { text: 'map：Swiss Table', link: '/golang/guide/source-reading/map' },
      { text: 'goroutine：生命周期', link: '/golang/guide/source-reading/goroutine' },
      { text: 'timer：定时器实现', link: '/golang/guide/source-reading/timer' },
      { text: 'runtime：GMP 调度器', link: '/golang/guide/source-reading/runtime-scheduler' },
      { text: 'runtime：GC 垃圾回收', link: '/golang/guide/source-reading/runtime-gc' },
      { text: 'runtime：内存分配', link: '/golang/guide/source-reading/runtime-memory' },
      { text: 'runtime/debug：调试工具', link: '/golang/guide/source-reading/runtime-debug' },
      { text: 'runtime/pprof：性能剖析', link: '/golang/guide/source-reading/runtime-pprof' },
      { text: 'runtime/trace：执行追踪', link: '/golang/guide/source-reading/runtime-trace' },
      { text: 'runtime/metrics：运行时指标', link: '/golang/guide/source-reading/runtime-metrics' },
      { text: 'runtime.SetFinalizer：GC 终结器', link: '/golang/guide/source-reading/runtime-finalizer' },
      { text: 'go-memory-tuning：内存调优', link: '/golang/guide/source-reading/go-memory-tuning' },
    ],
  },
  {
    text: '标准库基础',
    collapsed: true,
    items: [
      { text: 'errors：错误链', link: '/golang/guide/source-reading/errors' },
      { text: 'strings/bytes：字符串处理', link: '/golang/guide/source-reading/strings-bytes' },
      { text: 'fmt：格式化 I/O', link: '/golang/guide/source-reading/fmt' },
      { text: 'strconv：字符串转换', link: '/golang/guide/source-reading/strconv' },
      { text: 'sort/slices：排序算法', link: '/golang/guide/source-reading/sort' },
      { text: 'math/rand：随机数生成（含 v2）', link: '/golang/guide/source-reading/math-rand' },
      { text: 'math/big：任意精度算术', link: '/golang/guide/source-reading/math-big' },
      { text: 'math/bits：位操作', link: '/golang/guide/source-reading/math-bits' },
      { text: 'time：时间处理', link: '/golang/guide/source-reading/time-pkg' },
      { text: 'unsafe：内存操作', link: '/golang/guide/source-reading/unsafe' },
      { text: 'reflect：反射原理', link: '/golang/guide/source-reading/reflect' },
      { text: 'iter（Go 1.23+）：迭代器协议', link: '/golang/guide/source-reading/iter-pkg' },
      { text: 'unique（Go 1.23+）：字符串驻留', link: '/golang/guide/source-reading/unique-pkg' },
      { text: 'slices/maps/cmp：泛型标准库', link: '/golang/guide/source-reading/slices-maps-cmp' },
    ],
  },
  {
    text: 'I/O、系统与网络',
    collapsed: true,
    items: [
      { text: 'io：接口体系', link: '/golang/guide/source-reading/io-interfaces' },
      { text: 'io 高级组合：TeeReader/Pipe', link: '/golang/guide/source-reading/io-advanced' },
      { text: 'bufio：缓冲 I/O 与 Scanner', link: '/golang/guide/source-reading/bufio' },
      { text: 'io/fs：文件系统抽象', link: '/golang/guide/source-reading/io-fs' },
      { text: 'os：文件与进程', link: '/golang/guide/source-reading/os' },
      { text: 'os/exec：命令执行', link: '/golang/guide/source-reading/os-exec' },
      { text: 'os/signal：信号处理', link: '/golang/guide/source-reading/os-signal' },
      { text: 'os/user：用户信息', link: '/golang/guide/source-reading/os-user' },
      { text: 'path/filepath：路径处理', link: '/golang/guide/source-reading/path-filepath' },
      { text: 'unicode/utf8：字符编码', link: '/golang/guide/source-reading/unicode-utf8' },
      { text: 'text/tabwriter：列对齐输出', link: '/golang/guide/source-reading/text-tabwriter' },
      { text: 'net：TCP/UDP 底层', link: '/golang/guide/source-reading/net' },
      { text: 'net/url：URL 解析', link: '/golang/guide/source-reading/net-url' },
      { text: 'net/http：HTTP 实现', link: '/golang/guide/source-reading/net-http' },
      { text: 'net/http 服务端高级模式', link: '/golang/guide/source-reading/net-http-server' },
      { text: 'net/http RESTful API 设计模式', link: '/golang/guide/source-reading/net-http-api' },
      { text: 'net/http Transport：连接池调优', link: '/golang/guide/source-reading/net-http-transport' },
      { text: 'net/http/httptrace：请求追踪', link: '/golang/guide/source-reading/net-http-trace' },
      { text: 'net/http/httptest：HTTP 测试', link: '/golang/guide/source-reading/net-http-test' },
      { text: 'net/http/httputil：反向代理', link: '/golang/guide/source-reading/net-httputil' },
      { text: 'net/http 限流与熔断', link: '/golang/guide/source-reading/net-http-ratelimit' },
      { text: 'HTTP/2：多路复用与 Server Push', link: '/golang/guide/source-reading/net-http2' },
      { text: 'net/http/cookiejar：Cookie 管理', link: '/golang/guide/source-reading/net-cookiejar' },
      { text: 'net/netip：现代 IP 地址', link: '/golang/guide/source-reading/net-netip' },
      { text: 'net/rpc：远程过程调用', link: '/golang/guide/source-reading/net-rpc' },
      { text: 'net/smtp：邮件发送', link: '/golang/guide/source-reading/net-smtp' },
      { text: 'mime/multipart：表单上传', link: '/golang/guide/source-reading/mime-multipart' },
      { text: '自定义 TCP 协议服务器', link: '/golang/guide/source-reading/net-tcp-server' },
      { text: 'WebSocket 服务器实现', link: '/golang/guide/source-reading/websocket' },
      { text: 'gRPC-Go：微服务通信', link: '/golang/guide/source-reading/grpc-go' },
      { text: 'Prometheus Go 客户端', link: '/golang/guide/source-reading/prometheus-go' },
      { text: 'OpenTelemetry Go：分布式追踪', link: '/golang/guide/source-reading/opentelemetry-go' },
      { text: 'golang.org/x/sync：并发工具包', link: '/golang/guide/source-reading/golang-x-sync' },
      { text: 'golang.org/x/oauth2：OAuth2 客户端', link: '/golang/guide/source-reading/golang-x-oauth2' },
      { text: 'go-redis：Redis 客户端', link: '/golang/guide/source-reading/go-redis' },
      { text: 'pgx：PostgreSQL 原生驱动', link: '/golang/guide/source-reading/pgx-driver' },
    ],
  },
  {
    text: '数据、编码与模板',
    collapsed: true,
    items: [
      { text: 'encoding/json：编解码', link: '/golang/guide/source-reading/encoding-json' },
      { text: 'encoding/xml：XML 编解码', link: '/golang/guide/source-reading/encoding-xml' },
      { text: 'encoding/csv：CSV 处理', link: '/golang/guide/source-reading/encoding-csv' },
      { text: 'encoding/gob：Go 原生序列化', link: '/golang/guide/source-reading/encoding-gob' },
      { text: 'encoding/base64：Base64 编码', link: '/golang/guide/source-reading/encoding-base64' },
      { text: 'encoding/hex：十六进制编解码', link: '/golang/guide/source-reading/encoding-hex' },
      { text: 'encoding/binary：字节序与协议', link: '/golang/guide/source-reading/encoding-binary' },
      { text: 'compress/gzip：流式压缩', link: '/golang/guide/source-reading/compress-gzip' },
      { text: 'archive/zip：ZIP 归档', link: '/golang/guide/source-reading/archive-zip' },
      { text: 'archive/tar：TAR 归档', link: '/golang/guide/source-reading/archive-tar' },
      { text: 'regexp：正则引擎', link: '/golang/guide/source-reading/regexp' },
      { text: 'container/heap：优先队列', link: '/golang/guide/source-reading/container-heap' },
      { text: 'container/list：双向链表', link: '/golang/guide/source-reading/container-list' },
      { text: 'text/template：模板引擎', link: '/golang/guide/source-reading/text-template' },
      { text: 'html/template：安全模板引擎', link: '/golang/guide/source-reading/html-template' },
      { text: 'database/sql：连接池', link: '/golang/guide/source-reading/database-sql' },
      { text: 'database/sql：高级事务与批量插入', link: '/golang/guide/source-reading/database-sql-advanced' },
    ],
  },
  {
    text: '安全与密码学',
    collapsed: true,
    items: [
      { text: 'crypto/tls：TLS 实现', link: '/golang/guide/source-reading/crypto-tls' },
      { text: 'crypto/x509：证书与 PKI', link: '/golang/guide/source-reading/crypto-x509' },
      { text: 'crypto/aes：对称加密', link: '/golang/guide/source-reading/crypto-aes' },
      { text: 'crypto/cipher：分组密码模式', link: '/golang/guide/source-reading/crypto-cipher' },
      { text: 'crypto/rand：密码学随机数', link: '/golang/guide/source-reading/crypto-rand' },
      { text: 'crypto/hmac：哈希与消息认证', link: '/golang/guide/source-reading/crypto-hmac' },
      { text: 'crypto/sha256：hash 接口体系', link: '/golang/guide/source-reading/crypto-sha' },
      { text: 'crypto/rsa：RSA 非对称加密', link: '/golang/guide/source-reading/crypto-rsa' },
      { text: 'crypto/ecdsa：椭圆曲线签名', link: '/golang/guide/source-reading/crypto-ecdsa' },
      { text: 'crypto/ed25519：EdDSA 签名', link: '/golang/guide/source-reading/crypto-ed25519' },
      { text: '密码散列：bcrypt/Argon2id/scrypt', link: '/golang/guide/source-reading/crypto-password' },
      { text: 'hash/crc32：校验和', link: '/golang/guide/source-reading/hash-crc32' },
    ],
  },
  {
    text: '工程实践与工具链',
    collapsed: true,
    items: [
      { text: 'log/slog：结构化日志', link: '/golang/guide/source-reading/log-slog' },
      { text: 'zap：高性能日志库', link: '/golang/guide/source-reading/zap' },
      { text: 'log：标准日志库', link: '/golang/guide/source-reading/log-pkg' },
      { text: 'testing：测试框架与高级模式', link: '/golang/guide/source-reading/testing' },
      { text: 'testing/fstest：虚拟文件系统测试', link: '/golang/guide/source-reading/testing-fstest' },
      { text: 'testing/fuzzing：模糊测试', link: '/golang/guide/source-reading/go-fuzzing' },
      { text: 'go:generate 代码生成工具链', link: '/golang/guide/source-reading/go-generate' },
      { text: 'go/format：代码格式化', link: '/golang/guide/source-reading/go-format' },
      { text: 'go/ast + go/parser：AST 解析', link: '/golang/guide/source-reading/go-ast' },
      { text: 'go/types：类型检查器', link: '/golang/guide/source-reading/go-types' },
      { text: 'go/analysis：自定义 Linter', link: '/golang/guide/source-reading/go-analysis' },
      { text: 'embed：静态资源嵌入', link: '/golang/guide/source-reading/embed' },
      { text: 'flag：命令行解析', link: '/golang/guide/source-reading/flag' },
      { text: 'expvar：可导出变量', link: '/golang/guide/source-reading/expvar' },
      { text: 'debug/buildinfo：构建信息', link: '/golang/guide/source-reading/debug-buildinfo' },
      { text: 'cgo：C/Go 互操作', link: '/golang/guide/source-reading/cgo-basics' },
      { text: 'cobra+viper：CLI 工具框架', link: '/golang/guide/source-reading/cobra-viper' },
      { text: 'wire：编译期依赖注入', link: '/golang/guide/source-reading/wire' },
      { text: 'golang.org/x/text：Unicode 文本', link: '/golang/guide/source-reading/golang-x-text' },
    ],
  },
]

export const sections: SectionConfig[] = [
  {
    key: 'ai',
    base: '/ai/',
    navText: 'AI / Agent',
    overviewDescription:
      '适合希望系统入门 Agent 和 LLM 应用开发的工程师，重点是 Agent、Tool Calling、RAG 与 workflow。',
    landing: {
      eyebrow: 'AI / Agent',
      title: 'AI / Agent 方向',
      intro:
        '从 Agent 模式、Tool Calling、RAG 到 workflow 设计，把零散资料收敛成一条更适合工程师持续推进的学习路径。',
      primary: { title: '知识地图', href: '/ai/knowledge-map', description: '先建立全局地图。' },
      secondary: { title: '综合指南', href: '/ai/agent-learning-guide', description: '再进入系统学习。' },
      scope: [
        'Agent 开发',
        'Tool Calling',
        'Workflow 与状态机',
        'RAG 与知识库',
        'Eval、安全、观测',
        'LLM 基础与学习路径',
      ],
      docs: [
        { title: 'LLM Agent 必学知识地图', href: '/ai/knowledge-map', description: '先搭整体认知框架，明确主题之间的关系。' },
        { title: 'Agent 学习综合指南', href: '/ai/agent-learning-guide', description: '用一篇长文把核心概念、资料和实践建议串起来。' },
        { title: '7 天 Agent 学习路线', href: '/ai/agent-learning-roadmap', description: '适合短周期起步，先把路径跑通。' },
        { title: 'Tool Calling 设计清单', href: '/ai/tool-calling-design-checklist', description: '关注接口设计、容错和运行边界。' },
        { title: 'RAG 基础与工作流', href: '/ai/rag-basics-and-workflow', description: '把检索、切分、召回和生成串成一个可理解的流程。' },
        { title: '待补主题清单', href: '/ai/todo-topics', description: '查看还未展开的补充主题。' },
      ],
      order: [
        'LLM Agent 必学知识地图',
        'Agent 学习综合指南',
        '7 天 Agent 学习路线',
        'Tool Calling 设计清单',
        'RAG 基础与工作流',
      ],
    },
    sidebar: [
      {
        text: 'AI / Agent',
        items: [
          { text: '方向概览', link: '/ai/' },
          { text: 'Agent 学习综合指南', link: '/ai/agent-learning-guide' },
          { text: '7 天 Agent 学习路线', link: '/ai/agent-learning-roadmap' },
          { text: 'Tool Calling 设计清单', link: '/ai/tool-calling-design-checklist' },
          { text: 'RAG 基础与工作流', link: '/ai/rag-basics-and-workflow' },
          { text: '待补主题清单', link: '/ai/todo-topics' },
        ],
      },
      {
        text: '7 天学习路线详解',
        collapsed: true,
        items: [
          { text: 'Day 1: 理解 Agent 是什么', link: '/ai/roadmap/day1-what-is-agent' },
          { text: 'Day 2: 学会调用 LLM API', link: '/ai/roadmap/day2-llm-api' },
          { text: 'Day 3: 学会 Tool Calling', link: '/ai/roadmap/day3-tool-calling' },
          { text: 'Day 4: 学习 Workflow', link: '/ai/roadmap/day4-workflow' },
          { text: 'Day 5: RAG 和 Memory', link: '/ai/roadmap/day5-rag-memory' },
          { text: 'Day 6: 评测与安全', link: '/ai/roadmap/day6-eval-safety' },
          { text: 'Day 7: 完整项目', link: '/ai/roadmap/day7-full-project' },
        ],
      },
    ],
  },
  {
    key: 'architecture',
    base: '/architecture/',
    navText: '架构',
    overviewDescription:
      '适合后端开发、技术负责人候选人和架构岗准备，主线是系统设计、治理和分布式能力。',
    landing: {
      eyebrow: 'Architecture',
      title: '架构方向',
      intro:
        '围绕系统设计、高并发、分布式事务与治理方法，把架构学习整理成适合长期复用的框架、清单和路线。',
      primary: { title: '学习路线', href: '/architecture/architect-learning-roadmap', description: '先搭主线。' },
      secondary: { title: '能力自检', href: '/architecture/architect-interview-prep-checklist', description: '再用清单校验。' },
      scope: [
        '系统设计',
        '核心基础',
        '分布式系统',
        '微服务与中间件',
        '数据架构',
        '云原生与 DevOps',
        '高可用与稳定性治理',
        '架构方法论与技术规划',
        '案例实战',
        'MySQL 深入学习',
      ],
      docs: [
        { title: '架构师学习路线', href: '/architecture/architect-learning-roadmap', description: '适合作为主入口，先看清楚各阶段该补什么。' },
        { title: '架构师分阶段书单', href: '/architecture/architect-booklist-by-level', description: '按成长阶段筛选更合适的资料。' },
        { title: '架构能力自检准备清单', href: '/architecture/architect-interview-prep-checklist', description: '用判断项梳理系统设计和架构治理能力。' },
        { title: '高并发系统设计清单', href: '/architecture/high-concurrency-system-checklist', description: '把常见高并发设计问题拆成一组可检查项。' },
        { title: '大促活动预热、压测与开关治理手册', href: '/architecture/promotion-readiness-pressure-test-and-switch-governance', description: '围绕容量估算、资源预热、全链路压测、灰度放量、开关矩阵与应急值守，讲清大促活动保障主线。' },
        { title: '秒杀系统压测脚本、容量估算与演练方法论', href: '/architecture/seckill-pressure-testing-capacity-estimation-and-drills', description: '围绕流量模型、容量估算、压测脚本、影子流量、故障注入与演练回写，讲清秒杀系统压测与容量验证主线。' },
        { title: '活动复盘模板与容量回归手册', href: '/architecture/activity-postmortem-and-capacity-regression-playbook', description: '围绕事实时间线、指标对比、容量回归、阈值修正、预案更新与责任闭环，讲清高峰活动后的复盘与资产沉淀主线。' },
        { title: '营销活动平台设计：模板、规则、发放、核销的一体化架构', href: '/architecture/marketing-activity-platform-architecture', description: '围绕活动模板、规则引擎、发放中心、券资产、核销链路、风控审计与平台治理，讲清营销活动平台的一体化架构主线。' },
        { title: '交易系统一致性设计总览', href: '/architecture/transaction-system-consistency-overview', description: '把订单、库存、支付、延时任务、Outbox 与补偿主线收成一张统一的交易一致性地图。' },
        { title: '订单超时取消与时间轮设计', href: '/architecture/order-timeout-cancellation-and-timing-wheel', description: '从 30 分钟未支付自动取消切入，串起延时消息、时间轮、状态机幂等与补偿兜底。' },
        { title: '订单状态机设计实战', href: '/architecture/order-state-machine-design', description: '围绕支付、取消、退款等链路，讲清状态机设计、条件更新、幂等与并发竞争。' },
        { title: '延时任务方案对比', href: '/architecture/delayed-task-solution-comparison', description: '系统对比 RocketMQ、RabbitMQ、Redis ZSet、时间轮等延时任务方案的边界与取舍。' },
        { title: 'Outbox 本地消息表设计实战', href: '/architecture/outbox-pattern-design', description: '围绕写库与发消息的一致性问题，讲清 Outbox 的流程、表设计、重试与幂等。' },
        { title: '库存扣减与订单创建一致性设计', href: '/architecture/order-and-inventory-consistency-design', description: '围绕超卖防护、库存冻结、Outbox 与补偿恢复，讲清订单与库存的一致性设计。' },
        { title: '秒杀系统库存设计专题', href: '/architecture/seckill-system-inventory-design', description: '围绕资格过滤、Redis 预扣减、异步下单、热点库存和回补补偿，讲清秒杀系统库存设计主线。' },
        { title: '秒杀系统限流、削峰与降级设计', href: '/architecture/seckill-system-rate-limiting-and-degradation', description: '围绕活动预热、资格令牌、多层限流、排队削峰、背压与降级策略，讲清秒杀系统稳定性设计主线。' },
        { title: '秒杀系统风控、防刷与资格校验设计', href: '/architecture/seckill-risk-control-and-eligibility-design', description: '围绕活动资格、抢购 Token、黑白名单、行为识别与误杀恢复，讲清秒杀系统入口治理主线。' },
        { title: '秒杀结果查询、排队态与用户体验设计', href: '/architecture/seckill-result-query-and-queueing-ux-design', description: '围绕排队态设计、结果查询接口、轮询与推送取舍、失败提示和状态收敛，讲清秒杀活动的用户体验主线。' },
        { title: '秒杀系统监控、告警与应急响应设计', href: '/architecture/seckill-monitoring-alerting-and-incident-response', description: '围绕指标分层、告警分级、链路追踪、值守大盘、止血动作与复盘回写，讲清秒杀系统监控与应急治理主线。' },
        { title: '抢券系统设计专题：与秒杀系统的异同', href: '/architecture/coupon-claim-system-design-and-comparison', description: '围绕券模板、领券资格、库存配额、异步发券、核销状态与用户限领，讲清抢券系统设计主线和它与秒杀系统的差异。' },
        { title: '支付系统回调幂等与补偿设计', href: '/architecture/payment-callback-idempotency-and-compensation', description: '围绕签名校验、状态机收口、主动查询与对账补偿，讲清支付回调的一致性设计。' },
        { title: '分布式事务方案对比', href: '/architecture/distributed-transaction-comparison', description: '快速对比常见事务方案的边界与取舍。' },
        { title: 'PostgreSQL 高可用集群整理', href: '/postgresql/ha-cluster', description: 'PG 高可用方案选型、Patroni 部署、WAL 流复制与故障恢复速查。' },
        { title: '架构案例实战', href: '/architecture/case-studies/', description: '收录偏业务落地的组织设计、PostgreSQL 高可用、支付系统与出海架构案例。' },
        { title: '待补主题清单', href: '/architecture/todo-topics', description: '查看后续计划补充的专题。' },
      ],
      order: [
        '架构师学习路线',
        '架构师分阶段书单',
        '大促活动预热、压测与开关治理手册',
        '秒杀系统压测脚本、容量估算与演练方法论',
        '活动复盘模板与容量回归手册',
        '营销活动平台设计：模板、规则、发放、核销的一体化架构',
        '交易系统一致性设计总览',
        '订单超时取消与时间轮设计',
        '订单状态机设计实战',
        '延时任务方案对比',
        'Outbox 本地消息表设计实战',
        '库存扣减与订单创建一致性设计',
        '秒杀系统库存设计专题',
        '秒杀系统限流、削峰与降级设计',
        '秒杀系统风控、防刷与资格校验设计',
        '秒杀结果查询、排队态与用户体验设计',
        '秒杀系统监控、告警与应急响应设计',
        '抢券系统设计专题：与秒杀系统的异同',
        '支付系统回调幂等与补偿设计',
        '高并发系统设计清单',
        '分布式事务方案对比',
        '架构能力自检准备清单',
        'PostgreSQL 高可用集群整理',
        '架构案例实战',
      ],
    },
    sidebar: [
      {
        text: '架构主线',
        items: [
          { text: '方向概览', link: '/architecture/' },
          { text: '架构师学习路线', link: '/architecture/architect-learning-roadmap' },
          { text: '架构师分阶段书单', link: '/architecture/architect-booklist-by-level' },
          { text: '交易系统一致性设计总览', link: '/architecture/transaction-system-consistency-overview' },
          { text: '大促活动预热、压测与开关治理手册', link: '/architecture/promotion-readiness-pressure-test-and-switch-governance' },
          { text: '秒杀系统压测脚本、容量估算与演练方法论', link: '/architecture/seckill-pressure-testing-capacity-estimation-and-drills' },
          { text: '活动复盘模板与容量回归手册', link: '/architecture/activity-postmortem-and-capacity-regression-playbook' },
          { text: '营销活动平台设计：模板、规则、发放、核销的一体化架构', link: '/architecture/marketing-activity-platform-architecture' },
          { text: '架构能力自检准备清单', link: '/architecture/architect-interview-prep-checklist' },
          { text: '高并发系统设计清单', link: '/architecture/high-concurrency-system-checklist' },
          { text: '订单超时取消与时间轮设计', link: '/architecture/order-timeout-cancellation-and-timing-wheel' },
          { text: '订单状态机设计实战', link: '/architecture/order-state-machine-design' },
          { text: '延时任务方案对比', link: '/architecture/delayed-task-solution-comparison' },
          { text: 'Outbox 本地消息表设计实战', link: '/architecture/outbox-pattern-design' },
          { text: '库存扣减与订单创建一致性设计', link: '/architecture/order-and-inventory-consistency-design' },
          { text: '秒杀系统库存设计专题', link: '/architecture/seckill-system-inventory-design' },
          { text: '秒杀系统限流、削峰与降级设计', link: '/architecture/seckill-system-rate-limiting-and-degradation' },
          { text: '秒杀系统风控、防刷与资格校验设计', link: '/architecture/seckill-risk-control-and-eligibility-design' },
          { text: '秒杀结果查询、排队态与用户体验设计', link: '/architecture/seckill-result-query-and-queueing-ux-design' },
          { text: '秒杀系统监控、告警与应急响应设计', link: '/architecture/seckill-monitoring-alerting-and-incident-response' },
          { text: '抢券系统设计专题：与秒杀系统的异同', link: '/architecture/coupon-claim-system-design-and-comparison' },
          { text: '支付系统回调幂等与补偿设计', link: '/architecture/payment-callback-idempotency-and-compensation' },
          { text: '分布式事务方案对比', link: '/architecture/distributed-transaction-comparison' },
          { text: '待补主题清单', link: '/architecture/todo-topics' },
        ],
      },
      {
        text: '案例实战',
        items: [
          { text: '案例概览', link: '/architecture/case-studies/' },
          { text: '组织架构与业务系统设计方案', link: '/architecture/case-studies/organization-structure-and-business-system-design' },
          { text: '高并发支付系统专题整理', link: '/architecture/case-studies/high-concurrency-payment-system-practice-notes' },
          { text: '运动 APP 出海架构与管理完全指南', link: '/architecture/case-studies/global-fitness-app-architecture-and-management-guide' },
        ],
      },
    ],
  },
  {
    key: 'golang',
    base: '/golang/',
    navText: 'Golang',
    overviewDescription:
      '适合 Go 后端和高级开发，重点覆盖语言机制、并发、性能、工程实践与源码精读主线。',
    landing: {
      eyebrow: 'Golang',
      title: 'Golang 方向',
      intro:
        '从语言机制、并发与性能，到服务端工程实践、能力自检和源码精读，把 Go 进阶学习整理成一套统一入口。',
      primary: { title: '源码精读主线', href: '/golang/guide/source-reading/learning-path', description: '先走源码阅读主线。' },
      secondary: { title: '能力自检', href: '/golang/interview-prep', description: '再做题库和专题回查。' },
      scope: ['Go 语言底层', '并发模型', '性能优化与排障', '服务端工程实践', '能力自检准备', '设计模式与安全', '容器化与云原生', '代码生成与元编程', '标准库源码精读', 'runtime 源码分析'],
      docs: [
        { title: 'Go 文档导航', href: '/golang/', description: '先看目录结构，再决定走学习主线、源码主线还是自检入口。' },
        { title: 'Go 学习路径与资料导航', href: '/golang/learning-path', description: 'Go 总体专题导航，负责串联各阶段专题与练习入口。' },
        { title: 'Go 源码阅读学习主线', href: '/golang/guide/source-reading/learning-path', description: '统一维护源码阅读路线、方法、runtime 导读与推荐资料。' },
        { title: 'Go 源码精读总览', href: '/golang/guide/source-reading/', description: '按 runtime、网络、编码、工程化等主题浏览源码文章。' },
        { title: 'Go 能力自检与面试准备导航', href: '/golang/interview-prep', description: '统一整理题库、代码片段与专题回查入口。' },
        { title: 'database/sql 与连接池', href: '/golang/guide/06-database-sql-and-connection', description: 'Go 标准库数据库访问与连接池配置的实战入口。' },
        { title: '30+ 高频 Golang 能力自检题', href: '/golang/go-top-30-interview-questions', description: '用问题驱动回顾知识盲区和底层理解。' },
        { title: 'Golang 高频题代码片段', href: '/golang/go-interview-code-snippets', description: '配套示例代码，方便把抽象概念落到实现。' },
        { title: 'Pprof 排障指南', href: '/golang/pprof-troubleshooting-guide', description: '针对性能定位和排障建立实操路径。' },
        { title: 'Context 使用边界', href: '/golang/context-usage-boundaries', description: '厘清在 Go 服务里使用 Context 的边界和误区。' },
      ],
      order: [
        'Go 文档导航',
        'Go 学习路径与资料导航',
        'Go 源码阅读学习主线',
        'Go 源码精读总览',
        'Go 能力自检与面试准备导航',
        'database/sql 与连接池',
        '30+ 高频 Golang 能力自检题',
        'Golang 高频题代码片段',
        'Pprof 排障指南',
        'Context 使用边界',
      ],
    },
    sidebar: [
      {
        text: '核心入口',
        items: [
          { text: '方向概览', link: '/golang/' },
          { text: '学习路径', link: '/golang/learning-path' },
          { text: '源码主线', link: '/golang/guide/source-reading/learning-path' },
          { text: '精读总览', link: '/golang/guide/source-reading/' },
          { text: '能力自检', link: '/golang/interview-prep' },
          { text: 'SQL 连接池', link: '/golang/guide/06-database-sql-and-connection' },
          { text: 'Pprof 排障', link: '/golang/pprof-troubleshooting-guide' },
          { text: 'Context 边界', link: '/golang/context-usage-boundaries' },
          { text: '版本特性', link: '/golang/go-version-features' },
          { text: '高频自检题', link: '/golang/go-top-30-interview-questions' },
          { text: '自检代码片段', link: '/golang/go-interview-code-snippets' },
        ],
      },
      {
        text: '学习大纲详解',
        collapsed: true,
        items: [
          {
            text: '一、语言基础',
            link: '/golang/guide/01-language-fundamentals',
            items: [
              { text: '变量与类型', link: '/golang/guide/01-variables-types-and-semantics' },
              { text: 'defer 与闭包', link: '/golang/guide/01-defer-panic-and-closures' },
              { text: '接口反射泛型', link: '/golang/guide/01-interface-reflect-generics' },
              { text: '错误处理', link: '/golang/guide/01-error-handling-design' },
              { text: 'Slice 陷阱', link: '/golang/guide/01-slice-append-pitfalls' },
              { text: '字符串转换', link: '/golang/guide/01-string-byte-best-practices' },
            ],
          },
          {
            text: '二、底层原理',
            link: '/golang/guide/02-underlying-principles',
            items: [
              { text: '容器底层实现', link: '/golang/guide/02-slice-map-channel-internals' },
              { text: '接口与逃逸', link: '/golang/guide/02-interface-escape-and-stack' },
              { text: 'GC 与内存模型', link: '/golang/guide/02-gc-allocator-and-memory-model' },
              { text: '逃逸分析', link: '/golang/guide/02-escape-analysis' },
              { text: '并发切片', link: '/golang/guide/02-concurrent-slice-patterns' },
            ],
          },
          {
            text: '三、并发编程',
            link: '/golang/guide/03-concurrency',
            items: [
              { text: '协程与调度', link: '/golang/guide/03-goroutine-and-scheduler' },
              { text: 'Channel 模式', link: '/golang/guide/03-channel-select-context' },
              { text: '同步原语', link: '/golang/guide/03-sync-primitives' },
              { text: '泄漏与竞态', link: '/golang/guide/03-goroutine-leak-and-data-race' },
              { text: '高级模式', link: '/golang/guide/03-advanced-concurrency-patterns' },
            ],
          },
          {
            text: '四、网络编程',
            link: '/golang/guide/04-network-stdlib',
            items: [
              { text: 'HTTP 与 TCP', link: '/golang/guide/04-http-server-client-tcp-udp' },
              { text: '超时重试限流', link: '/golang/guide/04-connection-timeout-retry-rate-limit' },
              { text: '中间件与 IO', link: '/golang/guide/04-middleware-json-io' },
            ],
          },
          {
            text: '五、工程实践',
            link: '/golang/guide/05-engineering-practices',
            items: [
              { text: '结构与配置', link: '/golang/guide/05-project-layout-deps-logging-config' },
              { text: '规范与错误码', link: '/golang/guide/05-error-middleware-code-style' },
              { text: '测试与 CI', link: '/golang/guide/05-testing-benchmark-cicd' },
            ],
          },
          {
            text: '六、数据与缓存',
            link: '/golang/guide/06-database-cache',
            items: [
              { text: 'Redis 缓存', link: '/redis/redis-and-cache-patterns' },
              { text: '一致性分表', link: '/golang/guide/06-cache-consistency-and-sharding' },
              { text: 'SQL 连接池', link: '/golang/guide/06-database-sql-and-connection' },
            ],
          },
          {
            text: '七、性能排障',
            link: '/golang/guide/07-performance-troubleshooting',
            items: [
              { text: '性能采集', link: '/golang/guide/07-pprof-trace-and-benchmark' },
              { text: 'GC 与内存', link: '/golang/guide/07-gc-tuning-and-memory-optimization' },
              { text: '锁与慢请求', link: '/golang/guide/07-lock-contention-and-slow-requests' },
              { text: '泄漏与定位', link: '/golang/guide/07-goroutine-leak-and-production-debugging' },
            ],
          },
          {
            text: '八、微服务架构',
            link: '/golang/guide/08-microservices-distributed',
            items: [
              { text: 'RPC 与发现', link: '/golang/guide/08-rpc-discovery-config' },
              { text: '容错与追踪', link: '/golang/guide/08-observability-resilience' },
              { text: '高并发系统设计', link: '/golang/guide/08-go-high-concurrency-system-design' },
              { text: 'MQ 与高可用', link: '/golang/guide/08-mq-transaction-governance-ha' },
            ],
          },
          { text: '九、源码阅读', link: '/golang/guide/source-reading/learning-path' },
          {
            text: '十、进阶专题',
            link: '/golang/guide/10-advanced-topics',
            items: [
              { text: '设计模式', link: '/golang/guide/10-design-patterns-idioms' },
              { text: '安全编程', link: '/golang/guide/10-security-practices' },
              { text: '容器云原生', link: '/golang/guide/10-containerization-cloud-native' },
              { text: '代码生成', link: '/golang/guide/10-codegen-metaprogramming' },
            ],
          },
        ],
      },
      ...golangSourceReadingSidebar,
    ],
  },
  {
    key: 'rust',
    base: '/rust/',
    navText: 'Rust',
    overviewDescription:
      '适合希望系统掌握 Rust 语言基础、所有权模型、类型系统、错误处理、Cargo 工程化与并发 async 的工程师。',
    landing: {
      eyebrow: 'Rust',
      title: 'Rust 方向',
      intro:
        '从所有权模型、类型系统与错误处理，到 Cargo 工程化、测试和并发 async，把 Rust 入门到能写出可靠代码的必备知识串成一条清晰路径。',
      primary: { title: 'Rust 学习路径', href: '/rust/learning-path', description: '先按阶段看整体主线。' },
      secondary: { title: 'Rust 必备知识总览', href: '/rust/essential-knowledge', description: '再建立整体知识地图。' },
      scope: [
        '所有权与借用',
        'Borrow Checker 排障',
        '生命周期',
        'struct / enum / match',
        'trait / 泛型',
        'DTO / 领域模型分层',
        '输入校验 / 边界建模',
        '错误处理',
        'Cargo / 测试 / 工程化',
        'crate 选型与边界',
        'CLI 工具实践',
        '配置管理',
        'Workspace 与 Monorepo',
        'HTTP client / 外部 API',
        '后台任务与 Worker',
        '定时任务 / 调度 / Leader Election',
        '缓存 / Redis',
        '集合与字符串处理',
        '智能指针与内部可变性',
        '线程并发与 async 基础',
        'Tokio async 工程实践',
        'Axum Web 服务实践',
        '限流 / 超时 / 负载保护',
        'API 错误响应 / 响应体设计',
        'API Versioning / 兼容 / 弃用治理',
        '过滤 / 排序 / 分页',
        '搜索 / 索引 / 检索',
        '批处理 / 回填 / 历史数据修复',
        '幂等 / 状态机 / Outbox',
        '消息队列 / 事件驱动',
        '文件上传 / 对象存储 / S3',
        '认证 / 请求上下文',
        'Secrets / 密钥 / 凭证轮换',
        '数据脱敏 / 隐私字段 / 日志安全',
        'Feature Flag / 运行时开关 / 灰度治理',
        '多租户 / 数据隔离',
        '审计日志 / 操作记录',
        'Webhook / 回调 / 签名校验',
        'WebSocket / SSE',
        'SQLx 数据库访问实践',
        '事务 / 锁 / 并发更新',
        '数据库迁移 / Schema 演进',
        '导出 / 报表 / 大结果集',
        'Axum + SQLx 服务落地模板',
        'Tracing 与可观测性',
        'Metrics / OpenTelemetry',
        '性能分析与 Profiling',
        '配置与优雅关闭',
        '后端项目骨架',
        '部署与发布清单',
        'Serde 与数据序列化',
        '宏与元编程',
        'Unsafe / FFI 边界',
        '测试替身与依赖隔离',
        '能力自检与面试准备',
        '面试代码片段',
      ],
      docs: [
        { title: 'Rust 学习路径与资料导航', href: '/rust/learning-path', description: '把 Rust 核心主题按阶段串成一条学习主线。' },
        { title: 'Rust 必备知识总览', href: '/rust/essential-knowledge', description: '先建立 Rust 的主线认知，明确先学什么、后学什么。' },
        { title: 'Rust 能力自检与面试准备导航', href: '/rust/interview-prep', description: '把问题清单、学习主线和专题回查入口收敛到一页。' },
        { title: 'Rust 必备问题清单', href: '/rust/essential-questions', description: '按由浅入深整理 30 个最常用来检验理解深度的问题。' },
        { title: 'Rust 能力自检高频题示例代码片段', href: '/rust/interview-code-snippets', description: '用最小、可讲解、可手写的代码片段把所有权、迭代器、错误处理和 async 高频题落下来。' },
        { title: '所有权、借用与生命周期', href: '/rust/ownership-borrowing-and-lifetimes', description: '理解 move、借用规则、切片和生命周期约束。' },
        { title: 'Rust Borrow Checker 常见报错排障指南', href: '/rust/borrow-checker-troubleshooting-guide', description: '集中处理 moved value、借用冲突、生命周期不够长和 async 边界等高频编译报错。' },
        { title: '集合、字符串与迭代器', href: '/rust/collections-strings-and-iterators', description: '补齐 String、Vec、HashMap 和 iterator 的日常编码边界。' },
        { title: 'Trait、泛型与模式匹配', href: '/rust/traits-generics-and-pattern-matching', description: '把类型建模、行为抽象和通用逻辑复用放到一条线上理解。' },
        { title: '智能指针与内部可变性', href: '/rust/smart-pointers-and-interior-mutability', description: '理解 Box、Rc、Arc、RefCell、Mutex 等工具的职责边界。' },
        { title: '错误处理、Cargo 与测试', href: '/rust/error-handling-cargo-and-testing', description: '补齐 Result、工程结构、测试、格式化与 lint 的基础工作流。' },
        { title: '项目结构、crate 组织与 API 设计', href: '/rust/project-structure-and-api-design', description: '把模块、crate、workspace 和 API 边界放到工程视角下理解。' },
        { title: 'Rust DTO、领域模型与存储模型分层实践', href: '/rust/dto-domain-and-persistence-model-practice', description: '把请求 DTO、领域对象、数据库模型和外部 API DTO 的职责边界与映射方式收成一页。' },
        { title: 'Rust 输入校验与边界建模实践', href: '/rust/validation-and-input-boundaries-practice', description: '把 serde 解析、字段校验、领域不变量、axum 输入边界和错误映射收成一页。' },
        { title: 'Rust 常用 crate 选型与工程边界', href: '/rust/crate-selection-and-boundaries', description: '把 CLI、错误处理、序列化、async、HTTP、数据库和 tracing 这些高频依赖的选型思路、feature 控制和适用边界收成一页。' },
        { title: 'Rust CLI 工具实践', href: '/rust/cli-tool-practice', description: '把参数解析、配置加载、错误处理、文件 I/O、HTTP 调用和集成测试收成一条完整的小工具主线。' },
        { title: 'Rust 配置管理实践', href: '/rust/configuration-management-practice', description: '把默认值、文件、环境变量、命令行、校验和多来源合并收成一条清晰的配置主线。' },
        { title: 'Rust Workspace 与 Monorepo 实践', href: '/rust/workspace-and-monorepo-practice', description: '把多 crate 项目的拆分时机、workspace.dependencies、default-members、resolver 与依赖治理收成一页。' },
        { title: '并发与 Async 基础', href: '/rust/concurrency-and-async', description: '理解 Send/Sync、线程、共享状态和 async 的基本边界。' },
        { title: 'Tokio 与 Async 工程实践', href: '/rust/tokio-and-async-practice', description: '补 runtime、task、超时、取消和阻塞边界。' },
        { title: 'Rust HTTP Client 与外部 API 实践', href: '/rust/http-client-and-external-api-practice', description: '把 reqwest、timeout、认证、错误分层、重试、幂等和 tracing 这些外部调用边界收成一页。' },
        { title: 'Rust 后台任务与 Worker 实践', href: '/rust/background-jobs-and-worker-practice', description: '把进程内 task、定时任务、队列消费者、取消、背压、重试和幂等这些后台执行边界收成一页。' },
        { title: 'Rust 定时任务、调度与 Leader Election 实践', href: '/rust/scheduler-and-leader-election-practice', description: '把 interval / cron、补跑、单实例执行、租约选主、关闭交接和调度观测收成一页。' },
        { title: 'Rust 缓存与 Redis 实践', href: '/rust/cache-and-redis-practice', description: '把本地缓存、Redis、TTL、cache-aside、两级缓存和缓存击穿/雪崩这些读路径边界收成一页。' },
        { title: 'Axum Web 服务实践', href: '/rust/axum-web-service-practice', description: '围绕 Router、State、Extractor、Middleware 和错误边界梳理 Rust Web 服务主线。' },
        { title: 'Rust 限流、超时与负载保护实践', href: '/rust/rate-limit-timeout-and-overload-protection-practice', description: '把 timeout、并发限制、rate limit、load shed、buffer 和 backpressure 这些服务保护边界收成一页。' },
        { title: 'Rust API 错误响应与响应体设计实践', href: '/rust/api-error-and-response-design-practice', description: '把 IntoResponse、状态码分层、统一错误体、request id 透传和中间件错误收口成一套稳定 API 契约。' },
        { title: 'Rust API Versioning、兼容演进与弃用治理实践', href: '/rust/api-versioning-and-compatibility-governance-practice', description: '把路径与 header 版本策略、兼容新增、错误契约稳定性、弃用窗口和多版本观测收成一页。' },
        { title: 'Rust 列表查询、过滤、排序与分页实践', href: '/rust/pagination-filter-and-sorting-practice', description: '把 Query DTO、过滤条件、排序白名单、offset 与 cursor 分页、total 成本和索引约束收成一页。' },
        { title: 'Rust 搜索、索引与检索实践', href: '/rust/search-index-and-retrieval-practice', description: '把搜索 query DTO、索引文档、异步同步、回填重建和 alias 切换收成一页。' },
        { title: 'Rust 批处理、回填与历史数据修复实践', href: '/rust/batch-processing-backfill-and-historical-repair-practice', description: '把分批扫描、checkpoint、限速、dry-run、补跑和历史修复收成一页。' },
        { title: 'Rust 幂等、状态机与 Outbox 实践', href: '/rust/idempotency-state-machine-and-outbox-practice', description: '把请求级幂等键、业务唯一键、条件更新、状态机推进和 Outbox 一起收成有副作用操作的一致性主线。' },
        { title: 'Rust 消息队列与事件驱动实践', href: '/rust/message-queue-and-event-driven-practice', description: '把 producer、consumer、事件契约、至少一次投递、重试、死信、顺序性和幂等消费收成一条消息驱动主线。' },
        { title: 'Rust 文件上传、对象存储与 S3 实践', href: '/rust/file-upload-and-object-storage-practice', description: '把 multipart、流式上传、预签名 URL、对象 key、元数据落库、异步后处理和 orphan 清理收成一页。' },
        { title: 'Rust 认证、授权与请求上下文实践', href: '/rust/auth-authorization-and-request-context-practice', description: '把 middleware、extractor、route_layer、当前用户、request id 和服务授权边界收成一页。' },
        { title: 'Rust Secrets、密钥与凭证轮换实践', href: '/rust/secret-management-and-credential-rotation-practice', description: '把 secret 注入、JWK / webhook secret 轮换、对象存储凭证和外部 API token 脱敏收成一页。' },
        { title: 'Rust 数据脱敏、隐私字段与日志安全实践', href: '/rust/data-masking-privacy-and-log-safety-practice', description: '把 DTO 暴露、日志 / trace / audit 脱敏、导出和对象存储交付边界收成一页。' },
        { title: 'Rust Feature Flag、运行时开关与灰度治理实践', href: '/rust/feature-flag-and-runtime-governance-practice', description: '把静态配置和运行时开关分层、按租户和按比例灰度、kill switch、回退降级和治理收成一页。' },
        { title: 'Rust 多租户与数据隔离实践', href: '/rust/multi-tenant-and-data-isolation-practice', description: '把 tenant context、SQL 过滤、租户内唯一约束、缓存 key、对象 key、租户配额和观测边界收成一页。' },
        { title: 'Rust 审计日志与操作记录实践', href: '/rust/audit-log-and-operation-history-practice', description: '把 actor、tenant、resource、request id、trace id、脱敏和异步审计落库边界收成一页。' },
        { title: 'Rust Webhook、回调与签名校验实践', href: '/rust/webhook-and-callback-practice', description: '把原始 body 验签、重放防护、重复与乱序回调、2xx / 5xx 返回语义和异步解耦收成一页。' },
        { title: 'Rust WebSocket 与 SSE 实践', href: '/rust/websocket-and-sse-practice', description: '把 WebSocketUpgrade、SSE、broadcast/watch、慢消费者和长连接生命周期收成一页。' },
        { title: 'SQLx 数据库访问实践', href: '/rust/sqlx-database-practice', description: '补连接池、编译期 SQL 校验、事务、迁移和分层设计。' },
        { title: 'Rust 事务、锁与并发更新实践', href: '/rust/transaction-locking-and-concurrent-update-practice', description: '把事务边界、隔离级别、条件更新、乐观锁、FOR UPDATE 和锁冲突排障收成一页。' },
        { title: 'Rust 数据库迁移、Schema 演进与兼容发布实践', href: '/rust/database-migration-and-schema-evolution-practice', description: '把 expand / contract、回填、双读双写、索引变更和兼容发布边界收成一页。' },
        { title: 'Rust 导出、报表与大结果集实践', href: '/rust/export-report-and-large-result-practice', description: '把异步导出任务、批量扫描、对象存储交付、租户配额和审计留痕收成一页。' },
        { title: 'Axum + SQLx 服务落地模板', href: '/rust/axum-sqlx-service-template', description: '把目录结构、Cargo、启动顺序、State、Router、SQLx 和关闭流程收成一份可直接照着搭的模板。' },
        { title: 'Tracing 与可观测性实践', href: '/rust/tracing-and-observability-practice', description: '把 event、span、instrument、subscriber 和服务观测边界串起来。' },
        { title: 'Rust Metrics 与 OpenTelemetry 实践', href: '/rust/metrics-and-opentelemetry-practice', description: '把 counter、gauge、histogram、OTLP exporter、标签基数和指标闭环收成一页。' },
        { title: 'Rust 性能分析与 Profiling 指南', href: '/rust/performance-and-profiling-guide', description: '补 release 构建、bench、flamegraph、内存分配分析和 async 争用排障的实战主线。' },
        { title: '服务配置与优雅关闭', href: '/rust/service-configuration-and-graceful-shutdown', description: '补配置加载、启动校验、信号处理、任务协调和关闭流程。' },
        { title: 'Rust 后端项目骨架', href: '/rust/backend-project-skeleton', description: '把 axum、sqlx、tracing、配置和关闭流程收成一个可持续演进的服务骨架。' },
        { title: 'Rust 服务部署与发布清单', href: '/rust/deployment-and-release-checklist', description: '把镜像构建、配置注入、迁移、健康检查、资源、发布验证和回滚收成一页上线清单。' },
        { title: 'Serde 与数据序列化实践', href: '/rust/serde-and-data-serialization', description: '理解类型与外部协议、配置格式之间的映射和错误边界。' },
        { title: '宏与元编程基础', href: '/rust/macros-and-metaprogramming', description: '理清声明宏、过程宏和普通抽象手段的边界。' },
        { title: 'Unsafe 与 FFI 边界', href: '/rust/unsafe-and-ffi-boundaries', description: '理解 unsafe 责任转移、封装原则和跨语言交互风险。' },
        { title: '测试与质量实践', href: '/rust/testing-and-quality-practice', description: '把测试、fmt、clippy 和回归策略收成一条质量闭环。' },
        { title: 'Rust 测试替身与依赖隔离实践', href: '/rust/test-doubles-and-dependency-isolation-practice', description: '把 fake、stub、mock、本地 HTTP server、Tokio 异步测试和依赖隔离策略收成一页。' },
      ],
      order: [
        'Rust 学习路径与资料导航',
        'Rust 必备知识总览',
        'Rust 能力自检与面试准备导航',
        'Rust 必备问题清单',
        'Rust 能力自检高频题示例代码片段',
        '所有权、借用与生命周期',
        'Rust Borrow Checker 常见报错排障指南',
        '集合、字符串与迭代器',
        'Trait、泛型与模式匹配',
        '智能指针与内部可变性',
        '错误处理、Cargo 与测试',
        '项目结构、crate 组织与 API 设计',
        'Rust DTO、领域模型与存储模型分层实践',
        'Rust 输入校验与边界建模实践',
        'Rust 常用 crate 选型与工程边界',
        'Rust CLI 工具实践',
        'Rust 配置管理实践',
        'Rust Workspace 与 Monorepo 实践',
        '并发与 Async 基础',
        'Tokio 与 Async 工程实践',
        'Rust HTTP Client 与外部 API 实践',
        'Rust 后台任务与 Worker 实践',
        'Rust 定时任务、调度与 Leader Election 实践',
        'Rust 缓存与 Redis 实践',
        'Axum Web 服务实践',
        'Rust 限流、超时与负载保护实践',
        'Rust API 错误响应与响应体设计实践',
        'Rust API Versioning、兼容演进与弃用治理实践',
        'Rust 列表查询、过滤、排序与分页实践',
        'Rust 搜索、索引与检索实践',
        'Rust 批处理、回填与历史数据修复实践',
        'Rust 幂等、状态机与 Outbox 实践',
        'Rust 消息队列与事件驱动实践',
        'Rust 文件上传、对象存储与 S3 实践',
        'Rust 认证、授权与请求上下文实践',
        'Rust Secrets、密钥与凭证轮换实践',
        'Rust 数据脱敏、隐私字段与日志安全实践',
        'Rust Feature Flag、运行时开关与灰度治理实践',
        'Rust 多租户与数据隔离实践',
        'Rust 审计日志与操作记录实践',
        'Rust Webhook、回调与签名校验实践',
        'Rust WebSocket 与 SSE 实践',
        'SQLx 数据库访问实践',
        'Rust 事务、锁与并发更新实践',
        'Rust 数据库迁移、Schema 演进与兼容发布实践',
        'Rust 导出、报表与大结果集实践',
        'Axum + SQLx 服务落地模板',
        'Tracing 与可观测性实践',
        'Rust Metrics 与 OpenTelemetry 实践',
        'Rust 性能分析与 Profiling 指南',
        '服务配置与优雅关闭',
        'Rust 后端项目骨架',
        'Rust 服务部署与发布清单',
        'Serde 与数据序列化实践',
        '宏与元编程基础',
        'Unsafe 与 FFI 边界',
        '测试与质量实践',
        'Rust 测试替身与依赖隔离实践',
      ],
    },
    sidebar: [
      {
        text: '核心入口',
        items: [
          { text: '方向概览', link: '/rust/' },
          { text: '学习路径', link: '/rust/learning-path' },
          { text: '必备知识总览', link: '/rust/essential-knowledge' },
          { text: '能力自检导航', link: '/rust/interview-prep' },
          { text: '必备问题清单', link: '/rust/essential-questions' },
          { text: '高频代码片段', link: '/rust/interview-code-snippets' },
          { text: '所有权与生命周期', link: '/rust/ownership-borrowing-and-lifetimes' },
          { text: 'Borrow Checker 排障', link: '/rust/borrow-checker-troubleshooting-guide' },
          { text: 'CLI 工具实践', link: '/rust/cli-tool-practice' },
        ],
      },
      {
        text: '语言与工程',
        collapsed: true,
        items: [
          { text: '所有权与生命周期', link: '/rust/ownership-borrowing-and-lifetimes' },
          { text: 'Borrow Checker 排障', link: '/rust/borrow-checker-troubleshooting-guide' },
          { text: '集合、字符串与迭代器', link: '/rust/collections-strings-and-iterators' },
          { text: 'Trait 与泛型', link: '/rust/traits-generics-and-pattern-matching' },
          { text: '智能指针与内部可变性', link: '/rust/smart-pointers-and-interior-mutability' },
          { text: '错误处理与 Cargo', link: '/rust/error-handling-cargo-and-testing' },
          { text: '项目结构与 API 设计', link: '/rust/project-structure-and-api-design' },
          { text: 'DTO / 领域模型分层', link: '/rust/dto-domain-and-persistence-model-practice' },
          { text: '输入校验与边界建模', link: '/rust/validation-and-input-boundaries-practice' },
          { text: 'crate 选型与边界', link: '/rust/crate-selection-and-boundaries' },
          { text: 'CLI 工具实践', link: '/rust/cli-tool-practice' },
          { text: '配置管理实践', link: '/rust/configuration-management-practice' },
          { text: 'Workspace 与 Monorepo', link: '/rust/workspace-and-monorepo-practice' },
        ],
      },
      {
        text: '并发与 Async',
        collapsed: true,
        items: [
          { text: '并发与 Async 基础', link: '/rust/concurrency-and-async' },
          { text: 'Tokio 与 Async 工程实践', link: '/rust/tokio-and-async-practice' },
          { text: 'HTTP Client 与外部 API', link: '/rust/http-client-and-external-api-practice' },
          { text: '后台任务与 Worker', link: '/rust/background-jobs-and-worker-practice' },
          { text: '定时任务、调度与 Leader Election', link: '/rust/scheduler-and-leader-election-practice' },
          { text: '缓存与 Redis 实践', link: '/rust/cache-and-redis-practice' },
        ],
      },
      {
        text: '服务与数据库',
        collapsed: true,
        items: [
          { text: 'Axum Web 服务实践', link: '/rust/axum-web-service-practice' },
          { text: '限流、超时与负载保护', link: '/rust/rate-limit-timeout-and-overload-protection-practice' },
          { text: 'API 错误响应与响应体设计', link: '/rust/api-error-and-response-design-practice' },
          { text: 'API Versioning、兼容演进与弃用治理', link: '/rust/api-versioning-and-compatibility-governance-practice' },
          { text: '列表查询、过滤、排序与分页', link: '/rust/pagination-filter-and-sorting-practice' },
          { text: '搜索、索引与检索', link: '/rust/search-index-and-retrieval-practice' },
          { text: '批处理、回填与历史数据修复', link: '/rust/batch-processing-backfill-and-historical-repair-practice' },
          { text: '幂等、状态机与 Outbox', link: '/rust/idempotency-state-machine-and-outbox-practice' },
          { text: '消息队列与事件驱动', link: '/rust/message-queue-and-event-driven-practice' },
          { text: '文件上传、对象存储与 S3', link: '/rust/file-upload-and-object-storage-practice' },
          { text: '认证与请求上下文', link: '/rust/auth-authorization-and-request-context-practice' },
          { text: 'Secrets、密钥与凭证轮换', link: '/rust/secret-management-and-credential-rotation-practice' },
          { text: '数据脱敏、隐私字段与日志安全', link: '/rust/data-masking-privacy-and-log-safety-practice' },
          { text: 'Feature Flag、运行时开关与灰度治理', link: '/rust/feature-flag-and-runtime-governance-practice' },
          { text: '多租户与数据隔离', link: '/rust/multi-tenant-and-data-isolation-practice' },
          { text: '审计日志与操作记录', link: '/rust/audit-log-and-operation-history-practice' },
          { text: 'Webhook、回调与签名校验', link: '/rust/webhook-and-callback-practice' },
          { text: 'WebSocket 与 SSE', link: '/rust/websocket-and-sse-practice' },
          { text: 'SQLx 数据库访问实践', link: '/rust/sqlx-database-practice' },
          { text: '事务、锁与并发更新', link: '/rust/transaction-locking-and-concurrent-update-practice' },
          { text: '数据库迁移与 Schema 演进', link: '/rust/database-migration-and-schema-evolution-practice' },
          { text: '导出、报表与大结果集', link: '/rust/export-report-and-large-result-practice' },
          { text: 'Axum + SQLx 服务落地模板', link: '/rust/axum-sqlx-service-template' },
          { text: 'Tracing 与可观测性', link: '/rust/tracing-and-observability-practice' },
          { text: 'Metrics 与 OpenTelemetry', link: '/rust/metrics-and-opentelemetry-practice' },
          { text: '性能分析与 Profiling', link: '/rust/performance-and-profiling-guide' },
          { text: '配置与优雅关闭', link: '/rust/service-configuration-and-graceful-shutdown' },
          { text: '后端项目骨架', link: '/rust/backend-project-skeleton' },
          { text: '部署与发布清单', link: '/rust/deployment-and-release-checklist' },
        ],
      },
      {
        text: '进阶专题',
        collapsed: true,
        items: [
          { text: 'Serde 与数据序列化', link: '/rust/serde-and-data-serialization' },
          { text: '宏与元编程', link: '/rust/macros-and-metaprogramming' },
          { text: 'Unsafe 与 FFI 边界', link: '/rust/unsafe-and-ffi-boundaries' },
          { text: '测试与质量实践', link: '/rust/testing-and-quality-practice' },
          { text: '测试替身与依赖隔离', link: '/rust/test-doubles-and-dependency-isolation-practice' },
        ],
      },
    ],
  },
  {
    key: 'mysql',
    base: '/mysql/',
    navText: 'MySQL',
    overviewDescription:
      '系统整理 MySQL 核心知识，聚焦事务、查询优化、GORM，以及高并发场景下的索引设计、大事务拆分、死锁治理、热点更新与分库迁移。',
    landing: {
      eyebrow: 'MySQL',
      title: 'MySQL 专题',
      intro:
        '把散落在 Go 学习大纲和支付系统案例中的 MySQL 相关内容统一收敛，涵盖日常开发基础和高并发场景实战。',
      primary: { title: '专题总览', href: '/mysql/', description: '从总览页开始，按主题查阅。' },
      secondary: { title: '索引设计', href: '/mysql/index-design', description: '从 B+ 树和最左前缀开始。' },
      scope: [
        'Go 与 MySQL 集成',
        '事务处理',
        '查询优化',
        'GORM 实战',
        '索引设计',
        '长事务与死锁治理',
        '热点更新与分库迁移',
        'MySQL 实战 45 讲（原理精读）',
      ],
      docs: [
        { title: 'database/sql 与连接池（Go 专题）', href: '/golang/guide/06-database-sql-and-connection', description: 'Go 标准库操作数据库的核心用法与连接池配置。' },
        { title: '事务处理', href: '/mysql/transaction-and-optimization', description: '事务模式、隔离级别、悲观锁与乐观锁、大事务拆分与长事务治理。' },
        { title: '查询优化', href: '/mysql/sql-optimization', description: 'EXPLAIN 分析、索引使用、批量操作与游标分页。' },
        { title: 'GORM实战', href: '/mysql/orm-gorm', description: 'GORM 基础用法、N+1 问题与何时用原生 SQL。' },
        { title: '索引设计', href: '/mysql/index-design', description: '索引结构、回表原理、最左前缀与索引失效场景。' },
        { title: '死锁重试', href: '/mysql/deadlock-and-retry', description: '死锁排查、根因治理与幂等回滚重试。' },
        { title: '热点更新', href: '/mysql/hot-account-update', description: '从乐观锁到子账户拆分的分层治理方案。' },
        { title: '分库迁移', href: '/mysql/sharding-and-migration', description: '拆分策略、数据迁移流程与核心原则。' },
        { title: '高频追问', href: '/mysql/high-frequency-questions', description: 'SELECT *、深分页、锁持有时间等落地细节。' },
      ],
      order: [
        'database/sql 与连接池（Go 专题）',
        '事务处理',
        '查询优化',
        'GORM实战',
        '索引设计',
        '死锁重试',
        '热点更新',
        '分库迁移',
        '高频追问',
      ],
    },
    sidebar: [
      {
        text: '基础专题',
        items: [
          { text: '专题总览', link: '/mysql/' },
          { text: '事务处理', link: '/mysql/transaction-and-optimization' },
          { text: '查询优化', link: '/mysql/sql-optimization' },
          { text: 'GORM实战', link: '/mysql/orm-gorm' },
        ],
      },
      {
        text: '并发专题',
        items: [
          { text: '索引设计', link: '/mysql/index-design' },
          { text: '死锁重试', link: '/mysql/deadlock-and-retry' },
          { text: '热点更新', link: '/mysql/hot-account-update' },
          { text: '分库迁移', link: '/mysql/sharding-and-migration' },
          { text: '高频追问', link: '/mysql/high-frequency-questions' },
        ],
      },
      {
        text: '基础八讲',
        collapsed: true,
        items: [
          { text: '00 开篇导读', link: '/mysql/00-preface' },
          { text: '01 查询执行', link: '/mysql/01-sql-query-execution' },
          { text: '02 更新链路', link: '/mysql/02-sql-update-log-system' },
          { text: '03 事务隔离', link: '/mysql/03-transaction-isolation' },
          { text: '04 索引上篇', link: '/mysql/04-index-part1' },
          { text: '05 索引下篇', link: '/mysql/05-index-part2' },
          { text: '06 全局表锁', link: '/mysql/06-global-table-lock' },
          { text: '07 行锁机制', link: '/mysql/07-row-lock' },
          { text: '08 隔离细节', link: '/mysql/08-transaction-isolation-detail' },
        ],
      },
      {
        text: '索引七讲',
        collapsed: true,
        items: [
          { text: '09 索引选型', link: '/mysql/09-normal-vs-unique-index' },
          { text: '10 误选索引', link: '/mysql/10-wrong-index-selection' },
          { text: '11 字符索引', link: '/mysql/11-string-index' },
          { text: '12 抖动分析', link: '/mysql/12-mysql-flush' },
          { text: '13 空间回收', link: '/mysql/13-table-space-reclaim' },
          { text: '14 计数优化', link: '/mysql/14-count-slow' },
          { text: '15 日志索引', link: '/mysql/15-qa-log-and-index' },
        ],
      },
      {
        text: '查询六讲',
        collapsed: true,
        items: [
          { text: '16 排序原理', link: '/mysql/16-order-by' },
          { text: '17 随机查询', link: '/mysql/17-random-message' },
          { text: '18 逻辑性能', link: '/mysql/18-sql-same-logic-diff-perf' },
          { text: '19 单行慢查', link: '/mysql/19-single-row-query-slow' },
          { text: '20 幻读问题', link: '/mysql/20-phantom-read' },
          { text: '21 更新加锁', link: '/mysql/21-single-row-update-many-locks' },
        ],
      },
      {
        text: '高可用篇',
        collapsed: true,
        items: [
          { text: '22 应急提速', link: '/mysql/22-emergency-perf-boost' },
          { text: '23 数据持久', link: '/mysql/23-data-durability' },
          { text: '24 主备一致', link: '/mysql/24-master-slave-consistency' },
          { text: '25 高可用性', link: '/mysql/25-high-availability' },
          { text: '26 备库延迟', link: '/mysql/26-slave-delay' },
          { text: '27 主库故障', link: '/mysql/27-master-failure' },
          { text: '28 读写分离', link: '/mysql/28-read-write-split-pitfalls' },
          { text: '29 健康检查', link: '/mysql/29-database-health-check' },
          { text: '30 动态加锁', link: '/mysql/30-qa-dynamic-locking' },
        ],
      },
      {
        text: '运维进阶',
        collapsed: true,
        items: [
          { text: '31 误删恢复', link: '/mysql/31-data-recovery' },
          { text: '32 语句终止', link: '/mysql/32-unkillable-query' },
          { text: '33 查询内存', link: '/mysql/33-large-query-memory' },
          { text: '34 关联使用', link: '/mysql/34-join-usage' },
          { text: '35 关联优化', link: '/mysql/35-join-optimization' },
          { text: '36 临表重名', link: '/mysql/36-temp-table-rename' },
          { text: '37 内部临表', link: '/mysql/37-internal-temp-table' },
          { text: '38 引擎对比', link: '/mysql/38-innodb-vs-memory-engine' },
          { text: '39 自增间隙', link: '/mysql/39-auto-increment-gaps' },
          { text: '40 插入加锁', link: '/mysql/40-insert-locks' },
          { text: '41 快速拷表', link: '/mysql/41-fastest-table-copy' },
          { text: '42 权限刷新', link: '/mysql/42-grant-flush-privileges' },
          { text: '43 分区设计', link: '/mysql/43-partition-table' },
          { text: '44 问题答疑', link: '/mysql/44-qa-good-questions' },
          { text: '45 自增溢出', link: '/mysql/45-auto-increment-overflow' },
          { text: '46 收官总结', link: '/mysql/46-conclusion' },
        ],
      },
    ],
  },
  {
    key: 'redis',
    base: '/redis/',
    navText: 'Redis',
    overviewDescription:
      '系统整理 Redis 核心知识，涵盖缓存治理、go-redis 客户端实践、分布式锁、Lua 原子性、滑动窗口与支付系统高并发场景。',
    landing: {
      eyebrow: 'Redis',
      title: 'Redis 专题',
      intro:
        '把散落在 Go 实践、源码精读和支付系统案例中的 Redis 相关内容统一收敛，方便按主题查阅和持续更新。',
      primary: { title: '专题总览', href: '/redis/', description: '从总览页开始，按主题查阅。' },
      secondary: { title: '高并发治理', href: '/redis/high-concurrency-cluster-locks', description: '继续补集群、锁和 Lua。' },
      scope: [
        'go-redis 客户端实践',
        '缓存穿透/击穿/雪崩',
        '高并发治理与集群部署',
        'Pipeline 与 Pub/Sub',
        '分布式锁与 Lua',
        '滑动窗口与限流',
        '支付系统幂等与高并发治理',
      ],
      docs: [
        { title: 'Redis 实践与缓存穿透/击穿/雪崩', href: '/redis/redis-and-cache-patterns', description: 'go-redis 基础用法、Pipeline、Pub/Sub、singleflight、布隆过滤器与多级缓存。' },
        { title: 'Redis 高并发、集群部署与分布式锁', href: '/redis/high-concurrency-cluster-locks', description: '热点 Key / 大 Key 治理、Sentinel / Cluster 选型、hash tag、分布式锁与 Lua 原子脚本。' },
        { title: 'go-redis 客户端源码精读', href: '/golang/guide/source-reading/go-redis', description: '连接池、Pipeline/TxPipeline、分布式锁、Watch 与客户端设计细节。' },
        { title: '支付系统 Redis 实战', href: '/redis/payment-practice', description: '缓存治理、分布式锁、Lua、滑动窗口、请求级幂等与支付场景答题模板。' },
      ],
      order: [
        'Redis 实践与缓存穿透/击穿/雪崩',
        'Redis 高并发、集群部署与分布式锁',
        'go-redis 客户端源码精读',
        '支付系统 Redis 实战',
      ],
    },
    sidebar: [
      {
        text: 'Redis 专题',
        items: [
          { text: '专题总览', link: '/redis/' },
          { text: 'Redis 实践与缓存穿透/击穿/雪崩', link: '/redis/redis-and-cache-patterns' },
          { text: 'Redis 高并发、集群部署与分布式锁', link: '/redis/high-concurrency-cluster-locks' },
          { text: 'go-redis 客户端源码精读', link: '/golang/guide/source-reading/go-redis' },
          { text: '支付系统 Redis 实战', link: '/redis/payment-practice' },
        ],
      },
    ],
  },
  {
    key: 'kafka',
    base: '/kafka/',
    navText: 'Kafka',
    overviewDescription:
      '系统整理 Kafka 核心知识，涵盖 Producer/Consumer/Broker、分区与副本、消息可靠性、顺序性、积压治理与支付实战。',
    landing: {
      eyebrow: 'Kafka',
      title: 'Kafka 专题',
      intro:
        '把散落在支付系统案例中的 Kafka 相关内容统一收敛，涵盖核心概念、支付实战和高频深入追问。',
      primary: { title: '专题总览', href: '/kafka/', description: '从总览页开始，按主题查阅。' },
      secondary: { title: '核心概念', href: '/kafka/core-concepts', description: '从 Producer/Broker/Consumer 开始。' },
      scope: [
        'Producer/Consumer/Broker',
        'Topic/Partition/Offset',
        'Consumer Group 与 Rebalance',
        '高可用与副本机制',
        '支付场景消息可靠性',
        '顺序性、积压治理与死信',
      ],
      docs: [
        { title: '核心概念', href: '/kafka/core-concepts', description: 'Producer/Consumer/Broker、Topic/Partition、Consumer Group、高可用机制与性能原理。' },
        { title: '支付实战', href: '/kafka/payment-practice', description: 'TCC+Kafka、本地消息表、Offset 补偿、全链路闭环、延迟队列与生产治理。' },
        { title: '深入追问与词汇', href: '/kafka/interview-questions', description: '消息不丢失、顺序性、积压处理、重试与死信、幂等与事务、英语术语速查。' },
      ],
      order: [
        '核心概念',
        '支付实战',
        '深入追问与词汇',
      ],
    },
    sidebar: [
      {
        text: 'Kafka 专题',
        items: [
          { text: '专题总览', link: '/kafka/' },
          { text: '核心概念', link: '/kafka/core-concepts' },
          { text: '支付实战', link: '/kafka/payment-practice' },
          { text: '深入追问与词汇', link: '/kafka/interview-questions' },
        ],
      },
    ],
  },
  {
    key: 'etcd',
    base: '/etcd/',
    navText: 'etcd',
    overviewDescription:
      '系统整理 etcd 必须掌握的核心知识，涵盖 Raft、多数派、MVCC revision、Lease/Watch、Txn/CAS、读一致性与生产运维边界。',
    landing: {
      eyebrow: 'etcd',
      title: 'etcd 专题',
      intro:
        '把 etcd 从“知道能做注册中心”提升到“理解一致性存储系统”的层面，先抓必须掌握的知识点，再延伸到服务发现、配置中心和高可用场景。',
      primary: { title: '专题总览', href: '/etcd/', description: '从总览页开始，先建立统一框架。' },
      secondary: { title: 'RPC、注册发现与配置', href: '/golang/guide/08-rpc-discovery-config', description: '看 Go 场景中的 etcd 落地。' },
      scope: [
        'Raft 与多数派',
        'MVCC 与 revision',
        'Lease / TTL / KeepAlive',
        'Watch 与 compaction',
        'Txn / CAS / 分布式锁',
        '线性一致性读写',
        '备份恢复与运维边界',
      ],
      docs: [
        { title: '专题总览', href: '/etcd/', description: '先建立 etcd 的定位、核心机制和必须掌握知识点。' },
        { title: 'RPC、注册发现与配置', href: '/golang/guide/08-rpc-discovery-config', description: '看 etcd 在服务注册发现和配置中心里的 Go 实战。' },
        { title: 'PostgreSQL 高可用集群整理', href: '/postgresql/ha-cluster', description: '看 etcd 在 Patroni + HAProxy 方案中的角色。' },
      ],
      order: [
        '专题总览',
        'RPC、注册发现与配置',
        'PostgreSQL 高可用集群整理',
      ],
    },
    sidebar: [
      {
        text: 'etcd 专题',
        items: [
          { text: '专题总览', link: '/etcd/' },
        ],
      },
    ],
  },
  {
    key: 'k8s',
    base: '/k8s/',
    navText: 'K8s',
    overviewDescription:
      '系统整理 Kubernetes 必备知识，涵盖核心对象、调度与资源管理、网络与存储、发布治理、故障排查与控制面原理。',
    landing: {
      eyebrow: 'K8s',
      title: 'K8s 专题',
      intro:
        '把 Kubernetes 从“会写 YAML”提升到“能解释机制、能定位问题、能回答高频追问”的层面，先建立统一对象模型，再按由浅入深整理必备问题。',
      primary: { title: '专题总览', href: '/k8s/', description: '从总览页开始，先建立统一框架。' },
      secondary: { title: '入口控制器实现链路', href: '/k8s/ingress-and-gateway-controller-chain', description: '补 IngressClass、GatewayClass、controller 接管和地址分配。' },
      scope: [
        '控制面与节点组件',
        'Pod / Deployment / StatefulSet',
        'Service / Ingress / Mesh 与服务发现',
        '调度、资源限制与弹性伸缩',
        '探针、发布与优雅终止',
        '网络、存储与持久化',
        'RBAC、ServiceAccount 与隔离',
        '控制循环、etcd、CRD / Operator',
      ],
      docs: [
        { title: '核心概念与对象模型', href: '/k8s/core-concepts', description: '从定位、控制面、核心对象到调度与存储，建立统一认知。' },
        { title: '必备问题清单', href: '/k8s/essential-questions', description: '按由浅入深整理高频问题，覆盖发布、排障、安全与深入机制。' },
        { title: 'Pod 生命周期与探针实战', href: '/k8s/pod-lifecycle-and-probes', description: '系统讲清 Pod phase、Running/Ready、CrashLoopBackOff 与 startup、readiness、liveness 的边界。' },
        { title: 'Pod 内多容器协作实战', href: '/k8s/pod-multi-container-collaboration', description: '系统讲清为什么 Pod 是最小调度单元，以及主容器、Init Container、Sidecar、临时容器、共享网络与共享卷的边界。' },
        { title: 'Job 与 CronJob 批处理链路实战', href: '/k8s/job-and-cronjob-batch-workloads', description: '系统讲清 Job、CronJob、重试、补跑、并发策略、历史清理与幂等性边界，以及为什么一次性任务不该用 Deployment。' },
        { title: 'ConfigMap、Secret 与配置注入边界实战', href: '/k8s/configmap-secret-and-config-injection', description: '系统讲清 ConfigMap、Secret、env、envFrom、volume、projected volume、subPath、热更新传播与安全边界。' },
        { title: '调度与驱逐链路实战', href: '/k8s/scheduling-and-eviction', description: '把 Pending、OOMKilled、Evicted 以及 requests、QoS、优先级、污点容忍放回同一条链路里。' },
        { title: 'PriorityClass、Preemption 与调度让路边界实战', href: '/k8s/priorityclass-preemption-and-scheduling-boundaries', description: '系统讲清 PriorityClass、调度队列顺序、scheduler preemption、nominatedNodeName、非抢占优先级、PDB best effort、QoS 与节点压力驱逐的边界。' },
        { title: '资源规格与运行时压力实战', href: '/k8s/resource-specs-and-runtime-pressure', description: '系统讲清 requests、limits、QoS、CPU throttling、OOMKilled 和节点压力之间的关系，以及为什么“能调度”不等于“跑得稳”。' },
        { title: '弹性扩缩容与容量协同实战', href: '/k8s/autoscaling-and-capacity-control-chain', description: '系统讲清 HPA、VPA、Cluster Autoscaler 如何围绕 requests、Pending、节点容量和 Ready 协同工作。' },
        { title: '副本打散与拓扑高可用实战', href: '/k8s/replica-spread-and-topology-ha', description: '系统讲清 podAntiAffinity、topologySpreadConstraints、PodDisruptionBudget、drain 如何围绕节点、可用区和维护窗口共同保障高可用。' },
        { title: '零停机发布链路实战', href: '/k8s/zero-downtime-rollout', description: '把 readiness、preStop、SIGTERM、grace period、PDB 串成一条真正可用的发布链路。' },
        { title: 'PDB、Eviction API 与 drain 边界实战', href: '/k8s/pdb-eviction-api-and-drain-boundaries', description: '系统讲清 voluntary/involuntary disruption、PodDisruptionBudget、Eviction API、kubectl drain、429 Too Many Requests 与 unhealthyPodEvictionPolicy。' },
        { title: 'StatefulSet 与 Headless Service 实战', href: '/k8s/statefulset-headless-service', description: '讲清稳定实例身份、成员级 DNS 和独立 PVC，拆掉“固定 Pod IP”误解。' },
        { title: '存储与数据链路实战', href: '/k8s/storage-and-data-lifecycle', description: '拆清 PV、PVC、StorageClass、CSI、扩容、回收策略和常见挂载故障。' },
        { title: '认证、授权与隔离链路实战', href: '/k8s/authn-authz-and-isolation', description: '拆清 ServiceAccount、RBAC、Admission、Secret、NetworkPolicy 的边界与协作关系。' },
        { title: 'ServiceAccount Token 与 Pod 身份边界实战', href: '/k8s/serviceaccount-token-and-pod-identity', description: '系统讲清 ServiceAccount、自动挂载 token、projected serviceAccountToken、TokenRequest、audience、自动轮转与 Pod 身份边界。' },
        { title: 'RBAC 实战与最小权限设计', href: '/k8s/rbac-and-least-privilege', description: '系统讲清 Role、ClusterRole、RoleBinding、ClusterRoleBinding、resourceNames、subresource、serviceaccounts/token、bind、escalate、impersonate 与最小权限设计边界。' },
        { title: 'Pod Security 与 SecurityContext 运行权限边界实战', href: '/k8s/pod-security-and-security-context', description: '系统讲清 SecurityContext、Pod Security Admission、Pod Security Standards、runAsNonRoot、allowPrivilegeEscalation、privileged、capabilities、seccomp、host namespaces 与 hostPath 的安全边界。' },
        { title: 'Admission、策略治理与 Policy Engine 边界实战', href: '/k8s/admission-policy-and-governance', description: '系统讲清内建 Admission Controllers、Mutating/Validating Webhook、ValidatingAdmissionPolicy、Pod Security Admission、OPA Gatekeeper、Kyverno 的职责边界与选型。' },
        { title: '镜像安全、镜像准入与供应链边界实战', href: '/k8s/image-security-and-supply-chain-governance', description: '系统讲清镜像 tag 与 digest、imagePullPolicy、imagePullSecrets、AlwaysPullImages、镜像来源限制、签名校验、attestation、SBOM 与供应链治理边界。' },
        { title: 'Secret 安全、etcd 加密与外部 Secret 管理边界实战', href: '/k8s/secret-security-and-external-secret-management', description: '系统讲清 Secret 的 base64 与真正加密、etcd at-rest encryption、KMS、RBAC 边界、节点分发、ESO、Secrets Store CSI Driver 与轮转收敛。' },
        { title: 'API 审计、Audit Policy 与审计日志边界实战', href: '/k8s/api-auditing-and-audit-policy-boundary', description: '系统讲清 API Audit 的执行位置、Audit Policy、规则顺序、级别、阶段、log 与 webhook backend、admission webhook audit annotations 与审计日志边界。' },
        { title: 'Namespace 资源治理与配额边界实战', href: '/k8s/namespace-resource-governance-and-quota', description: '系统讲清 Namespace、LimitRange、ResourceQuota 如何围绕默认值、单对象边界、命名空间总预算和对象数量配额共同做资源治理。' },
        { title: '控制器与 Reconcile 链路实战', href: '/k8s/controllers-and-reconcile', description: '讲清 controller、reconcile loop、Deployment、HPA、CRD、Operator 如何协同工作。' },
        { title: '删除、Finalizers 与 Terminating 边界实战', href: '/k8s/deletion-finalizers-and-terminating-boundaries', description: '系统讲清 delete、deletionTimestamp、finalizers、ownerReferences、垃圾回收、Foreground/Background/Orphan、Pod Terminating 与控制面对象删除边界。' },
        { title: '控制面主线实战', href: '/k8s/control-plane-mainline', description: '系统讲清 kube-apiserver、etcd、kube-scheduler、kube-controller-manager 如何把声明变成真正运行的 Pod。' },
        { title: '节点心跳、Lease 与失联驱逐边界实战', href: '/k8s/node-heartbeat-lease-and-failure-eviction', description: '系统讲清节点心跳、Lease、Ready False/Unknown、自动 taint、NoExecute、tolerationSeconds、失联驱逐与网络分区边界。' },
        { title: '节点执行链路实战', href: '/k8s/node-execution-chain', description: '系统讲清 kubelet、CRI、container runtime、Pod sandbox、CNI、CSI 如何把一个已调度的 Pod 真正跑起来。' },
        { title: '服务暴露与流量入口链路实战', href: '/k8s/service-exposure-and-traffic-entry', description: '拆清 ClusterIP、NodePort、LoadBalancer、Ingress、Gateway API、TLS 终止与真实源地址。' },
        { title: 'Ingress Controller 与 Gateway Controller 实现链路', href: '/k8s/ingress-and-gateway-controller-chain', description: '系统讲清 Ingress、IngressClass、GatewayClass、Gateway、HTTPRoute 背后的控制器接管、路由下发、地址分配与常见排障方法。' },
        { title: 'CoreDNS 与服务发现实战', href: '/k8s/coredns-and-service-discovery', description: '系统讲清服务名解析、CoreDNS、普通 Service DNS、Headless Service DNS、dnsPolicy、ndots 与常见服务发现排障方法。' },
        { title: 'EndpointSlice、Ready 与服务后端收敛边界实战', href: '/k8s/service-backend-readiness-and-endpointslice', description: '系统讲清 EndpointSlice、Service selector、ready/serving/terminating、publishNotReadyAddresses、滚动发布摘流量，以及为什么 Pod Running 了也不一定已经进后端池。' },
        { title: 'kube-proxy 与 Service 数据面实战', href: '/k8s/kube-proxy-and-service-dataplane', description: '系统讲清 Service VIP、EndpointSlice、kube-proxy、iptables、IPVS、NodePort 与 externalTrafficPolicy 的数据面实现和排障方法。' },
        { title: 'NetworkPolicy 与东西向访问控制实战', href: '/k8s/networkpolicy-and-east-west-access-control', description: '系统讲清 NetworkPolicy 的默认拒绝、Ingress/Egress、生效前提、selector 语义、DNS 放行、ipBlock 边界与常见排障方法。' },
        { title: 'Service Mesh 与东西向流量实战', href: '/k8s/service-mesh-and-east-west-traffic', description: '拆清南北向与东西向边界，以及 Service Mesh、Sidecar、mTLS、重试、熔断、灰度和 Egress Gateway。' },
        { title: 'K8s 网络排障手册', href: '/k8s/network-troubleshooting', description: '按 Service、EndpointSlice、kube-proxy、CNI、Pod 五层链路系统排查网络问题。' },
        { title: '固定入口、固定出口与白名单实战', href: '/k8s/fixed-ip-and-whitelist', description: '拆清 Pod 动态 IP、固定入口、固定出口、第三方白名单与真实客户端 IP 保留。' },
        { title: 'externalTrafficPolicy Local 实战与边界', href: '/k8s/external-traffic-policy-local', description: '拆清 Cluster 和 Local 的差异、源地址保留机制、副作用与适用边界。' },
        { title: '容器化与云原生实践', href: '/golang/guide/10-containerization-cloud-native', description: '从 Go 服务视角看探针、优雅关闭、配置和 K8s 部署。' },
        { title: 'etcd 专题', href: '/etcd/', description: '理解 etcd 在 Kubernetes 控制面中的角色和一致性边界。' },
      ],
      order: [
        '核心概念与对象模型',
        '必备问题清单',
        'Pod 生命周期与探针实战',
        'Pod 内多容器协作实战',
        'Job 与 CronJob 批处理链路实战',
        'ConfigMap、Secret 与配置注入边界实战',
        '调度与驱逐链路实战',
        'PriorityClass、Preemption 与调度让路边界实战',
        '资源规格与运行时压力实战',
        '弹性扩缩容与容量协同实战',
        '副本打散与拓扑高可用实战',
        '零停机发布链路实战',
        'PDB、Eviction API 与 drain 边界实战',
        'StatefulSet 与 Headless Service 实战',
        '存储与数据链路实战',
        '认证、授权与隔离链路实战',
        'ServiceAccount Token 与 Pod 身份边界实战',
        'RBAC 实战与最小权限设计',
        'Pod Security 与 SecurityContext 运行权限边界实战',
        'Admission、策略治理与 Policy Engine 边界实战',
        '镜像安全、镜像准入与供应链边界实战',
        'Secret 安全、etcd 加密与外部 Secret 管理边界实战',
        'API 审计、Audit Policy 与审计日志边界实战',
        'Namespace 资源治理与配额边界实战',
        '控制器与 Reconcile 链路实战',
        '删除、Finalizers 与 Terminating 边界实战',
        '控制面主线实战',
        '节点心跳、Lease 与失联驱逐边界实战',
        '节点执行链路实战',
        '服务暴露与流量入口链路实战',
        'Ingress Controller 与 Gateway Controller 实现链路',
        'CoreDNS 与服务发现实战',
        'EndpointSlice、Ready 与服务后端收敛边界实战',
        'kube-proxy 与 Service 数据面实战',
        'NetworkPolicy 与东西向访问控制实战',
        'Service Mesh 与东西向流量实战',
        'K8s 网络排障手册',
        '固定入口、固定出口与白名单实战',
        'externalTrafficPolicy Local 实战与边界',
        '容器化与云原生实践',
        'etcd 专题',
      ],
    },
    sidebar: [
      {
        text: 'K8s 专题',
        items: [
          { text: '专题总览', link: '/k8s/' },
          { text: '核心概念与对象模型', link: '/k8s/core-concepts' },
          { text: '必备问题清单', link: '/k8s/essential-questions' },
          { text: 'Pod 生命周期与探针实战', link: '/k8s/pod-lifecycle-and-probes' },
          { text: 'Pod 内多容器协作实战', link: '/k8s/pod-multi-container-collaboration' },
          { text: 'Job 与 CronJob 批处理链路实战', link: '/k8s/job-and-cronjob-batch-workloads' },
          { text: 'ConfigMap、Secret 与配置注入边界实战', link: '/k8s/configmap-secret-and-config-injection' },
          { text: '调度与驱逐链路实战', link: '/k8s/scheduling-and-eviction' },
          { text: 'PriorityClass、Preemption 与调度让路边界实战', link: '/k8s/priorityclass-preemption-and-scheduling-boundaries' },
          { text: '资源规格与运行时压力实战', link: '/k8s/resource-specs-and-runtime-pressure' },
          { text: '弹性扩缩容与容量协同实战', link: '/k8s/autoscaling-and-capacity-control-chain' },
          { text: '副本打散与拓扑高可用实战', link: '/k8s/replica-spread-and-topology-ha' },
          { text: '零停机发布链路实战', link: '/k8s/zero-downtime-rollout' },
          { text: 'PDB、Eviction API 与 drain 边界实战', link: '/k8s/pdb-eviction-api-and-drain-boundaries' },
          { text: 'StatefulSet 与 Headless Service 实战', link: '/k8s/statefulset-headless-service' },
          { text: '存储与数据链路实战', link: '/k8s/storage-and-data-lifecycle' },
          { text: '认证、授权与隔离链路实战', link: '/k8s/authn-authz-and-isolation' },
          { text: 'ServiceAccount Token 与 Pod 身份边界实战', link: '/k8s/serviceaccount-token-and-pod-identity' },
          { text: 'RBAC 实战与最小权限设计', link: '/k8s/rbac-and-least-privilege' },
          { text: 'Pod Security 与 SecurityContext 运行权限边界实战', link: '/k8s/pod-security-and-security-context' },
          { text: 'Admission、策略治理与 Policy Engine 边界实战', link: '/k8s/admission-policy-and-governance' },
          { text: '镜像安全、镜像准入与供应链边界实战', link: '/k8s/image-security-and-supply-chain-governance' },
          { text: 'Secret 安全、etcd 加密与外部 Secret 管理边界实战', link: '/k8s/secret-security-and-external-secret-management' },
          { text: 'API 审计、Audit Policy 与审计日志边界实战', link: '/k8s/api-auditing-and-audit-policy-boundary' },
          { text: 'Namespace 资源治理与配额边界实战', link: '/k8s/namespace-resource-governance-and-quota' },
          { text: '控制器与 Reconcile 链路实战', link: '/k8s/controllers-and-reconcile' },
          { text: '删除、Finalizers 与 Terminating 边界实战', link: '/k8s/deletion-finalizers-and-terminating-boundaries' },
          { text: '控制面主线实战', link: '/k8s/control-plane-mainline' },
          { text: '节点心跳、Lease 与失联驱逐边界实战', link: '/k8s/node-heartbeat-lease-and-failure-eviction' },
          { text: '节点执行链路实战', link: '/k8s/node-execution-chain' },
          { text: '服务暴露与流量入口链路实战', link: '/k8s/service-exposure-and-traffic-entry' },
          { text: 'Ingress Controller 与 Gateway Controller 实现链路', link: '/k8s/ingress-and-gateway-controller-chain' },
          { text: 'CoreDNS 与服务发现实战', link: '/k8s/coredns-and-service-discovery' },
          { text: 'EndpointSlice、Ready 与服务后端收敛边界实战', link: '/k8s/service-backend-readiness-and-endpointslice' },
          { text: 'kube-proxy 与 Service 数据面实战', link: '/k8s/kube-proxy-and-service-dataplane' },
          { text: 'NetworkPolicy 与东西向访问控制实战', link: '/k8s/networkpolicy-and-east-west-access-control' },
          { text: 'Service Mesh 与东西向流量实战', link: '/k8s/service-mesh-and-east-west-traffic' },
          { text: 'K8s 网络排障手册', link: '/k8s/network-troubleshooting' },
          { text: '固定入口、固定出口与白名单实战', link: '/k8s/fixed-ip-and-whitelist' },
          { text: 'externalTrafficPolicy Local 实战与边界', link: '/k8s/external-traffic-policy-local' },
        ],
      },
    ],
  },
  {
    key: 'postgresql',
    base: '/postgresql/',
    navText: 'PostgreSQL',
    overviewDescription:
      '系统整理 PostgreSQL 核心知识，涵盖 MVCC、索引、锁与事务、批量写入、分区表、高可用集群部署与故障恢复。',
    landing: {
      eyebrow: 'PostgreSQL',
      title: 'PostgreSQL 专题',
      intro:
        '把散落在支付系统案例和架构文档中的 PostgreSQL 相关内容统一收敛，方便按主题查阅和持续更新。',
      primary: { title: '专题总览', href: '/postgresql/', description: '从总览页开始，按主题查阅。' },
      secondary: { title: '高可用集群', href: '/postgresql/ha-cluster', description: '从 Patroni + etcd + HAProxy 开始。' },
      scope: [
        'MVCC 与可见性',
        '索引与查询计划',
        '锁与事务',
        '批量写入与分区表',
        '高可用集群部署',
        'WAL 流复制与故障恢复',
      ],
      docs: [
        { title: '核心概念与高频考点', href: '/postgresql/core-concepts', description: 'MVCC、索引类型、锁与事务、批量写入、分区表、高可用与复制。' },
        { title: '支付场景追问', href: '/postgresql/payment-practice', description: '长事务问题、流水表分区、CopyFrom 使用时机、复制延迟监控。' },
        { title: '高可用集群整理', href: '/postgresql/ha-cluster', description: 'Patroni + etcd + HAProxy 部署、WAL 流复制、同步策略、故障恢复。' },
      ],
      order: [
        '核心概念与高频考点',
        '支付场景追问',
        '高可用集群整理',
      ],
    },
    sidebar: [
      {
        text: 'PostgreSQL 专题',
        items: [
          { text: '专题总览', link: '/postgresql/' },
          { text: '核心概念与高频考点', link: '/postgresql/core-concepts' },
          { text: '支付场景追问', link: '/postgresql/payment-practice' },
          { text: '高可用集群整理', link: '/postgresql/ha-cluster' },
        ],
      },
    ],
  },
  {
    key: 'ops',
    base: '/ops/',
    navText: '运维',
    overviewDescription:
      '适合需要日常运维能力的开发和运维工程师，重点覆盖磁盘排查、日志管理、进程管理等实操技能。',
    landing: {
      eyebrow: 'Ops',
      title: '运维方向',
      intro:
        '将日常运维中反复用到的排障命令、清理流程和管理技巧，从零散笔记整理成可复用的操作指南。',
      primary: {
        title: 'Linux 磁盘清理与进程管理',
        href: '/ops/linux-disk-cleanup',
        description: '从磁盘排查到进程管理的实战指南。',
      },
      scope: [
        '磁盘空间排查与清理',
        '日志管理与轮转',
        '缓存清理（Go / Node / Docker）',
        'PM2 进程管理',
        '用户管理与权限（chmod / chown / umask）',
        '常用运维工具',
      ],
      docs: [
        { title: 'Linux 磁盘清理与进程管理', href: '/ops/linux-disk-cleanup', description: '磁盘排查、日志清理、缓存管理、PM2 进程管理的实战操作指南。' },
        { title: 'Linux 用户管理与权限', href: '/ops/linux-user-permissions', description: '用户切换、chmod、chown、umask、用户目录管理的实战指南。' },
        { title: '待补主题清单', href: '/ops/todo-topics', description: '查看运维方向后续计划补充的主题。' },
      ],
      order: ['Linux 磁盘清理与进程管理', 'Linux 用户管理与权限'],
    },
    sidebar: [
      {
        text: '运维',
        items: [
          { text: '方向概览', link: '/ops/' },
          { text: 'Linux 磁盘清理与进程管理', link: '/ops/linux-disk-cleanup' },
          { text: 'Linux 用户管理与权限', link: '/ops/linux-user-permissions' },
          { text: '待补主题清单', link: '/ops/todo-topics' },
        ],
      },
    ],
  },
  {
    key: 'git',
    base: '/git/',
    navText: 'Git',
    overviewDescription:
      '集中整理 Git 工作流、分支对比、PR 与 Code Review、GitHub Actions 排障、发布与回滚实践。',
    landing: {
      eyebrow: 'Git',
      title: 'Git 主题',
      intro: '把 Git 基础、GitHub 协作、Code Review、GitHub Actions 排障、发布与回滚拆成更清晰的主题入口，方便后续持续扩展。',
      primary: { title: 'Git 常用技巧', href: '/git/common-tips', description: 'Git 与 GitHub 协作总手册，覆盖分支、对比、发布、回滚和团队规范。' },
      secondary: { title: 'GitHub PR 与 Code Review', href: '/git/github-pr-review', description: '集中处理 PR 提交、审核、评论回复、合并策略与多人协作实践。' },
      scope: [
        'Git 日常工作流与常用命令',
        '分支对比、cherry-pick 与恢复现场',
        'PR 提交与 Code Review 协作',
        'GitHub Actions CI/CD 与故障排查',
        '发布分支、回滚与多人协作排障',
      ],
      docs: [
        { title: 'Git 常用技巧', href: '/git/common-tips', description: 'Git 与 GitHub 协作总手册，覆盖分支、PR、Review、发布与回滚。' },
        { title: 'GitHub PR 与 Code Review', href: '/git/github-pr-review', description: '集中处理 PR 提交、Code Review、评论回复、审核操作与协作规范。' },
        { title: 'GitHub Actions 故障排查', href: '/git/github-actions-troubleshooting', description: '集中排查 workflow 不触发、权限不足、Secrets、缓存、Artifact 与 Environment 问题。' },
      ],
      order: ['Git 常用技巧', 'GitHub PR 与 Code Review', 'GitHub Actions 故障排查'],
    },
    sidebar: [
      {
        text: 'Git',
        items: [
          { text: '主题概览', link: '/git/' },
          { text: 'Git 常用技巧', link: '/git/common-tips' },
          { text: 'GitHub PR 与 Code Review', link: '/git/github-pr-review' },
          { text: 'GitHub Actions 故障排查', link: '/git/github-actions-troubleshooting' },
        ],
      },
    ],
  },
  {
    key: 'tools',
    base: '/tools/',
    navText: '工具',
    overviewDescription:
      '收录 Claude Code、Codex、Gemini CLI、Cursor、Vim、iTerm2、Mac 等日常开发工具的实用配置和技巧。',
    landing: {
      eyebrow: 'Tools',
      title: '工具方向',
      intro: '收录 Claude Code、Codex、Gemini CLI、Cursor、Vim、iTerm2、Mac 等日常开发工具的实用配置和技巧，提升开发效率。',
      primary: { title: 'Claude Code 使用指南', href: '/tools/claude-code', description: '整理安装、权限模式、CLAUDE.md、MCP、Hooks 与 VS Code 工作流。' },
      secondary: { title: 'Codex 使用指南', href: '/tools/codex', description: '整理 CLI、IDE、App、Cloud、AGENTS.md、MCP、skills 与自动化用法。' },
      scope: [
        'Claude Code CLI / IDE / 自动化',
        'OpenAI Codex CLI / IDE / Cloud',
        'Gemini CLI / MCP / GEMINI.md / 自动化',
        'Cursor / Agent / Rules / MCP / Background Agents',
        'Vim 编辑器配置与技巧',
        'iTerm2 终端美化与效率',
        'Mac 开发环境与效率工具',
      ],
      docs: [
        { title: 'Claude Code 使用指南', href: '/tools/claude-code', description: '整理安装、权限模式、CLAUDE.md、MCP、Hooks 与 VS Code 工作流。' },
        { title: 'Codex 使用指南', href: '/tools/codex', description: '整理 CLI、IDE、App、Cloud、AGENTS.md、MCP、skills 与自动化用法。' },
        { title: 'Gemini CLI 使用指南', href: '/tools/gemini-cli', description: '整理安装、认证、settings.json、GEMINI.md、MCP、skills、subagents 与自动化用法。' },
        { title: 'Cursor 使用指南', href: '/tools/cursor', description: '整理安装、Tab、Inline Edit、Agent、Rules、MCP、Background Agents、Bugbot 与 CLI 用法。' },
        { title: 'Vim 实用方案', href: '/tools/vim', description: 'Vim 编辑器的实用配置、快捷键和插件推荐。' },
        { title: 'iTerm2 配置指南', href: '/tools/iterm2', description: 'iTerm2 终端的美化配置、快捷操作和效率提升。' },
        { title: 'Mac 效率工具', href: '/tools/mac', description: 'Mac 开发环境搭建和效率工具推荐。' },
      ],
      order: ['Claude Code 使用指南', 'Codex 使用指南', 'Gemini CLI 使用指南', 'Cursor 使用指南', 'Vim 实用方案', 'iTerm2 配置指南', 'Mac 效率工具'],
    },
    sidebar: [
      {
        text: '工具',
        items: [
          { text: '方向概览', link: '/tools/' },
          { text: 'Claude Code 使用指南', link: '/tools/claude-code' },
          { text: 'Codex 使用指南', link: '/tools/codex' },
          { text: 'Gemini CLI 使用指南', link: '/tools/gemini-cli' },
          { text: 'Cursor 使用指南', link: '/tools/cursor' },
          { text: 'Vim 实用方案', link: '/tools/vim' },
          { text: 'iTerm2 配置指南', link: '/tools/iterm2' },
          { text: 'Mac 效率工具', link: '/tools/mac' },
        ],
      },
    ],
  },
]

export const learningOverviewTracks = sections.map((section) => ({
  title: `${section.navText}方向`.replace('AI / Agent方向', 'AI / Agent 方向'),
  href: section.base,
  description: section.overviewDescription,
}))

export const learningOverviewGoals = [
  { title: '想先看路线图', href: '/architecture/architect-learning-roadmap', description: '先从架构路线开始，再延伸到 AI 或 Go 的专题。' },
  { title: '想快速入门 Agent 开发', href: '/ai/agent-learning-guide', description: '先建立 Agent 全局认知，再展开 Tool Calling 和 RAG。' },
  { title: '想强化 Go 高级能力', href: '/golang/guide/source-reading/learning-path', description: '从源码阅读主线切入，再补性能、排障和高频题。' },
  { title: '想补 Rust 学习主线', href: '/rust/learning-path', description: '按阶段补所有权、类型系统、工程化与 async，不必在专题之间来回跳。' },
  { title: '想专项读 Go 源码', href: '/golang/guide/source-reading/', description: '直接进入独立源码阅读模块，按 runtime、网络、编码等主题深挖。' },
  { title: '想做能力自检准备', href: '/architecture/architect-interview-prep-checklist', description: '架构和 Go 都提供适合阶段复盘或面试准备的清单和题目。' },
]

export const homeTracks = sections
  .filter((section) => section.key !== 'tools')
  .map((section) => ({
    title: section.navText,
    description:
      section.key === 'ai'
        ? '从 Agent 模式、Tool Calling 到 RAG 与 workflow，把概念、设计和可落地实现串成完整路径。'
        : section.key === 'architecture'
          ? '围绕系统设计、高并发与分布式治理，构建能复用到真实业务的判断框架与清单。'
          : section.key === 'golang'
            ? '覆盖语言机制、并发、性能与工程实践，把 Go 进阶学习从点状资料整理成面。'
            : section.key === 'rust'
              ? '聚焦所有权、类型系统、错误处理、Cargo 工程化与并发 async，建立 Rust 的核心能力主线。'
            : section.key === 'mysql'
              ? '系统整理 MySQL 核心知识，从 database/sql 基础到高并发场景下的索引、事务、锁与分库分表。'
              : section.key === 'redis'
                ? '系统整理 Redis 核心知识，涵盖缓存治理、分布式锁、高并发集群与支付场景实战。'
            : section.key === 'kafka'
                ? '系统整理 Kafka 核心知识，涵盖消息可靠性、顺序性、积压治理与支付场景实战。'
                : section.key === 'etcd'
                  ? '系统整理 etcd 必须掌握的核心知识，涵盖 Raft、多数派、MVCC revision、Lease/Watch 与运维边界。'
                  : section.key === 'k8s'
                    ? '系统整理 Kubernetes 必备知识，涵盖核心对象、调度与资源、发布治理、网络存储与控制面机制。'
                    : section.key === 'postgresql'
                      ? '系统整理 PostgreSQL 核心知识，涵盖 MVCC、索引、事务、分区表与高可用集群部署。'
                      : section.key === 'ops'
                        ? '将日常运维中反复用到的排障命令、清理流程和管理技巧，整理成可复用的操作指南。'
                        : section.key === 'git'
                          ? '集中整理 Git 工作流、PR 与 Code Review、GitHub Actions 排障、发布与回滚实践。'
                          : '按主题整理路线图、专题和能力自检入口，方便持续学习和回查。',
    href: section.base,
  }))

export const homeHighlights = [
  {
    eyebrow: 'Start here',
    title: '学习导航总览',
    description: '先看总览，再决定从路线、专题还是自检开始，避免在目录里来回跳转。',
    href: '/learning-overview',
  },
  {
    eyebrow: 'AI focus',
    title: 'Agent 学习综合指南',
    description: '适合先搭整体地图，再逐步展开 Tool Calling、RAG 和 workflow 细节。',
    href: '/ai/agent-learning-guide',
  },
  {
    eyebrow: 'System thinking',
    title: '架构能力自检准备清单',
    description: '把架构问题拆到能力项和判断项，适合准备面试或做阶段性复盘。',
    href: '/architecture/architect-interview-prep-checklist',
  },
  {
    eyebrow: 'Go depth',
    title: '30+ 高频能力自检题',
    description: '用题目拉通语言细节、并发模型和工程经验，快速发现知识盲区。',
    href: '/golang/go-top-30-interview-questions',
  },
  {
    eyebrow: 'Source reading',
    title: 'Go 源码精读模块',
    description: '把 runtime、标准库和工程主题拆开管理，避免在主菜单里滚动超长目录。',
    href: '/golang/guide/source-reading/',
  },
]

export const homePrinciples = [
  '按主题组织，不把知识堆成时间线式日志。',
  '优先给出路线和框架，再补专题和资料。',
  '兼顾系统学习、实践落地与能力自检。',
]
